Implement new website
SkriptLang/Skript pull request #2859
Opened 2020-03-12 10:53 UTC by Olyno

### Description
Implementation of the new website of Skript's project.

Here is the (un)official pull request for the new website. Here is a list of tasks that I can't solve myself, and which are required before merge this pull request:

 - [ ] Add [skript-website](https://github.com/Olyno/skript-website) and [skript-website-public](https://github.com/Olyno/skript-website-public) repositories into the [SkriptLang organization](https://github.com/SkriptLang?type=source):
    * ``skript-website``: Contains source code of the website
    * ``skript-website-public``: Public stuff of the website. Created to make easy changes inside the website without need to touch its source code.
 - [ ] Add 2 secrets to [Skript](https://github.com/SkriptLang/Skript)'s repository:
    * ``EMAIL``: The main email of the organization
    * ``ACCESS_TOKEN``: An access token to be able to make commits and push
 - [ ] Create a ``generateDocs`` gradle task to generate Skript documentation in a json file at ``src/main/resources/docs.json``:
    * Please try to reproduce current json format of documentation available in ``skript-website-public/docs.json``.
    * If you add any new information inside it to improve website, or remove some others, please inform me about it, I could make necessary changes about that.
 - [ ] Try the new Github Action task I created:
    * Should clone website public stuff
    * Should create a new branch for updated documentation
    * Should remove old ``docs.json`` file and replace it with the new one generated with ``generateDocs`` gradle task
    * Should push the updated branch in the ``skript-website-public`` repository
 

After this to do list completed, you should be able to have a good implementation of the new website.

If you have any suggestion/bug with new website, please let me know [here](https://github.com/Olyno/skript-website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
If you have any suggestion/bug with this pull request, please let me know in comment of it.

---
**Target Minecraft Versions:** /
**Requirements:** /
**Related Issues:**
 * Main issue: #2561
 * Sub issues:
   * #611
   * #1253
   * #1429
   * #1598
   * #1184
   * #2425

2020-03-12 23:16 UTC, abandonedaccount6235 requested changes

2020-03-12 23:59 UTC, JRoy commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
I do not believe you can make organization authorization tokens so you could setup a dummy user with repository access and grant a token that way. As for github actions: they are non privileged containers by design. They need tokens via organization secrets to become privileged.

2020-03-13 00:00 UTC, JRoy commented on .github/workflows/gradle.yml
> +        git config --global user.email "${EMAIL}"
Github actions containers don't retain information between runs, this shouldn't matter unless I'm not properly understanding your concern

2020-03-13 00:00 UTC, JRoy commented on .github/workflows/gradle.yml
> +        git push origin update/docs -f
+1 I think you can target releases (be them stable or not) for github action triggers but you'd have to look into this

2020-03-13 15:39 UTC, Olyno commented on .github/workflows/gradle.yml
> +        git push origin update/docs -f
Hmm agree with you, I will create another workflow for that, should be better

2020-03-13 15:42 UTC, Olyno commented on .github/workflows/gradle.yml
> +        git config --global user.email "${EMAIL}"
Unlucky for me, I'm not a pro git and the only way to make a push for me is this way. Of course if you see a better way, please use it :)

2020-03-13 15:50 UTC, Olyno commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
> is this access token made at a user level or a organization level?
I think we can do it with organization, need to see.
> who else can see what the token is?
No one. When a secret token is added, you only can remove it, so you never can see what the token is (same for logs, secrets are replaced with ``*****``)
> also - is there no way for a github action to just handle this automatically? the repo is hosted on github after all
The only way I see to replace current docs is simply to push it. So Github Action can't handle everything, like access token that we need to setup manually.

2020-03-13 19:20 UTC, bensku commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
The token could be leaked (e.g. sending it over internet) by a malicious PR. I wonder how we could restrict token access to actions in only whitelisted branches.

2020-03-13 21:27 UTC, Olyno commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
The token literally can't be leak. You just have to add the token in the ``secrets`` section, and when you added it, you only can remove it, no one can see it. I really don't see how the access token could be leaked except by the person who created and added this one to the repository.

2020-03-22 12:50 UTC, bensku commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
Sorry for late response. Actions runner can access the token, and do whatever it wants with it. We need to ensure that this does not happen with pull request builds.

2020-03-22 16:29 UTC, Olyno commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
I did a new workflow for the generation of the docs. It is triggered only when a new release is published.

2020-03-22 19:26 UTC, bensku commented on .github/workflows/gradle.yml
> +        git clone https://${ACCESS_TOKEN}@github.com/SkriptLang/skript-website-public.git
Ok, that should do the job.

2020-03-22 23:01 UTC, Olyno commented
**Important note:** I can't transfert any of my repositories (including ``skript-website`` and ``skript-website-public``) to SkriptLang because it requiers that I have "the permission to create public repositories on SkriptLang"

2021-03-06 17:05 UTC, Olyno commented
Closing this pull request for the moment. I have bigger projects for that, as a new design, a blog system and a lot of more.

2021-03-06 17:05 UTC, closed without merging