Expr max minecart speed
SkriptLang/Skript pull request #3218
Opened 2020-07-26 10:50 UTC by DeltaRays

**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2020-07-26 11:26 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/expressions/ExprMaxMinecartSpeed.java
> +					if (m instanceof Minecart) ((Minecart) m).setMaxSpeed(((Number) delta[0]).doubleValue());
As stated before on Discord, the condition and void method should not be on the same line.

2020-07-30 20:12 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxMinecartSpeed.java
> +			if (mode == ChangeMode.RESET) getExpr().stream(e).forEach(m -> {
the IF statement should be on it's own line

2020-07-30 20:12 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxMinecartSpeed.java
> +		return (mode == ChangeMode.ADD || mode == ChangeMode.REMOVE || mode == ChangeMode.RESET || mode == ChangeMode.SET) ? CollectionUtils.array(Number.class) : null;
Can you put this statement into a switch?

2020-07-30 20:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxMinecartSpeed.java
> +				getExpr().stream(e).forEach(m -> {
Oh, also, can you switch these to for loops (based on other PRs / feedback to stay consistent)?

2020-09-26 18:25 UTC, APickledWalrus requested changes

2020-09-26 18:25 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxMinecartSpeed.java
> +	public void change(Event e, @Nullable Object[] delta, ChangeMode mode) {
The switch statement should have a default case that asserts false

2020-10-04 19:53 UTC, ShaneBeee approved these changes
Looks good to me

2020-10-06 22:07 UTC, ShaneBeee approved these changes

2020-10-06 22:08 UTC, APickledWalrus approved these changes

2020-10-06 22:09 UTC, merged

2020-10-06 22:09 UTC, ShaneBeee commented
Thank you for your contribution