Add CondIsUnbreakable
SkriptLang/Skript pull request #3410
Opened 2020-09-27 13:32 UTC by Mr-Darth

### Description
Adds a condition to check if an itemtype is unbreakable.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2020-09-27 13:44 UTC, TPGamesNL commented
AFAIK `ItemMeta#isUnbreakable` was added in 1.11.x

2020-09-27 14:24 UTC, Mr-Darth commented
> AFAIK `ItemMeta#isUnbreakable` was added in 1.11.x

Fixed, sorry 😅

2020-09-27 14:48 UTC, TPGamesNL commented
> > AFAIK `ItemMeta#isUnbreakable` was added in 1.11.x
> 
> Fixed, sorry 😅

No worries. 2 suggestions: you can add compatibility by using `ItemFlag`s and it could be a nice addition to add a way to make an item unbreakable as well.

2020-10-05 08:14 UTC, ShaneBeee requested changes
could small changes, other than that looks good to me

2020-10-05 08:14 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/conditions/CondIsUnbreakable.java
> + * Copyright 2011-2017 Peter Güttinger and contributors
bensku has updated the last line of the license heard which can be found [**HERE**](https://github.com/SkriptLang/Skript/blob/master/licenseheader.txt) to update accordingly

2020-10-05 08:14 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/conditions/CondIsUnbreakable.java
> +@RequiredPlugins("1.11+")
To keep consistency with the rest of this project, I suggestion:
```suggestion
@RequiredPlugins("Minecraft 1.11+")
```

2020-10-06 09:27 UTC, ShaneBeee approved these changes

2020-10-06 09:29 UTC, ShaneBeee approved these changes

2020-10-06 10:57 UTC, APickledWalrus approved these changes

2020-10-06 21:07 UTC, merged

2020-10-06 21:07 UTC, ShaneBeee commented
Thank you for your contribution