Add CondIsVectorNormalized
SkriptLang/Skript pull request #3417
Opened 2020-09-29 20:06 UTC by youngmasterseth

### Description

Add is vector normalized property condition
---
**Target Minecraft Versions:** Any
**Requirements:** 1.13+
**Related Issues:** n/a

2020-09-29 20:14 UTC, APickledWalrus requested changes

2020-09-29 20:14 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
> +		register(CondIsVectorNormalized.class, "normalized", "vectors");
If this only works on 1.13+ you should be checking whether the method exists.
e.g.
```java
Skript.methodExists(Vector.class, "isNormalized")
```

2020-09-29 20:18 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
> +@RequiredPlugins("1.13 or newer")
Looks like this was added in 1.13.2 from what I can see on the javadocs
```suggestion
@RequiredPlugins("1.13.2 or newer")
```

2020-10-02 00:53 UTC, APickledWalrus requested changes

2020-10-02 00:53 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
> +		if (Skript.methodExists(Vector.class, "isNormalized")) {register(CondIsVectorNormalized.class, "normalized", "vectors");}
Formatting needs fixed
```suggestion
		if (Skript.methodExists(Vector.class, "isNormalized")) {
			register(CondIsVectorNormalized.class, "normalized", "vectors");
		}
```

2020-10-02 04:34 UTC, DeceptionYMS approved these changes

2020-10-05 06:18 UTC, ShaneBeee requested changes
Just a couple small changes

2020-10-05 06:18 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
> + * Copyright 2011-2017 Peter Güttinger and contributors
bensku has updated the last line of the license header, you can find the update version [**HERE**](https://github.com/SkriptLang/Skript/blob/master/licenseheader.txt) and update accordingly

2020-10-05 06:18 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
> +@RequiredPlugins("1.13.2 or newer")
To keep consistency with other classes, we should probably be doing "Minecraft 1.13.2+" here

2020-10-05 18:08 UTC, closed without merging