Add EffOpenBook
SkriptLang/Skript pull request #3431
Opened 2020-10-04 18:38 UTC by OfficialDonut

### Description
Added open book effect to open written books to players.

---
**Target Minecraft Versions:** any
**Requirements:** no
**Related Issues:** no

2020-10-04 18:58 UTC, APickledWalrus requested changes

2020-10-04 18:58 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffOpenBook.java
> +	public boolean init(final Expression<?>[] exprs, final int matchedPattern, final Kleenean isDelayed, final SkriptParser.ParseResult parseResult) {
You should import ParseResult directly

2020-10-04 18:58 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffOpenBook.java
> +	}
Nitpicky but could you add a space after here
```suggestion
	}

```

2020-10-04 18:58 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffOpenBook.java
> +		Skript.registerEffect(EffOpenBook.class, "(open|show) book %itemtype% to %players%");
```suggestion
		Skript.registerEffect(EffOpenBook.class, "(open|show) book %itemtype% (to|for) %players%");
```

2020-10-04 20:00 UTC, Pikachu920 requested changes

2020-10-04 20:01 UTC, ShaneBeee commented on .gitattributes
> -        * text=auto
that could be due to it not being on the 2.5 branch, just updated it, should go away

2020-10-04 20:08 UTC, OfficialDonut commented on src/main/java/ch/njol/skript/effects/EffOpenBook.java
> +			@Nullable ItemStack itemStack = itemType.getRandom();
It had a warning
```
Expression 'book.getSingle(e)' might evaluate to null but is assigned to a variable that is annotated with @NotNull
```

2020-10-05 14:46 UTC, APickledWalrus submitted a review, later dismissed
LGTM

2020-10-05 22:11 UTC, ShaneBeee approved these changes

2020-10-06 08:55 UTC, ShaneBeee requested changes
small change.

2020-10-06 08:55 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/effects/EffOpenBook.java
> +		if (itemType != null && itemType.getMaterial() == Material.WRITTEN_BOOK) {
In the event a Bukkit material is changed or what not, an alias should be used here instead, here is an example of another class with books doing it:
https://github.com/SkriptLang/Skript/blob/99af0a13a7cefb0e6ed890e775093a51fc3802bf/src/main/java/ch/njol/skript/expressions/ExprBookTitle.java#L45
https://github.com/SkriptLang/Skript/blob/99af0a13a7cefb0e6ed890e775093a51fc3802bf/src/main/java/ch/njol/skript/expressions/ExprBookTitle.java#L54-L59

in this case you could use the ItemType#equals method instead before getting the item stack.

2020-10-06 21:29 UTC, ShaneBeee approved these changes

2020-10-06 21:30 UTC, APickledWalrus approved these changes

2020-10-06 21:30 UTC, merged