Force attack
SkriptLang/Skript pull request #3432
Opened 2020-10-04 19:09 UTC by OfficialDonut

### Description
Add force attack effect to make a living entity attack an entity.

---
**Target Minecraft Versions:** 1.15+
**Requirements:** 1.15+
**Related Issues:** no

2020-10-04 19:42 UTC, ShaneBeee requested changes
Looks good to me. One small request, and one small suggestion for readability.

2020-10-04 19:42 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +@Description("Makes a living entity attack an entity with a melee attack")
Super small nitpick, but a description should end in a period, to keep consistent with other descriptions

2020-10-04 19:42 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +@Examples("spawn a wolf at player's location\nmake last spawned wolf attack player")
In my opinion, for readability this should be split, ex:
```java
@Examples({"spawn a wolf at player's location",
    "make last spawned wolf attack player"})
```

2020-10-05 07:56 UTC, ShaneBeee submitted a review, later dismissed

2020-10-05 15:38 UTC, APickledWalrus requested changes

2020-10-05 15:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +		if (!ATTACK_IS_SUPPORTED) {
Should be checked in registration.

2020-10-05 15:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +		Skript.registerEffect(EffForceAttack.class, "make %livingentitys% attack %entity%", "force %livingentitys% to attack %entity%");
Patterns should be on their own lines. Also, shouldn't it be `livingentities`? I don't know if that actually matters though.

2020-10-05 15:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +		@Nullable Entity target = this.target.getSingle(e);
We usually don't include annotations like this. It should be okay for the warning to be there.

2020-10-05 20:40 UTC, APickledWalrus requested changes

2020-10-05 20:40 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +@RequiredPlugins("1.15.2 or newer")
```suggestion
@RequiredPlugins("Minecraft 1.15.2+")
```

2020-10-05 20:40 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffForceAttack.java
> +			Skript.error("The force attack effect requires server version 1.15.2 or newer");
```suggestion
			Skript.error("The force attack effect requires Minecraft 1.15.2 or newer");
```

2020-10-05 22:10 UTC, ShaneBeee approved these changes

2020-10-05 23:06 UTC, APickledWalrus approved these changes

2020-10-06 08:30 UTC, merged