Improve public syntax information API
SkriptLang/Skript pull request #3558
Opened 2020-11-21 02:09 UTC by NickAcPT

### Description

This PR introduces some changes that will allow documentation extraction tools like ResourceSync(skUnity), [SkriptHubDocsTool](https://github.com/SkriptHub/SkriptHubDocsTool) (Skript Hub) and [DocExtractionTool](https://github.com/SkriptInsight/DocExtractionTool)(SkriptInsight) will benefit from these changes.

Some of the changes include the following:
 - Store and expose Skript Expression types (The expression order is different depending on the expression's type)
 - Expose Syntax Element information with getters
 - Expose Event Value information with getters
 - Expose Language information with getters
 - Expose Function Parameter information with getters

### Why this change?

When tools need to fetch information from Skript, they have to resort to using Reflection.

https://github.com/SkriptHub/SkriptHubDocsTool/blob/70ae1be649a6797e98e2b108ebaee518d6789f65/src/main/java/net/skripthub/docstool/utils/EventValuesGetter.java#L28-L40

---
**Target Minecraft Versions:** any

2020-11-21 09:40 UTC, ShaneBeee approved these changes
Looks good to me. I would like to see what other members of the team have to say before merging.

2020-11-21 09:42 UTC, ShaneBeee approved these changes
The base branch was changed.

2020-11-22 07:33 UTC, NickAcPT commented
@ShaneBeee 
> The base branch was changed.

Fixed it, but almost forgot to ask.. any particular reason as to why? ~~I would've asked on Discord, but you know the drill.~~

Either way, thanks for your review. If there's anything I missed in regards of exposing Syntax information, just let me know.

2020-11-22 09:07 UTC, ShaneBeee commented
> Fixed it, but almost forgot to ask.. any particular reason as to why?

Are you referring to the base branch change? 
Master is going to be our release branch, where as the dev branches will be the branches we work on, until we are ready to release.

2020-11-25 18:45 UTC, APickledWalrus requested changes
two small things

2020-11-25 18:45 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/localization/Language.java
> +		if (localized != null) return new HashMap<>(localized);
return should be on its own line

2020-11-25 18:45 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +			if (excludes != null) return Arrays.copyOf(excludes, excludes.length);
same as above

2020-11-25 19:29 UTC, NickAcPT commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +			if (excludes != null) return Arrays.copyOf(excludes, excludes.length);
Fixed this in abb07d1.

2020-11-25 19:29 UTC, NickAcPT commented on src/main/java/ch/njol/skript/localization/Language.java
> +		if (localized != null) return new HashMap<>(localized);
Fixed this in abb07d1.

2020-11-25 19:31 UTC, APickledWalrus approved these changes
LGTM 🙂

2020-11-25 19:57 UTC, ShaneBeee approved these changes

2020-11-25 20:02 UTC, ShaneBeee commented
Im not sure If you turned off "Allow Edits" (the pic is an example from one of my PRs)
<img width="393" alt="Screen Shot 2020-11-25 at 12 00 41 PM" src="https://user-images.githubusercontent.com/20008482/100276159-ec49a480-2f15-11eb-9862-55d783eb1f9a.png">

But I don't have an option to update the branch:
<img width="968" alt="Screen Shot 2020-11-25 at 11 59 07 AM" src="https://user-images.githubusercontent.com/20008482/100276179-f4a1df80-2f15-11eb-91fd-595ada1c96e9.png">

Could you please update your fork/branch to the dev-2.5 branch :)
Just want to make sure everything is A-OK before merging!

2020-11-25 20:05 UTC, NickAcPT commented
> Im not sure If you turned off "Allow Edits" (the pic is an example from one of my PRs)
> <img alt="Screen Shot 2020-11-25 at 12 00 41 PM" width="393" src="https://user-images.githubusercontent.com/20008482/100276159-ec49a480-2f15-11eb-9862-55d783eb1f9a.png">
> 
> But I don't have an option to update the branch:
> <img alt="Screen Shot 2020-11-25 at 11 59 07 AM" width="968" src="https://user-images.githubusercontent.com/20008482/100276179-f4a1df80-2f15-11eb-91fd-595ada1c96e9.png">
> 
> Could you please update your fork/branch to the dev-2.5 branch :)
> Just want to make sure everything is A-OK before merging!

That's odd.. I don't have that option on my side.. But I merged it anyway. I'm so sorry for that trouble and thanks for your time.

2020-11-25 20:05 UTC, ShaneBeee commented
> > Im not sure If you turned off "Allow Edits" (the pic is an example from one of my PRs)
> > <img alt="Screen Shot 2020-11-25 at 12 00 41 PM" width="393" src="https://user-images.githubusercontent.com/20008482/100276159-ec49a480-2f15-11eb-9862-55d783eb1f9a.png">
> > But I don't have an option to update the branch:
> > <img alt="Screen Shot 2020-11-25 at 11 59 07 AM" width="968" src="https://user-images.githubusercontent.com/20008482/100276179-f4a1df80-2f15-11eb-91fd-595ada1c96e9.png">
> > Could you please update your fork/branch to the dev-2.5 branch :)
> > Just want to make sure everything is A-OK before merging!
> 
> That's odd.. I don't have that option on my side.. But I merged it anyway. I'm so sorry for that trouble and thanks for your time.

No need to apologize. Thanks for the quick update 👍

2020-11-25 20:28 UTC, merged