Fix striping without validating
SkriptLang/Skript pull request #3794
Opened 2021-03-07 11:43 UTC by AyhamAl-Ali

Fixing ChatColor striping any and all `<`, `>`, `&` and `§` without checking if they are valid or not

### Description

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:**

2021-03-07 15:10 UTC, APickledWalrus requested changes

2021-03-07 15:10 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/util/chat/ChatMessages.java
> +		plain = plain.replaceAll("<(link|url|run command|suggest command|tooltip):(.*?)>", "$2").replaceAll("<\\w+? ?\\w+?>", "").replaceAll("(?i)[&§][0-9a-folkrnm]", "").replaceAll("(?i)<#[0-9a-z]{6}>", "
You don't need to worry about stripping HEX codes. They will have been parsed by this point and formatted like `§x§1§2§3§4§5§6` so you might want to make sure they are covered properly when you replace &/§ symbols. Ideally you should only do that when HEX codes are enabled and when it is a valid HEX tag (e.g. search for that kind of formatted HEX string).

2021-03-07 15:59 UTC, AyhamAl-Ali commented
Regardless of my IDE wrapping lines I didn't notice that sorry, I have removed the HEX code `<#123456>` format as you said it will be already parsed to `&x&1&2&3&4&5&6` format or `§` instead of `&`

So it will only do that when HEX codes are supported as for the remaining 6 colors after the `&x` they will already be stripped by the old `&` color strip regex ecpr

2021-04-30 02:44 UTC, AyhamAl-Ali commented
Missing `2.5` tag or?

2021-05-09 23:00 UTC, APickledWalrus requested changes
Just these minor things. Other than that, LGTM. Another review looking over the regex checks is appreciated too :D

2021-05-09 23:00 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/util/chat/ChatMessages.java
> +}
```suggestion
}

```

2021-05-09 23:00 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/util/chat/ChatMessages.java
> +			2nd Replace: strips colors using <color name> (Note: this regex expr repalce any two words surrounded by <> such as <any text>)
```suggestion
			2nd Replace: strips colors using <color name> (NOTE: This regex expression replaces any two words surrounded by <> such as <any text>)
```

2021-06-30 09:15 UTC, closed without merging

2021-06-30 13:59 UTC, AyhamAl-Ali commented
Closed this by accident, will re-open in a bit.