Make random vector expression components signed
SkriptLang/Skript pull request #3821
Opened 2021-03-15 17:45 UTC by TPGamesNL

### Description
Updated `ExprVectorRandom` to be able to return both positive and negative components.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3135

2021-03-19 06:06 UTC, Wealthyturtle commented on src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java
> +	}
You could do
```java
	private static double randomSignedDouble () {
		return random.nextDouble() * (random.nextBoolean() ? 1 : -1);
	}
```

2021-03-20 09:19 UTC, Anarchick commented on src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java
>  @Since("2.2-dev28")
don't forget to update :)

2021-05-09 22:03 UTC, APickledWalrus requested changes

2021-05-09 22:03 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java
> +	private static double randomSignedDouble () {
```suggestion
	private static double randomSignedDouble() {
```

2022-07-13 02:28 UTC, TheLimeGlass approved these changes

2022-07-13 03:59 UTC, Wealthyturtle approved these changes

2022-07-13 07:59 UTC, merged