Fix variable conflict warnings
SkriptLang/Skript pull request #3979
Opened 2021-05-10 14:42 UTC by TPGamesNL

### Description
Fixes both the issue described in #3932 and the error giving the wrong variables (local variable token removed).

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3932

2021-05-11 08:12 UTC, TPGamesNL commented
> Correct me if I am wrong but from I can see from the test results, this change makes the warning detect the same variable as a conflict? Like, it detects `set {_test} to "test"` and `send "%{_test}%"` as a conflict or so it seems.

Oh yea, you're right on that, I accidentally removed the check for that. 
> Besides, I'd potentially prefer to get rid of this warning all altogether, almost every user I know disables them as they're just annoying. Of course, this is kind of because the warning wrongly consider some cases as conflicts but even without that issue, I do not consider it a feature that's worth all this hassle.

I'll convert this PR to instead remove the warnings altogether.

2021-05-13 08:08 UTC, TPGamesNL commented
I removed the method `Parser#getVariableNamePattern`, which is abstract for all types with a parser, so most addons won't compile after merging this (although it shouldn't affect runtime)

2021-05-13 19:50 UTC, FranKusmiruk requested changes

2021-05-13 19:50 UTC, FranKusmiruk commented on src/main/java/ch/njol/skript/classes/Parser.java
> -	public abstract String getVariableNamePattern();
Don't delete it here, just deprecate it. If you remove it we're going to break ABI compatibility, and that means a lot of addons

2021-05-13 21:03 UTC, FranKusmiruk approved these changes

2021-10-30 11:43 UTC, merged