Updated the fish event to support getting the player, the hook and the state
SkriptLang/Skript pull request #3992
Opened 2021-05-12 17:49 UTC by DeltaRays

### Description

The title says it all
---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #3262

2021-08-16 14:47 UTC, APickledWalrus requested changes
Nothing major ;D

I was also wondering if this event could be added to [ExprExperience](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprExperience.java).
`the dropped exp` could be used for `PlayerFishEvent#getExpToDrop` and `PlayerFishEvent#setExpToDrop`

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +		Skript.registerEvent("Fishing", EvtFish.class, PlayerFishEvent.class, "[player] fish[ing] [state[s] [of] %-fishingstates%]");
Since you're registering this event in its own class I would probably just register the event values here too.

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +@Examples({"on fishing state of fish caught:",
I would move Examples to below Description

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +		}
```suggestion
		if (states != null)
			this.states.addAll(Arrays.asList(states.getAll()));
		return true;
```

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +	public boolean init(Literal<?>[] args, int matchedPattern, SkriptParser.ParseResult parseResult) {
Direct import for ParseResult

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +public class ExprFishingHook extends EventValueExpression<FishHook> {
```suggestion
public class ExprFishingHook extends EventValueExpression<FishHook> {

```
Space after class declaration

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +	@SuppressWarnings("null")
Is this suppression still needed? There have been a lot of updates to annotation stuff recently-ish.

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +		if (!ScriptLoader.isCurrentEvent(PlayerFishEvent.class)) {
Should switch to ParserInstance (`getParser()`)

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +	public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean isDelayed, ParseResult parser) {
Is init actually needed? Skript should handle checking that the event has a fishing hook event value.

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprFishingState.java
> +public class ExprFishingState extends EventValueExpression<PlayerFishEvent.State> {
Could probably directly import State

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/resources/lang/english.lang
> +	in_ground: in ground
```suggestion
	in_ground: hook in the ground
```
Maybe something like this too? Up for debate

2021-08-16 14:47 UTC, APickledWalrus commented on src/main/resources/lang/english.lang
> +fishing states:
I feel like some of these names will sound odd in script lines, but I am also not too sure how to improve them. Anyone have any ideas?

2021-08-16 18:01 UTC, TPGamesNL commented
When handling review, also look at https://github.com/SkriptLang/Skript/pull/3994, I reviewed part of this stuff there because you added it to that branch

2021-08-17 08:39 UTC, TPGamesNL commented
Closing in favour of https://github.com/SkriptLang/Skript/pull/4284

2021-08-17 08:39 UTC, closed without merging