Arrow damage
SkriptLang/Skript pull request #3994
Opened 2021-05-12 19:17 UTC by DeltaRays

### Description

Added the 'arrow damage' property expression to arrows
---
**Target Minecraft Versions:** 1.13+
**Requirements:** none 
**Related Issues:** #3207

2021-05-13 07:46 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> +			return null;
Equal catch block can be collapsed

2021-05-13 07:46 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> +}
Add newline

2021-05-13 07:47 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprArrowDamage.java
> +				if (strength < 0) return;
put return on next line

2021-05-13 07:47 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprArrowDamage.java
> +}
newline

2021-05-13 07:48 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprArrowDamage.java
> +					if (dmg < 0) continue;
body of if statement should be on new line

2021-06-13 19:27 UTC, DeltaRays commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> +			return null;
Thanks

2021-06-14 10:42 UTC, TPGamesNL requested changes

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> +	public static Object getShooter(final @Nullable Projectile p) {
unused methods (same for setShooter), so L57-96 can be removed

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> + * @author Peter Güttinger
author tag can be removed

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> +public abstract class ProjectileUtils {
I don't know why other classes in Skript have this pattern, but you don't need to make it abstract with a private constructor for utility classes

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/bukkitutil/ProjectileUtils.java
> +	public static Double getDamage(Projectile arrow){
Method is nullable, annotate it as such

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +				.user("fish(ing|) ?states?")
(ing|) should be replaced with (ing)? 
Also, unrelated, but can you set the string on L1965 to `enchant(ment)? ?offers?`, someone mistook the string for a Skript pattern

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +						return "\\S";
regex doesn't match all possible results of `toVariableNameString`, `\S` only matches a single character

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +    //HorseJumpEvent
indentation

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +	EnumSet<PlayerFishEvent.State> states = EnumSet.noneOf(PlayerFishEvent.State.class);
make this private final
I don't think there's much advantage here to using an EnumSet, you could make this a nullable list of fish states, in this case you can directly set the field to `(Literal<PlayerFishEvent.State>) args[0]` in init, no need for an if statement (you do have to not make it final in that case)

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +			return true;
`return true` can be extracted from if/else body

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/events/EvtFish.java
> +public class EvtFish extends SkriptEvent {
isn't this PR for arrow damage, not fishing stuff?

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/events/SimpleEvents.java
> -		Skript.registerEvent("Fishing", SimpleEvent.class, PlayerFishEvent.class, "[player] fish[ing]")
an import can be removed because of this

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprArrowDamage.java
> +	@Nullable
spacing

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprArrowDamage.java
> +				if (strength < 0)
condition always false, see L66

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +	static {
spacing

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +		if (!ScriptLoader.isCurrentEvent(PlayerFishEvent.class)) {
method deprecated, same with L57 getCurrentEventName

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprFishingHook.java
> +			Skript.error("There's no fishing hook in " + Utils.a(ScriptLoader.getCurrentEventName()) + " event.", ErrorQuality.SEMANTIC_ERROR);
SEMANTIC_ERROR is default, argument can be removed

2021-06-14 10:42 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprFishingState.java
> +public class ExprFishingState extends EventValueExpression<PlayerFishEvent.State> {
needs init to check event class

2022-03-01 12:06 UTC, AyhamAl-Ali commented
Unfinished PR, if anyone wants to take over/redo feel free to

2022-03-01 12:06 UTC, closed without merging