Rework EffBroadcast to support advanced formatting
SkriptLang/Skript pull request #4197
Opened 2021-07-16 20:39 UTC by APickledWalrus

### Description
This PR reworks EffBroadcast to support advanced formatting by using similar handling to EffMessage.
(I know this is a fixes branch but this is actually an enhancement as it was intended behavior)

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:** #4156

2021-07-17 10:23 UTC, TPGamesNL requested changes
Looks good!
What is sent to console when you use advanced formatting?

2021-07-17 10:23 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/effects/EffBroadcast.java
> +				if (message instanceof VariableString) {
VariableString is an expression, and expression's getter (e.g. `message.getArray(e)`) will not return another expression

2021-07-17 10:23 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/effects/EffBroadcast.java
> +@Description("Broadcasts a message to the server. Only formatting options supported by console (i.e. colors) are supported.")
```suggestion
@Description("Broadcasts a message to the server.")
```

2021-07-17 14:40 UTC, APickledWalrus commented
> What is sent to console when you use advanced formatting?

![image](https://user-images.githubusercontent.com/29044720/126040492-05cb65ce-cb07-44bc-8332-43f06a63afce.png)
The advanced stuff seems to be ignored :)

2021-12-06 18:00 UTC, TPGamesNL approved these changes

2021-12-06 18:04 UTC, merged