Update ExprWorld.java
SkriptLang/Skript pull request #4217
Opened 2021-07-23 18:06 UTC by TUCAOEVER

Support world of chunk expression.

### Description

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:**

2021-07-23 18:22 UTC, AyhamAl-Ali commented
You should mention this issue (#4215) in your PR

2021-07-24 02:48 UTC, TUCAOEVER commented
> You should mention this issue (#4215) in your PR

Thx for reminding.

2021-07-30 12:55 UTC, TPGamesNL requested changes

2021-07-30 12:55 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprWorld.java
> -				assert false : o;
Keep the assertion (after the last if block)

2021-07-30 12:55 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprWorld.java
> +		"set {_world} to world of chunk at location of targeted entity"})
Not a good example (`world of targeted entity`), you also don't have to add an example. If you do want to, do something like `set {_world} to world of {_chunk}` or `set {_world} to world of event-chunk`

2021-07-31 08:37 UTC, TPGamesNL approved these changes

2021-10-30 10:22 UTC, merged

2021-10-30 10:23 UTC, TPGamesNL commented
@TUCAOEVER Next time, please don't delete your branch while the PR using it is still open \:)