Rewrite ExprFurnaceSlot
SkriptLang/Skript pull request #4281
Opened 2021-08-16 02:10 UTC by APickledWalrus

### Description
This PR aims to rewrite and fix ExprFurnaceSlot. In its current state, it is inaccurate and produces several NPEs in various situations.

This PR also handles #2889, although that issue was actually user error. This is because they were using `block's fuel slot` which does not refer to the fuel slot in a burn event, but rather the fuel slot of the event block in a burn event. However, event values do not currently work and produce NPEs (this is because it is currently a PropertyExpression that may not have an expression, which is not allowed).

This PR also makes several syntax changes, meaning it may be incompatible with current scripts. The new syntax is essentially like this:
```
[the] (ore slot|fuel slot|result|result slot)
[the] (ore|fuel|result) slot[s] of %blocks%
%blocks%'[s] (ore|fuel|result) slot[s]
```

This PR also adds a distinction between `the result` and `the result slot`.
`the result` refers to the product in a smelt event (the item to be added to the output slot)
`the result slot` refers to the output (or result) slot in a furnace. This is where `the result` ends up.
I have also updated the documentation to give as much detail to users as possible.

These events are kind of difficult for Skript to handle because of so many factors, but I tried to handle it the best I could. Thus, the code is not exactly the prettiest, and ideas are very welcome.

Initial testing indicates that everything is working as expected, but it would be good if more people could test.
Because of the syntax changes and such in this PR, it should probably target a version like 2.6.1.

---
**Target Minecraft Versions:** Any (I think)
**Requirements:** None
**Related Issues:** #2889

2022-07-01 08:08 UTC, TheLimeGlass approved these changes

2022-07-01 11:23 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +				"[the] (0¦ore slot|1¦fuel slot|2¦result [(5¦slot)])",
Should use colons instead of broken pipes now

2022-11-11 11:53 UTC, AyhamAl-Ali requested changes

2022-11-11 11:53 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +	protected Slot[] get(Event e) {
```suggestion
	protected Slot[] get(Event event) {
```

2022-11-11 11:53 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +	public String toString(@Nullable Event e, boolean debug) {
```suggestion
	public String toString(@Nullable Event event, boolean debug) {
```

2022-12-11 21:55 UTC, AyhamAl-Ali requested changes
Solid ⚡

2022-12-11 21:55 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +	"Thus you may wish to use the event block in this case (e.g. <code>the fuel slot of the event-block</code>) to get accurate values if needed."
```suggestion
	"Note that if values other than <code>the result</code> are changed, event values may not accurately reflect the actual items in a furnace.",
	"Thus you may wish to use the event block in this case (e.g. <code>the fuel slot of the event-block</code>) to get accurate values if needed."
```

2022-12-11 21:55 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +	"and <code>the result slot</code> is the output slot of a furnace (where <code>the result</code> will end up).",
```suggestion
	"Note that <code>the result</code> and <code>the result slot</code> refer to separate things. <code>the result</code> is the product in a smelt event" +
	" and <code>the result slot</code> is the output slot of a furnace (where <code>the result</code> will end up).",
```

2023-07-31 17:12 UTC, sovdeeth requested changes
A few nitpicks, mainly just as a reminder this pr exists. Also, "Ore slot" is a useful name but might cause confusion, as more than just ore can go in a furnace. Do you think it's worth it to support something like "input slot" as well?

2023-07-31 17:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +	" and <code>the result slot</code> is the output slot of a furnace (where <code>the result</code> will end up).",
```suggestion
	"Note that <code>the result</code> and <code>the result slot</code> refer to separate things. <code>the result</code> is the product in a smelt event " +
	"and <code>the result slot</code> is the output slot of a furnace (where <code>the result</code> will end up).",
```

2023-07-31 17:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
> +				return new Slot[0];
Should this not `continue` instead? A block that isn't a furnace should just return null for itself, not cause the entire expression to return null in my opinion.

2023-12-18 20:35 UTC, sovdeeth approved these changes

2024-01-01 21:14 UTC, merged