🚀 Vehicle Improvements
SkriptLang/Skript pull request #4329
Opened 2021-09-13 01:02 UTC by AyhamAl-Ali

### Description

- :heavy_check_mark: Added more vehicle events (Collision, Move)
- :heavy_check_mark: Added `vehicle` expression
- :heavy_check_mark: Added vehicle collision cause expression (see note below)
- :heavy_check_mark: Fixed event values of vehicles
- :heavy_check_mark: Changed Vehicle PropertyExpression to VehicleOf
- :heavy_check_mark: Changed Vehicle Effect name to Ride / Mount (Vehicle here doesn't make sense and also to not conflict)

**NOTE:** Vehicle collision cause currently returns an object type which probably makes it lose some of its information as a block or an entity as I have tried to collide with a zombie named "Hi" and executing `name of collision cause` only returned "zombie"

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:** #4328 #1337

2021-11-07 15:57 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/events/EvtVehicleCollision.java
> +				"\t\tpush vehicle upwards with force 1.5")
Self note: use only `\t`

2021-11-07 16:02 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprVehicle.java
> +		System.out.println(getParser().getCurrentEvents()[0].toString());
Self note: debug statement

2021-11-07 16:02 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprVehicle.java
> +			Skript.error("Cannot use 'vehicle' outside of a vehicle related events.");
Self note: remove period

2021-11-07 16:05 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprVehicleCollisionCause.java
> +		Skript.registerExpression(ExprVehicleCollisionCause.class, Object.class, ExpressionType.SIMPLE, "[the] [vehicle] collision cause");
Self note: Would be better to make `vehicle` part required

2022-01-14 18:19 UTC, TheLimeGlass requested changes

2022-01-14 18:19 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +import org.bukkit.event.vehicle.*;
We can't be doing wild card imports please

2022-01-14 18:19 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/events/SimpleEvents.java
> +import org.bukkit.event.vehicle.*;
^ wild card

2022-01-14 18:19 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprVehicleOf.java
> +		assert false;
Is this assert false required?

2022-01-14 18:23 UTC, TheLimeGlass commented
Say you have a list of multiple entities and they're going to be set onto 1 vehicle, wouldn't it be a better implementation to have all the entities stack onto eachother riding the set vehicle 
![image](https://user-images.githubusercontent.com/16087552/149565994-e6c2b5d3-ee88-4ccd-b533-90e8a0ce10f5.png)

2022-02-20 18:03 UTC, TPGamesNL commented
You should create the vehicle entity data instead of the vehicle expression (e.g. just like player or any other entity)

2024-07-16 06:40 UTC, sovdeeth commented
Closing due to inactivity.

2024-07-16 06:40 UTC, closed without merging