Make Variable toString always include variable name
SkriptLang/Skript pull request #4397
Opened 2021-10-31 14:39 UTC by TPGamesNL

### Description
Makes Variable#toString(Event, boolean) always include the name of the variable.
Example:
![image](https://user-images.githubusercontent.com/29547183/139588777-35151057-e50b-4920-a1b5-885b6d151b6b.png)
![image](https://user-images.githubusercontent.com/29547183/139588805-df72528b-3f36-42e6-aa89-3a0114638157.png)

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4294

2021-11-01 15:26 UTC, TheLimeGlass reviewed
Looks good

2021-11-11 05:08 UTC, Pikachu920 requested changes

2021-11-11 05:08 UTC, Pikachu920 commented on src/main/java/ch/njol/skript/lang/Variable.java
> +			stringBuilder.append("_");
this should probably use https://github.com/SkriptLang/Skript/blob/adb683196f44582251e44b998c4a0d88edd41606/src/main/java/ch/njol/skript/lang/Variable.java#L72

2021-11-11 18:34 UTC, Pikachu920 approved these changes

2021-11-12 10:20 UTC, merged