Update korean.lang
SkriptLang/Skript pull request #4401
Opened 2021-11-01 02:58 UTC by alphaimetal0903

### Description
Updated version of #4127 
Grammar errors and incorrect translation solutions.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4127 , #3999

2021-11-01 15:01 UTC, TPGamesNL requested changes
So I can't read Korean, so with this review I got help from Peter (Discord: Peter_#9686) (thanks again Peter :D)

2021-11-01 15:29 UTC, alphaimetal0903 commented on src/main/resources/lang/korean.lang
> +			enabled: 이전에 비활성화된 모든 스크립트를 성공적으로 활성화하고 구문을 분석했습니다.
I think my translation is correct according to the default language file.

2021-11-01 15:29 UTC, alphaimetal0903 commented on src/main/resources/lang/korean.lang
> +		error: %1$s을(를) 다시 로드하는 동안 %2$s개의 오류를 찾았습니다!
_todo_

2021-11-01 15:31 UTC, alphaimetal0903 commented on src/main/resources/lang/korean.lang
> +			enabled: 이전에 비활성화된 모든 스크립트를 성공적으로 활성화하고 구문을 분석했습니다.
Hmm... it's more natural to not have `'이전에'`.

2021-11-02 13:33 UTC, TPGamesNL approved these changes

2021-11-02 13:43 UTC, merged