fix(sections): reverse current section order
SkriptLang/Skript pull request #4447
Opened 2021-11-26 18:34 UTC by Olyno

### Description

This pull request changes the order of the current section, so it returns always the innermost.

---
**Target Minecraft Versions:** any
**Requirements:** /
**Related Issues:** #4446

2021-11-26 20:39 UTC, TPGamesNL requested changes

2021-11-26 20:39 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
> +		List<TriggerSection> reversedSections = currentSections;
This will reverse the field as well

2021-11-26 20:39 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
> +		List<TriggerSection> reversedSections = currentSections;
Not needed in this method, it won't have effect

2021-11-27 09:37 UTC, TPGamesNL approved these changes
I think it's fine to change this method's behaviour without creating a new one for it, as it is still quite new and intuitively you'd expect it to behave this way anyway, but I would still like a other review on this for this reason

2021-12-01 19:43 UTC, Pikachu920 commented
instead of creating a new reversed list, could we loop over the existing one but in reverse?

2021-12-01 20:11 UTC, Olyno commented
Sure i would like to, but honestly i don't see how

2021-12-01 20:28 UTC, TPGamesNL commented
The same you'd do it for an array, except with size() and get(i)

2021-12-01 20:34 UTC, Pikachu920 commented
Check out section 3.1 at this link https://www.baeldung.com/java-list-iterate-backwards

It's the most performant way because you don't need to allocate a new list or an Iterator

2021-12-04 06:26 UTC, Pikachu920 approved these changes
good stuff!👍👍

2021-12-20 02:43 UTC, merged