Enhance ExprSignText
SkriptLang/Skript pull request #4584
Opened 2022-02-08 16:19 UTC by bilektugrul

### Description
Added support for getting all lines of the sign and some minor code changes.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4579

2022-02-08 16:23 UTC, TheLimeGlass commented
Mentioned incorrect related issue.

2022-02-08 16:26 UTC, bilektugrul commented
> Mentioned incorrect related issue.

Fixed.

2022-02-08 16:30 UTC, TheLimeGlass commented
While you're in this class. The %block% expression should really be %blocks%. It isn't currently because this syntax is an older one. Syntaxes should always support multiple.

Also Skript's coding standard is to use no brackets on single line conditions
```java
if (example.isTrue())
    return;
```
Rather than requiring the brackets.
```java
if (example.isTrue()) {
    return;
}
```
It's not a strict rule as there are a small amount of random usages with the bracket single lines still present, but we need to be cracking down, and you changed some in this pull request.

2022-02-08 16:31 UTC, TheLimeGlass commented
Don't worry about GitHub actions erroring, there is currently an issue with it erroring.

2022-02-09 09:15 UTC, bilektugrul commented
> While you're in this class. The %block% expression should really be %blocks%. It isn't currently because this syntax is an older one. Syntaxes should always support multiple.
> 
> Also Skript's coding standard is to use no brackets on single line conditions
> 
> ```java
> if (example.isTrue())
>     return;
> ```
> 
> Rather than requiring the brackets.
> 
> ```java
> if (example.isTrue()) {
>     return;
> }
> ```
> 
> It's not a strict rule as there are a small amount of random usages with the bracket single lines still present, but we need to be cracking down, and you changed some in this pull request.

Added multiple block support also reverted those minor changes to fit Skript's standarts.

2022-02-09 17:12 UTC, bilektugrul commented
Seperated the new expression from old class as TPGamesNL requested in skUnity.

2022-02-15 22:50 UTC, TheLimeGlass requested changes

2022-02-15 22:50 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprAllSignLines.java
> +		return lines.toArray(new String[0]);
We use String[]::new instead of defining a new array list directly. Three occurrences of this in this pull.

2022-02-15 22:50 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprAllSignLines.java
> +	static boolean hasUpdateBooleanBoolean = true;
We could have a better field name other than hasUpdateBooleanBoolean, like maybe hasForceUpdate.

2022-02-15 22:50 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprAllSignLines.java
> +				try {
This try catch is not required. The boolean already knows the method exists.

2022-02-15 22:50 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprAllSignLines.java
> +		return super.setTime(time, SignChangeEvent.class, blocks);
You're setting the time state to all here, but you're only supporting 0 and 1 aka present and future in the get. You need to only return if it's 0 or 1, or you need to add support for getting the former lines of the sign in the get method.

Example in the get method:
```java
protected String[] get(Event e) {
    //existing code...
    if (getTime() == -1 && isSignChangeEvent) {
        SignChangeEvent event = (SignChangeEvent) e;
        lines.addAll(List.of(((Sign)event.getBlock()).getLines()));
        return lines.toArray(String[]::new);
    }
}
```
```vb
if the former lines contains "[protected]":
    player does not have permission "admin.protected"
    message "&cYou don't have permission to edit this sign."
    cancel event
```

2022-02-15 22:50 UTC, TheLimeGlass commented
Thank you for adding time states, they're over looked by many.

2022-02-16 07:48 UTC, bilektugrul commented
I will look into your reviews when I have time.

2022-02-23 08:42 UTC, closed without merging