🚀 Add age of block expression
SkriptLang/Skript pull request #4594
Opened 2022-02-12 04:38 UTC by AyhamAl-Ali

### Description

This PR adds a new expression `((max[imum]|) age) of %block%` used for ageable blocks such as crops

---
**Target Minecraft Versions:** 1.13+
**Requirements:** Minecraft 1.13+
**Related Issues:** #4534

2022-02-12 14:04 UTC, TPGamesNL requested changes

2022-02-12 14:04 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
> +		BlockData bd = block.getBlockData();
This method isn't there on 1.9, only make the expression register if it (and the interface Ageable, if needed) exist, and add docs accordingly

2022-02-12 14:04 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
> +		return mode == ChangeMode.SET || mode == ChangeMode.RESET ? CollectionUtils.array(Number.class) : null;
Should return null if isMax

2022-02-12 14:04 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
> +		}
```suggestion
		if (mode == ChangeMode.SET && (delta == null || delta[0] == null))
			return;
```

2022-02-12 14:04 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
> +@Description({"Returns the age of a block. 'Age' represents the different growth stages that a crop-like block can go through.",
First sentence should include something about the age or the maximum age

2022-02-15 14:28 UTC, TPGamesNL approved these changes

2022-02-15 14:28 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
> +		return (mode == ChangeMode.SET || mode == ChangeMode.RESET) && !isMax ? CollectionUtils.array(Number.class) : null;
This looks slightly better
```suggestion
		return !isMax && (mode == ChangeMode.SET || mode == ChangeMode.RESET) ? CollectionUtils.array(Number.class) : null;
```

2022-06-30 06:23 UTC, TheLimeGlass approved these changes

2022-06-30 06:23 UTC, merged