⚒️ Fix parser formatting in debug mode
SkriptLang/Skript pull request #4620
Opened 2022-02-21 19:45 UTC by AyhamAl-Ali

### Description

This PR fixes parser output missing a new line when `from` variable is set, this only appears in debug verbosity

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:** None

2022-03-05 05:34 UTC, APickledWalrus approved these changes

2022-04-18 17:29 UTC, TPGamesNL requested changes

2022-04-18 17:29 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/log/LogEntry.java
> +			from = "§7   " + from + "\n";
While the field `from` is annotated as nullable, it doesn't appear to be from anywhere in the implementation. The annotation should therefore be removed, and the condition can be replaced with `!from.isEmpty()`

2022-04-18 17:29 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/log/LogEntry.java
> +			String.format(lineInfoMsg, String.valueOf(node.getLine()), c.getFileName()) + // String.valueOf is needed to replace as a string
```suggestion
			String.format(lineInfoMsg, String.valueOf(node.getLine()), c.getFileName()) + // String.valueOf is to convert the line number (int) to a String
```
IMO this is more clear

2022-06-30 16:29 UTC, TPGamesNL approved these changes

2022-07-11 10:11 UTC, merged