⚒️ Replace color char in debug statements
SkriptLang/Skript pull request #4630
Opened 2022-02-25 17:30 UTC by AyhamAl-Ali

### Description

- Replaces chat color codes in debugging statements instead of stripping them
- Handle unhandled debugging statements for chat color codes

**Before**
![image](https://user-images.githubusercontent.com/20037329/155758587-e2f01cc1-e1fa-40cb-ace9-19c6740ea738.png)
![image](https://user-images.githubusercontent.com/20037329/155760127-163a67cb-c646-48a7-aed5-499c05a49fe2.png)

**After**
![image](https://user-images.githubusercontent.com/20037329/155758513-8abdba79-174f-4fb3-8c47-4ae0f88f80f5.png)
![image](https://user-images.githubusercontent.com/20037329/155760227-8c33ab46-1bb6-4333-95bd-3915e3d26a89.png)

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:**  None

2022-03-05 05:26 UTC, APickledWalrus approved these changes

2022-03-06 13:44 UTC, Moderocky approved these changes

2022-03-06 16:07 UTC, TPGamesNL requested changes

2022-03-06 16:07 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/util/SkriptColor.java
> +		return COLOR_CHAR_PATTERN.matcher(s).replaceAll("&");
```suggestion
		return s.replace('\u00A7', '&');
```
I think it's better to use this form to avoid any possible encoding issues

2022-04-18 17:49 UTC, merged