Add EffPathfind
SkriptLang/Skript pull request #4671
Opened 2022-03-17 04:33 UTC by Pikachu920

### Description
Adds an effect to make an entity start/stop pathfinding to an entity/location

---
**Target Minecraft Versions:** Any
**Requirements:** Paper
**Related Issues:** #2334

2022-04-28 23:45 UTC, Nicofisi approved these changes
Top-tier code, no complaints!

2022-05-06 17:25 UTC, Pikachu920 commented
> Top-tier code, no complaints!

thank you please tell microbook to hire me

2022-06-30 15:08 UTC, TheLimeGlass approved these changes

2022-06-30 15:14 UTC, TPGamesNL approved these changes

2022-06-30 18:12 UTC, AyhamAl-Ali approved these changes

2022-07-12 11:58 UTC, TheLimeGlass requested changes

2022-07-12 11:58 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/effects/EffPathfind.java
> +		Number speed = this.speed != null ? this.speed.getSingle(e) : null;
The Number object can be an int here rather than doing it every loop

2022-07-16 04:47 UTC, TheLimeGlass approved these changes

2022-07-16 04:47 UTC, merged