⚒️ Improve Time class
SkriptLang/Skript pull request #4690
Opened 2022-03-22 22:49 UTC by AyhamAl-Ali

### Description

Little PR to improve Time parsing

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:** None

2022-06-30 14:59 UTC, TheLimeGlass approved these changes

2022-07-15 17:39 UTC, APickledWalrus requested changes
Sorry to nitpick lol

2022-07-15 17:39 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/util/Time.java
> +	private final static Pattern TIME_PATTERN = Pattern.compile("\\d?\\d:\\d\\d", Pattern.CASE_INSENSITIVE);
```suggestion
	private static final Pattern DAY_TIME_PATTERN = Pattern.compile("(\\d?\\d)(:(\\d\\d))? ?(am|pm)", Pattern.CASE_INSENSITIVE);
	private static final Pattern TIME_PATTERN = Pattern.compile("\\d?\\d:\\d\\d", Pattern.CASE_INSENSITIVE);
```

2022-07-15 18:26 UTC, APickledWalrus approved these changes

2022-07-18 12:16 UTC, TheLimeGlass approved these changes

2022-07-18 12:21 UTC, merged