Ench/itemdata tostring
SkriptLang/Skript pull request #4707
Opened 2022-03-27 21:35 UTC by AyhamAl-Ali

### Description

This PR should be merged at least after #4630
Enhance toString of items to include enchantments, lore, fix colors and add quotation marks around the name
**After PR**
![image](https://user-images.githubusercontent.com/20037329/160302002-2a01c777-3161-422d-afa1-6d4ce715d7e5.png)

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:**

2022-03-31 19:55 UTC, AyhamAl-Ali commented
> where can i download skript nightly with it?

You can locate it now in the `checks tab > artifacts` or from this [link](https://github.com/SkriptLang/Skript/suites/5884127035/artifacts/198902889)

2022-03-31 21:08 UTC, pawelkuwa commented
![image](https://user-images.githubusercontent.com/83598982/161149589-7a989ffd-7411-4053-939f-622ee4bd59e8.png)
doesn't give item :(

2022-07-15 17:13 UTC, APickledWalrus commented
> ![image](https://user-images.githubusercontent.com/83598982/161149589-7a989ffd-7411-4053-939f-622ee4bd59e8.png) doesn't give item :(

It's because the ItemType parser does not support parsing to this extent. We can expand the output here, but it won't be useful for parsing the string version of an item type.

2022-07-17 17:49 UTC, pawelkuwa commented
> 

why it won't be usefull? in some scripts i save items into string for store items in yaml but i must use my special function for read and for other people it is terrible

2022-07-17 17:52 UTC, APickledWalrus commented
The issue is you won't be able to parse the string as an item (as you encountered above when you stated that it doesn't give you the item)

Perhaps we could change this in the future, but you should probably use something like skript-yaml which IIRC will serialize items for you (meaning you don't need to store them as strings)

2022-07-17 17:54 UTC, AyhamAl-Ali commented
If you don't want to use the suggestion above you better split its attributes when saving then parse it when needed something like this
 ```yml
itemtype: stone
name: "&aCustom Name"
lore: ["lore 1", "lore 2", "lore 3"]
```
script would be
```v
# set {_itemtype}, {_name} and {_lore} to the yml values
set {_item} to {_itemtype} parsed as itemtype named {_name} with lore {_lore}
```

2022-11-24 04:33 UTC, APickledWalrus requested changes

2022-11-24 04:33 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/ItemType.java
> +		return "" + b;
```suggestion
		return b.toString();
```

2022-11-24 04:33 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +					if (i != enchs.size() - 1)
I would add curly braces here since it's an if/else

2022-11-24 04:33 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +						if (i != lore.size() - 1)
I would add curly braces here since it's an if/else

2022-11-24 04:33 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +		return "" + b;
```suggestion
		return b.toString();
```

2022-11-28 21:22 UTC, TheLimeGlass requested changes
@AyhamAl-Ali conflicts

2023-01-02 12:25 UTC, TheLimeGlass requested changes

2023-01-02 12:25 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +			b.append(Language.getSpaced("enchantments.of"));
```suggestion
			b.append(Language.getSpaced("enchantments.of").toLowerCase(Locale.ENGLISH));
```

2023-01-02 12:25 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +			b.append(Language.getSpaced("enchantments.of"));
Import may be needed

2023-01-02 12:47 UTC, TheLimeGlass commented
I think Aliases#parseItemType should support parsing of this addition, that way parsing will work. I don't think we should completely remove the ability to parse what ItemType returns.

2023-04-22 01:46 UTC, TheLimeGlass approved these changes

2023-04-22 01:46 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/aliases/Aliases.java
> +				EnchantmentType enchantmentType = EnchantmentType.parse("" + enchantment);
```suggestion
				EnchantmentType enchantmentType = EnchantmentType.parse(enchantment);
```

2023-09-18 09:26 UTC, Moderocky approved these changes

2023-12-30 22:18 UTC, sovdeeth approved these changes

2024-05-30 16:38 UTC, APickledWalrus requested changes

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/Aliases.java
> +	private final static Message m_with_lore = new Message("aliases.with lore");
```suggestion
	private static final RegexMessage p_named = new RegexMessage("aliases.named", "(.+) ", " \"(.+)\"", Pattern.CASE_INSENSITIVE);
	private static final RegexMessage p_with_lore = new RegexMessage("aliases.with lore", "(.+) ", " (\".+\")", Pattern.CASE_INSENSITIVE);

	private static final Pattern ENCHANTMENTS_PATTERN = Pattern.compile("\\s*(,|" + Pattern.quote(Language.get("and")) + ")\\s*");
	private static final Pattern MULTIPLE_VALUE_SPLIT_PATTERN = Pattern.compile("(, ?| " + Pattern.quote(Language.get("and")) + " )");

	private static final Message m_named = new Message("aliases.named");
	private static final Message m_with_lore = new Message("aliases.with lore");
```

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/Aliases.java
> +		value = "" + value.trim();
```suggestion
		value = value.trim();
```
These should be removable. IIRC they are leftover from old null analysis

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/Aliases.java
> +			value = "" + matcher.group(matcher.groupCount());
```suggestion
			itemtype.setAmount(Utils.parseInt(matcher.group(1)));
			itemtype.setAll(true);
			value = matcher.group(matcher.groupCount());
		} else if ((matcher = p_of.matcher(value)).matches()) {
			itemtype.setAmount(Utils.parseInt(matcher.group(1)));
			value = matcher.group(matcher.groupCount());
		} else if ((matcher = p_every.matcher(value)).matches()) {
			itemtype.setAll(true);
			value = matcher.group(matcher.groupCount());
```

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/Aliases.java
> +				if (parseType("" + value.substring(0, character), clonedItemtype, false) == null)
```suggestion
				if (parseType(value.substring(0, character), clonedItemtype, false) == null)
```

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/Aliases.java
> +			matcher = p_named.matcher(value.substring(character, hasLore ? lowercase.indexOf(" " + m_with_lore + " ") : lowercase.length()));
what happens if the name contains `with lore`?

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +					if (i != enchantments.size() - 1) {
```suggestion
			int size = enchantments.size();
			for (Entry<Enchantment, Integer> entry : enchantments.entrySet()) {
				if (i != 0) {
					if (i != size - 1) {
```

2024-05-30 16:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/aliases/ItemData.java
> +				builder.append("\"").append(SkriptColor.replaceColorChar(meta.getDisplayName())).append("\"");
I'm not sure we should color this by default. IMO it should be up to the user to color the string.

2024-07-01 23:13 UTC, APickledWalrus commented
This PR also likely needs to account for the fact that some ItemDatas do not represent ItemStacks anymore

2024-12-15 03:29 UTC, sovdeeth commented
Closing due to inactivity

2024-12-15 03:29 UTC, closed without merging