Armor Expression
SkriptLang/Skript pull request #4813
Opened 2022-06-16 15:25 UTC by dkfrede

### Description
I made a expression so instead of you typing all types of armor to create a list of all player's armor, its just an expression called player's armor. I tested it ingame, and it works just fine :)

---
**Target Minecraft Versions:** any
**Requirements:** i guess none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4752

2022-06-16 15:32 UTC, TheBentoBox commented
Couldn't this be made to work for any living entity using [`EntityEquipment`](https://purpurmc.org/javadoc/org/bukkit/inventory/EntityEquipment.html) instead of `PlayerEquipment`?

2022-06-16 16:48 UTC, TheLimeGlass requested changes
It should also support multiple values and use getArray(event), but if you're switching over to a property expression like stated above, then the property expression will help in that regard.

2022-06-16 16:48 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprGetAllArmor.java
> +       return true;
When you always return multiple values like your array list there. The isSingle should be false.

2022-06-16 16:56 UTC, dkfrede commented
> Couldn't this be made to work for any living entity using [`EntityEquipment`](https://purpurmc.org/javadoc/org/bukkit/inventory/EntityEquipment.html) instead of `PlayerEquipment`?

So, i have some problems trying your idea, i can still get the player's armor but not a skeleton's or a mobs.

2022-06-16 16:57 UTC, dkfrede commented
> This should also use `SimplePropertyExpression` instead of `SimpleExpression` Take a look at [this expression](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprAI.java) for example

This should work.

2022-06-16 17:03 UTC, TheLimeGlass commented
The return type doesn't need to be an array and there is a register method in the class to use instead.

2022-06-16 17:05 UTC, dkfrede commented
> The return type doesn't need to be an array and there is a register method in the class to use instead.

If you can suggest the changes, it would be great, im going down to eat :)

2022-06-16 18:00 UTC, dkfrede commented
> The return type doesn't need to be an array and there is a register method in the class to use instead.
Do you know the problem " i can still get the player's armor but not a skeleton's or a mobs."

2022-06-16 18:37 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprGetAllArmor.java
> +       Skript.registerExpression(ExprGetAllArmor.class, ItemStack[].class, ExpressionType.COMBINED, "%livingentities%'s armor");
Please don't mark reviews as resolved if they're not

2022-06-20 14:27 UTC, AyhamAl-Ali requested changes
_Follow up review_

This expression should also support **change methods** (change, acceptChange) I would suggest **SET** & **DELETE** modes

2022-10-19 22:14 UTC, TheLimeGlass commented
@frackz why was this branch deleted? Mistake? Or you used your master for something else?

2023-02-17 05:42 UTC, TheLimeGlass commented
Appears author has deleted and abandoned this pull request. Closing in favor of https://github.com/SkriptLang/Skript/pull/5456

2023-02-17 05:42 UTC, closed without merging