Allow for continue in while loops
SkriptLang/Skript pull request #4839
Opened 2022-06-27 19:52 UTC by kiip1

### Description
Allows for `continue` to be used in while loops. This closes #4810 

---
**Target Minecraft Versions:** All
**Requirements:** None
**Related Issues:**
+ #4810

2022-06-27 21:26 UTC, AyhamAl-Ali commented
Thanks for this nice PR \:D
I think it should probably wait for #4595 so it can benifit from `LoopSection`

2022-06-27 21:34 UTC, kiip1 commented
`LoopSection` surely would be useful when merged, but no need to wait on it as only 3 lines of code will change.

2022-06-27 21:42 UTC, AyhamAl-Ali commented
If that PR is going to take some time after 2.7 then yea no need to wait that long but hopefully they will be merged together.

2022-06-29 15:04 UTC, TheLimeGlass commented
Converted to draft as this pull will need updating when the Structure API gets merged. https://github.com/SkriptLang/Skript/pull/4108

2022-06-30 06:57 UTC, TheLimeGlass requested changes
Looks good, just an update to the error message so users aren't misinformed about while loops aswell.

2022-06-30 06:57 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/effects/EffContinue.java
>  			Skript.error("Continue may only be used in loops");
The error should also reflect while loops.

2022-06-30 12:47 UTC, TheLimeGlass approved these changes

2022-06-30 14:15 UTC, AyhamAl-Ali approved these changes
![LGTM STICKER](https://user-images.githubusercontent.com/20037329/176700136-2f0ed6f5-b546-4672-b867-7632101bf6c0.png)

2022-06-30 14:25 UTC, merged