Fix for Colored String Case
SkriptLang/Skript pull request #4892
Opened 2022-07-10 17:28 UTC by hotpocket184

### Description
This PR fixes an issue when using the string case expression with colored strings.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4602

2022-07-15 16:48 UTC, APickledWalrus requested changes
Does this only work for hex and color tags? We just probably support any sort of tag contained within `<>`

Also, you should update https://github.com/SkriptLang/Skript/blob/master/src/test/skript/tests/syntaxes/expressions/ExprStringCase.sk to test this

2022-07-15 16:48 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprStringCase.java
> +	}
```suggestion
	}

```

2022-07-15 17:19 UTC, AyhamAl-Ali commented
# Proposal
I had an idea about this, probably easier and cleaner here how it goes:

- You make a little parser ([something like this](https://github.com/SkriptLang/Skript/blob/63ab42eb7f36cf4e6bf8dd54220fbfb4fcf0992d/src/main/java/ch/njol/skript/doc/Documentation.java#L175-L219)) to walk each character from last to beginning (important) and find chat colors/tags/hex codes by:
- Read first > and go to next < then regex check the inside of it
- Read & and chacter on its right and do regex heck
- Read # and the 3-6 characters on its right and do regex heck

Then cut them from the text, save it with its first character position (most left character) in a map and move on

Once the text is filtered, to restore it you do this:
- Inverse the map (related to important above)
- Loop the map then insert each block at its position in the filtered text

If you think you can do that and it's easier go ahead otherwise it's just an idea

# Notes
If you wanted to keep your current code, make sure to compile all regex patterns outside the methods and assign them to their own fields

2022-07-29 23:37 UTC, TheLimeGlass commented
There is `ch.njol.skript.util.chat.ChatMessages#stripStyles(String)` for removing the colour formats, it may also be better to put your utility methods inside `ch.njol.skript.util.chat.ChatMessages`

2022-09-30 01:21 UTC, hotpocket184 commented
> There is `ch.njol.skript.util.chat.ChatMessages#stripStyles(String)` for removing the colour formats, it may also be better to put your utility methods inside `ch.njol.skript.util.chat.ChatMessages`

The only problem with the strip styles is that it throws an index out of bounds exception. I will add it to `ch.njol.skript.util.chat.ChatMessages` though, thanks for the suggestion.

2022-11-24 06:10 UTC, APickledWalrus requested changes
I think a test would be good for this

2022-11-24 06:10 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprStringCase.java
> +						strs[i] = strs[i].replaceAll("[&§][0-9a-fk-orx]", "").replaceAll("(<?<=<)(.*?)(?=>)", "");
can use `cStr` instead of `strs[i]` here

2023-09-18 09:32 UTC, closed without merging