⚒️ Fix Time Played NSME
SkriptLang/Skript pull request #4938
Opened 2022-07-22 02:33 UTC by AyhamAl-Ali

### Description

This PR fixes a NoSuchMethodError when using `ExprTimePlayed` on 1.13-1.15 minecraft server because OfflinePlayer class only had that method in 1.16

---
**Target Minecraft Versions:** 1.13-1.15
**Requirements:** None
**Related Issues:** 
- #4929

2022-07-31 04:23 UTC, TheLimeGlass requested changes

2022-07-31 04:23 UTC, TheLimeGlass commented on src/test/skript/tests/regressions/4938-time played.sk
> +	assert {_time} is equal to 0 seconds with "Notch hacked your server and built a dirt house on your server (time: %{_time}%)"
GitHub suggestion caused me to forget the new line, my bad.
```suggestion
	assert {_time} is equal to 0 seconds with "Notch hacked your server and built a dirt house on your server (time: %{_time}%)"

```

2022-07-31 04:23 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
>  		for (OfflinePlayer offlinePlayer : getExpr().getArray(e)) {
I think we're going to start changing to event as majority vote.
```suggestion
	public void change(Event event, @Nullable Object[] delta, ChangeMode mode) {
		if (delta == null)
			return;

		long ticks = ((Timespan) delta[0]).getTicks_i();
		for (OfflinePlayer offlinePlayer : getExpr().getArray(event)) {
```

2022-08-01 21:22 UTC, TheLimeGlass approved these changes

2022-08-15 20:55 UTC, APickledWalrus requested changes
Just some formatting :)

2022-08-15 20:55 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
> +
```suggestion
```

2022-08-15 20:55 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
> +				offlinePlayer.getPlayer().setStatistic(Statistic.PLAY_ONE_MINUTE, (int) ticks); // No NPE due to isOnline check
Should have curly brackets IMO

2022-08-15 20:55 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
> +
```suggestion
```

2022-08-16 10:16 UTC, TPGamesNL requested changes

2022-08-16 10:16 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
> +		return new Timespan(0);
I don't think the expression should return 0 ticks when the player is offline and offline players aren't supported, I think it should return null. The player being offline doesn't mean they've never played, it just means we don't know it.

2022-08-16 10:16 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
>  @Since("2.5")
Can you edit the Since annotation to note that offline players were supported since 2.6?

2022-08-16 19:25 UTC, APickledWalrus approved these changes
Other than TP's comments, LGTM

2022-08-20 17:55 UTC, TPGamesNL approved these changes

2022-09-16 04:12 UTC, merged