Add moon phase expression
SkriptLang/Skript pull request #5061
Opened 2022-08-27 21:38 UTC by UnderscoreTud

### Description
This PR adds an expression to get the current moon phase of a world

---
**Target Minecraft Versions:** 1.16+
**Requirements:** Paper
**Related Issues:** https://github.com/SkriptLang/Skript/issues/746

2022-08-28 03:26 UTC, AyhamAl-Ali requested changes
Nice PR 🎉

2022-08-28 03:26 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +				.requiredPlugins("Paper")
```suggestion
				.requiredPlugins("Paper 1.16+")
```

2022-08-28 03:26 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprMoonPhase.java
> +@RequiredPlugins("Paper")
```suggestion
@RequiredPlugins("Paper 1.16+")
```

2022-08-28 09:53 UTC, AyhamAl-Ali approved these changes

2022-09-16 03:11 UTC, TheLimeGlass approved these changes

2022-09-16 03:14 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprMoonPhase.java
> +	"\tsend \"today's a full moon!\""
```suggestion
		"\tsend \"today's a full moon!\""
```

2022-11-24 03:38 UTC, APickledWalrus requested changes
Minor formatting - fun stuff!!

2022-11-24 03:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +						return toString(moonPhase, 0);
```suggestion
						return moonPhase.name();
```
I think this is preferred? would be consistent with your enum class info pr too

2022-11-24 03:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMoonPhase.java
> +		"\tsend \"today's a full moon!\""
```suggestion
		"\tsend \"Watch for the wolves!\""
```
maybe this is more fun 🤣

2022-11-24 03:38 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMoonPhase.java
> +@Description("The current moon phase of a world")
```suggestion
@Description("The current moon phase of a world.")
```

2022-11-24 05:47 UTC, APickledWalrus approved these changes

2022-11-24 09:27 UTC, TheLimeGlass commented
@UnderscoreTud conflicts

2022-11-24 10:58 UTC, UnderscoreTud commented
> @UnderscoreTud conflicts

alright fixed

2022-11-24 11:00 UTC, TheLimeGlass requested changes

2022-11-24 11:00 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +import ch.njol.skript.util.*;
No wild cards

2022-11-24 11:00 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +import ch.njol.skript.classes.*;
No wild cards

2022-11-24 11:07 UTC, TheLimeGlass approved these changes

2022-11-24 11:08 UTC, merged