add environment expression
SkriptLang/Skript pull request #5070
Opened 2022-08-29 10:16 UTC by UnderscoreTud

### Description
This PR adds a way to get the environment of a world, (get if the world is an overworld, nether or end)

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** don't believe there are any

2022-08-29 11:45 UTC, AyhamAl-Ali requested changes
Nice PR ⚡

2022-08-29 11:45 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +				.description("Represents the type of a world")
Since other types do this as well
```suggestion
				.description("Represents the type of a world.")
```

2022-08-29 11:45 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprEnvironment.java
> +		"\tapply fire resistance to player for 10 minutes"
```suggestion
	"if environment of player's world is nether:",
	"\tapply fire resistance to player for 10 minutes"
```

2022-08-29 11:45 UTC, AyhamAl-Ali commented on src/main/resources/lang/default.lang
> +	normal: overworld
```suggestion
	normal: overworld, the overworld
```

2022-08-29 11:46 UTC, AyhamAl-Ali commented
Related issue:
- #3673

2022-09-02 14:19 UTC, APickledWalrus approved these changes
should be good 👍

2022-09-14 20:40 UTC, TheLimeGlass requested changes
`Missing lang enum constant for 'environments.CUSTOM'`

I also tested for conflicts with world name and biome, no conflicts after adding the `custom` enum to the lang file.

2022-09-14 20:47 UTC, TheLimeGlass requested changes

2022-09-14 20:47 UTC, TheLimeGlass commented on src/main/resources/lang/default.lang
> +
```suggestion
	custom: custom

```

2022-09-16 02:59 UTC, TheLimeGlass commented
You also need to respect the original enum name. Normal is also not in the default.lang.

A test can be added for this. The main world of the test runner is a super flat world, along with the end being enabled.
```
test "world environment":
	assert environment of world "world" is overworld with "main overworld was not ""normal"""
	assert environment of world "world_the_end" is the end with "world_the_end was not ""the end"""
	set {_environment} to environment of world "world"
	assert {_environment} is normal with "environment of world didn't compare with a variable"
```

2022-09-16 03:36 UTC, UnderscoreTud commented
> You also need to respect the original enum name. Normal is also not in the default.lang for the enum environments.normal.
> 
> A test can be added for this. The main world of the test runner is a super flat world, along with the end being enabled. A super flat is defined as normal and not custom, as environment is different from world generation, hence why normal should be an accepted enum.
> ```
> test "world environment":
> 	assert environment of world "world" is normal with "main overworld was not environment ""normal"""
> 	assert environment of world "world_the_end" is the end with "world_the_end was not environment ""the end"""
> 	set {_environment} to environment of world "world"
> 	assert {_environment} is overworld with "environment of world didn't compare with a variable"
> ```

it is there, it's just called "overworld" as it makes more sense

2022-09-16 03:41 UTC, TheLimeGlass commented
> it is there, it's just called "overworld" as it makes more sense
The type `normal` refers to the sky (and a few other details like temperature etc), sure overworld works, but normal is the literal name used for the enum and if someone knows the Environment enum like me, I would instinctively use `normal`.

2022-09-16 17:34 UTC, UnderscoreTud commented
> The type `normal` refers to the sky (and a few other details like temperature etc), sure overworld works, but normal is the literal name used for the enum and if someone knows the Environment enum like me, I would instinctively use `normal`.

Should i replace `overworld` with `normal` or just add it?

2022-09-16 17:43 UTC, TheLimeGlass commented
> > The type `normal` refers to the sky (and a few other details like temperature etc), sure overworld works, but normal is the literal name used for the enum and if someone knows the Environment enum like me, I would instinctively use `normal`.
> 
> Should i replace `overworld` with `normal` or just add it?

Just adding, overworld is fine as an aliases.

2022-09-16 18:59 UTC, TheLimeGlass approved these changes

2022-09-16 19:02 UTC, TheLimeGlass requested changes
Wait a test script should be added. I wrote an example that's tested

2022-09-16 19:30 UTC, UnderscoreTud commented
> Wait a test script should be added. I wrote an example that's tested
oh right, i forgot to add that, ill do it later :grin:

2022-10-21 10:26 UTC, TheLimeGlass approved these changes

2022-10-21 10:31 UTC, merged