Escape colons in ExprParse
SkriptLang/Skript pull request #5071
Opened 2022-08-29 14:39 UTC by Mr-Darth

### Description
Escapes colons in ExprParse patterns.

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:**

2022-08-29 15:05 UTC, AyhamAl-Ali approved these changes

2022-08-29 15:05 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprParse.java
> +		"\t\tgive {var::1::*} to the player"})
```suggestion
@Examples({
	"set {var} to line 1 parsed as number",
	"on chat:",
	"\tset {var::*} to message parsed as \"buying %items% for %money%\"",
	"\tif parse error is set:",
	"\t\tmessage \"%parse error%\"",
	"\telse if {var::*} is set:",
	"\t\tcancel event",
	"\t\tremove {var::2} from the player's balance",
	"\t\tgive {var::1::*} to the player"
})
```

2022-09-14 23:11 UTC, TheLimeGlass requested changes

2022-09-14 23:11 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprParse.java
> +	@SuppressWarnings("NotNullFieldNotInitialized")
Why are you changing this Nullable field to NonNull?

2022-09-14 23:13 UTC, TheLimeGlass commented
Can you change all e to event and p to parser..p could refer to pattern, so let's make it better understandable.

2022-10-06 09:06 UTC, TheLimeGlass approved these changes

2022-10-06 21:20 UTC, APickledWalrus approved these changes

2022-10-06 21:37 UTC, merged