Add lang file updates on version change
SkriptLang/Skript pull request #5072
Opened 2022-08-29 22:28 UTC by APickledWalrus

### Description
This PR enables lang file updates when Skript detects a version change.
There are a few questions where I'm looking for input though:
- Should we allow addons to opt into this feature? Should it only be for Skript? My thought is that addon opt in would only be possible for addons that handle language files the same as Skript (I'm not sure any do tbh)
- Right now, it *always* updates and creates a backup of a lang file if a version change is detected. This is because Skript has no built-in capability of detecting differences in *values* of Config objects, only the actual keys themselves. Should we add a way for Skript to check if the values themselves have changed? It might result in *slightly* longer startup time when the version changes, but it might be better than just assuming it's changed.

---
**Target Minecraft Versions:** Any
**Requirements:** N/A
**Related Issues:** Needs merged before:
- https://github.com/SkriptLang/Skript/pull/4108

2022-08-30 08:07 UTC, AyhamAl-Ali commented
Noice PR ⚡ 

1- I don't know if any addon is using such system yet so IMO we can decide this later if we have get more feedback on it.
2- That's good IMO, a backup is never a bad choice.

However, I would like this to have an option (in config.sk) so that users can choose to toggle auto update lang files in case they want to manually update with their custom lang files

2022-09-05 20:00 UTC, APickledWalrus commented
> However, I would like this to have an option (in config.sk) so that users can choose to toggle auto update lang files in case they want to manually update with their custom lang files

That could be useful, however outdated lang files may result in console errors (as reported for Structure API, see https://discord.com/channels/988998880794402856/1012003185302450206/1013589722586689588 - testing guild).

This is why I opted for backups, as it ensures lang files will be up to date (but also preserves a user's work if they care to update it)

2022-09-08 10:34 UTC, AyhamAl-Ali commented
The choice relies on whether it's preferred to

1- Override the user lang files with the new lang files and force the users to adapt their custom lang files every update manually
2- Force the users to update their lang files (after having a similar error of Structure API) and adapt their changes once in a while (when a lang file changes in some update)

Based on the answer the default value of `auto-update-lang-files` should be set

2022-09-14 20:32 UTC, TheLimeGlass commented
Can this pull request also target the old aliases file? Issue stated here with error https://github.com/SkriptLang/Skript/issues/4861

2022-09-18 01:54 UTC, APickledWalrus commented
> Can this pull request also target the materials.json? Issue(s) stated here with error #4861

See https://github.com/SkriptLang/Skript/pull/5105

2022-09-21 19:59 UTC, APickledWalrus commented
> The choice relies on whether it's preferred to
> 
> 1- Override the user lang files with the new lang files and force the users to adapt their custom lang files every update manually 2- Force the users to update their lang files (after having a similar error of Structure API) and adapt their changes once in a while (when a lang file changes in some update)
> 
> Based on the answer the default value of `auto-update-lang-files` should be set

With the latest commit, it will only create backups if the lang file has been changed.
Unfortunately, I think we do need to force them to update. I don't think it's a good idea to add an opt out here because of the potential for errors (especially because the error message isn't always clear). We provide backups, so it wouldn't be the worse to convert over. We can also mention lang file changes in the update log :D

2022-09-23 15:10 UTC, Moderocky requested changes

2022-09-23 15:10 UTC, Moderocky commented on src/main/java/ch/njol/skript/Skript.java
> +		SkriptAddon a = addon;
This is messy, why is it being done like this?

2022-09-23 15:10 UTC, Moderocky commented on src/main/java/ch/njol/skript/localization/Language.java
> +			in.close();
Can we be using try-with-resources here? Or at least proper handling for this.

2022-09-25 10:09 UTC, Moderocky approved these changes
Good. Maybe when we move on from Java 1.8 we can use try-with-resources.

2022-10-02 16:16 UTC, TPGamesNL requested changes

2022-10-02 16:16 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/config/SectionNode.java
> +	public boolean setValues(final SectionNode other, boolean countValues, final String... excluded) {
Maybe a better param name would be checkValues

2022-10-02 16:16 UTC, TPGamesNL commented on src/main/java/ch/njol/skript/config/SectionNode.java
> +	 * If false, values from the other SectionNode will be copied to this one.
I think this should be phrased differently. The main function of this method is to copy values over, so it should be said that if countValues is true, this is no longer the case. 

However, I'm also uncertain if the method `setValues` should have an argument to do exactly not what the name implies.

2022-10-03 19:00 UTC, TPGamesNL approved these changes

2022-10-03 19:40 UTC, merged