Re-add support for itemtypes in CondIsOfType
SkriptLang/Skript pull request #5073
Opened 2022-08-30 13:04 UTC by Mr-Darth

### Description
Looks like #1597 accidentally removed `itemtypes` support in CondIsOfType. This PR adds it back.

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:**

2022-09-01 13:16 UTC, AyhamAl-Ali approved these changes

2022-09-24 18:13 UTC, TheLimeGlass commented
There is no entitytype to entitydata converter, this will break comparing an entity to an entitytype.

2022-09-24 21:04 UTC, Mr-Darth commented
> There is no entitytype to entitydata converter, this will break past compatability comparing an entity to an entitytype. Why did you remove entitytype?
>
> Not all entitydata match 1:1 with entitytype. EntityData is based off Entity classes, it's designed to be used a literal and return a created entity. Entitytype will be removed in the future as Skript doesn't use Spigot EntityType enum, just not at this current time, so support for it is required.

From the looks of it, `entitytype` was never meant to be supported (and it isn't, only the pattern accepted it). And EntityType is just EntityData with an amount.

2022-11-24 03:32 UTC, APickledWalrus approved these changes
Might be worth looking into the EntityType thing as Lime mentioned

2022-11-24 03:32 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondIsOfType.java
>  							} else if (o2 instanceof ItemType && o1 instanceof Entity) {
I know you didn't add it, but how exactly would an Entity and ItemType be comparable? Is this needed?

2023-01-09 17:31 UTC, TheLimeGlass commented
@Mr-Darth

2023-01-23 07:54 UTC, TheLimeGlass submitted a review, later dismissed
https://github.com/SkriptLang/Skript/pull/5073#issuecomment-1257034687

2024-04-07 13:45 UTC, sovdeeth requested changes
Some tests would be nice

2024-07-16 06:57 UTC, sovdeeth commented
Do you still intend to work on this?

2024-08-16 20:09 UTC, UnderscoreTud approved these changes

2024-08-16 20:11 UTC, sovdeeth approved these changes

2024-08-16 20:11 UTC, sovdeeth commented on src/test/skript/tests/syntaxes/conditions/CondIsOfType.sk
> +    delete last spawned enderpearl
```suggestion
    delete last spawned enderpearl

```

2024-08-16 20:11 UTC, APickledWalrus approved these changes

2024-08-17 21:03 UTC, merged