Update ExprTool.java
SkriptLang/Skript pull request #5095
Opened 2022-09-10 15:36 UTC by TUCAOEVER

Related issue #5094

### Description
Get wrong offhand tool of player when trigger PlayerHeldItem event

---
**Target Minecraft Versions:**  any
**Requirements:**  None
**Related Issues:**  #5094

2022-09-16 01:27 UTC, TheLimeGlass commented
@AyhamAl-Ali Why was the bug label removed? Was it just because the main issue didn't have a label yet?

2022-10-06 21:24 UTC, APickledWalrus requested changes

2022-10-06 21:24 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprTool.java
> +					if (e instanceof PlayerItemHeldEvent && ((PlayerItemHeldEvent) e).getPlayer() == ent && !offHand) {
Offhand check should come first
```suggestion
					if (!offHand && e instanceof PlayerItemHeldEvent && ((PlayerItemHeldEvent) e).getPlayer() == ent) {
```

2022-10-06 21:24 UTC, TUCAOEVER commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2022-10-21 20:56 UTC, APickledWalrus approved these changes

2022-10-22 01:10 UTC, merged