add to to within
SkriptLang/Skript pull request #5107
Opened 2022-09-19 21:57 UTC by TheLimeGlass

Add `to` to within. Follows the SkQuery syntax which can be removed from SkQuery after this. I always use `to` as SkQuery is way older than the within syntax in Skript.

2022-09-19 21:59 UTC, TheLimeGlass commented
Also this whole from, between and within conflicts is very confusing for new people. Like you either have to know from talking to people or reading the source code that from and between is in a line and within is a cuboid.

2022-11-24 03:24 UTC, APickledWalrus requested changes
I'm not sure if `to` makes sense here - I guess it can be discussed though

If we do add `to` for within, I don't see why we shouldn't add it for `between` as well

(Requesting changes as I'd like discussion on this)

2022-11-24 04:33 UTC, TheLimeGlass commented
blocks within the location from player to the location above player's target block

2023-07-12 08:04 UTC, Moderocky approved these changes
I'm a bit concerned this will be confusing to read.

2023-10-26 22:42 UTC, sovdeeth requested changes
`within a to b` doesn't make sense to me. I can't think of or find any examples where `to` is appropriate to use in this situation; I can only think of `within 1 to 2 days` which is a completely different meaning.

Please let me know if there are legitimate uses of this phrasing outside of Skript, because I can't find any.

2023-10-27 21:25 UTC, TheLimeGlass commented
Not getting anywhere

2023-10-27 21:25 UTC, closed without merging