Adding breeding support
SkriptLang/Skript pull request #5116
Opened 2022-09-24 11:36 UTC by Fusezion

### Description

This PR adds the basis of breeding into skript
```applescript
# Event
[on] [entity] breed[ing]

# Expressions
bred child
breeding mother
breeding father
```

Along side this I've taken the liberality of switching any EventValues of `-1, 0, 1` to their corresponding parts `TIME_PAST, TIME_NOW, and TIME_FUTURE` just to keep it in line with skript's current way

![image](https://user-images.githubusercontent.com/81952476/192094178-032fe770-0897-45be-a66d-6ab5f3702d18.png)
*ignore the \<none\> was making sure `event-entity` = child*
`event-entity` acts the same as `bred child`
`event-livingentity` returns the entity who started the breeding
`event-item` returns the itemstack used for breeding

### Note
as for the experience changes I've copied the ones from the PR #4284 

---
**Target Minecraft Versions:**  1.12.2+ (Skript 2.7 will remove this requirement)
**Requirements:**  MC 1.12.2
**Related Issues:**  #5111

2022-09-24 11:51 UTC, Fusezion commented
I'll see about adding the stuff under `breedable` later once I get a chance just burnt out on seeing the same stuff non stop

2022-09-24 18:05 UTC, TheLimeGlass commented
There is already a pull request standardizing all the the event values to be enum.

2022-11-24 03:10 UTC, APickledWalrus requested changes
Nice feature :D

I think ExprBredChild, ExprBreedingFather, and ExprBreedingMother should be combined into one expression (ex: ExprBreedingFamily) (idk a good name lol)

Once that expression is made, I'll do further review - please feel free to re-request my review

2022-11-24 03:10 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> -        EquipmentSlot hand = e.getHand();
If possible, can you revert these unrelated changes?

2022-12-22 12:08 UTC, TheLimeGlass requested changes
Order of methods is `init -> get/getAll -> acceptChange -> change -> setTime -> getTime -> isSingle -> getReturnType -> toString` for SimpleExpression

The usage of event-father and event-mother can be used after Pickle's pull request at https://github.com/SkriptLang/Skript/pull/4963 to distinguish between the many entities that can be involved in this event as there are many conflicts.

2022-12-22 12:08 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprExperience.java
> +		experience = Math.max(0, Math.round(experience));
You can't continue to have this round method. The round method originally existed for the double, which is now an integer from the looks of it. Math.round(integer) doesn't exist, it only does double and floats, so no clue how this is valid code unless it's somehow converting it to a double/float.

2023-04-05 23:12 UTC, closed without merging

2023-04-05 23:13 UTC, Fusezion commented
Whoops , oh well