Resolves EffFireworkLaunch's IAE from out-of-range power number input
SkriptLang/Skript pull request #5173
Opened 2022-10-20 18:14 UTC by DelayedGaming

### Description
This PR simply resolves [EffFireworkLaunch](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffFireworkLaunch.java) throwing IllegalArgumentException caused by optional out-of-range power input.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2022-10-20 19:13 UTC, AyhamAl-Ali requested changes

2022-10-20 19:13 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/effects/EffFireworkLaunch.java
> +		if (power < 0 || power > 127) // Firework's power range limit
Remove this condition and let it just do the calculations below so that if someone provides 127+ it will become 127 same for 0 and minus

2022-10-21 21:16 UTC, APickledWalrus approved these changes

2022-10-24 18:51 UTC, TheLimeGlass approved these changes

2022-10-25 11:09 UTC, AyhamAl-Ali approved these changes

2022-10-26 04:21 UTC, merged