Add node js package and GitHub actions
SkriptLang/Skript pull request #5180
Opened 2022-10-24 21:20 UTC by TheLimeGlass

### Description
We need to fix GitHub actions running on a node.js branch, also add tests for CI. Ali's pull at https://github.com/SkriptLang/Skript/pull/4319 doesn't have this so it shouldn't conflict.

2022-10-26 04:20 UTC, TheLimeGlass commented
It also prevents GitHub actions from stall idling like this, as it has a task to represent it.

2022-11-11 06:37 UTC, AyhamAl-Ali requested changes

2022-11-11 06:37 UTC, AyhamAl-Ali commented on package.json
> +  "version": "1.0.0",
What version would this follow Skript or the website? for the website currently the version is handled [here](https://github.com/SkriptLang/Skript/pull/4319/files#diff-26b330d4ed424c74aa1b75d4ca8936dac30b9c4223f445d39f757c3ec3414453R1)
_In case it doesn't show up from the link_
![image](https://user-images.githubusercontent.com/20037329/201278488-b4f38ebf-c864-486c-a8d9-290857cc9f28.png)

2022-11-11 06:37 UTC, AyhamAl-Ali commented on package.json
> +  "license": "ISC",
Shouldn't this follow the repo license? `GPL-3.0 license`

2022-11-24 02:10 UTC, APickledWalrus approved these changes
I think this should be okay (approval from ayham def needed)

2023-02-16 13:56 UTC, TheLimeGlass commented
Going to rebase this on the documentation repo

2023-02-16 13:56 UTC, closed without merging