Use provided expression's iterator in ExprFilter
SkriptLang/Skript pull request #5199
Opened 2022-11-10 03:55 UTC by Pikachu920

### Description
Update ExprFilter to use the provided expression's iterator rather than creating an ArrayIterator of `getArray`.

---
**Target Minecraft Versions:** Any
**Requirements:** N/A
**Related Issues:** N/A

2022-11-10 10:37 UTC, AyhamAl-Ali requested changes

2022-11-10 10:37 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprFilter.java
>  	public Iterator<?> iterator(Event e) {
While you're here, rename `e` to `event`  :)

2022-11-13 05:50 UTC, AyhamAl-Ali approved these changes

2022-11-16 21:04 UTC, TheLimeGlass requested changes

2022-11-16 21:04 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprFilter.java
> +		}
```suggestion
		if (objIterator == null)
			return Collections.emptyIterator();
```

2022-11-24 01:59 UTC, APickledWalrus approved these changes

2022-11-24 11:30 UTC, TheLimeGlass approved these changes

2022-11-24 13:02 UTC, merged