Update Expression#stream to specify Stream elements should be non-null
SkriptLang/Skript pull request #5200
Opened 2022-11-10 04:09 UTC by Pikachu920

### Description
Updates the typing of Expression#stream to indicate that the returned stream should not contain null values. Also adds a mention of this in the docs. This change will help make the resulting stream less error-prone and faster as consumers won't need to always filter out non-nulls.

---
**Target Minecraft Versions:** Any
**Requirements:** Any
**Related Issues:** None

2022-11-10 04:10 UTC, Pikachu920 commented
I'm not sure if the placement of the `@NotNull` annotation is right. can anyone confirm?

2022-11-16 21:05 UTC, TheLimeGlass requested changes

2022-11-24 01:58 UTC, APickledWalrus approved these changes
LGTM other than formatting suggestion

2022-11-24 01:58 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/Expression.java
>  		Iterator<? extends T> iter = iterator(e);
```suggestion
	default public Stream<@NonNull ? extends  T> stream(Event event) {
		Iterator<? extends T> iter = iterator(event);
```
Mirroring Lime's comment as a suggestion type comment

2023-02-20 19:35 UTC, TheLimeGlass approved these changes

2023-02-20 19:41 UTC, merged