Allow modification of real player cap
SkriptLang/Skript pull request #5227
Opened 2022-11-28 21:38 UTC by kiip1

### Description
In 1.16, Paper added support for setting the real max player count with Bukkit#setMaxPlayers, but Skript didn't reflect this change yet.

---
**Target Minecraft Versions:** 1.16+
**Requirements:** Paper

2022-11-28 22:26 UTC, TheLimeGlass requested changes

2022-11-28 22:26 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
>  public class ExprMaxPlayers extends SimpleExpression<Long> {
This can return an Integer as both ServerListPingEvent and getMaxPlayers returns an Integer.

2022-11-28 22:26 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
> +		else return CollectionUtils.array((long) ((ServerListPingEvent) e).getMaxPlayers());
If and else if need braces. This also reflects Integer change.
```diff
+		if (isReal) {
+			return CollectionUtils.array(Bukkit.getMaxPlayers());
+		} else {
+			return CollectionUtils.array(((ServerListPingEvent) e).getMaxPlayers());
+		}
```

2022-11-28 22:26 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
>  	public void change(Event e, @Nullable Object[] delta, ChangeMode mode) {
event instead of e

2022-12-10 20:14 UTC, APickledWalrus requested changes
Just some formatting - awesome stuff!

2022-12-10 20:14 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
>  				"[the] [(1¦(real|default)|2¦(fake|shown|displayed))] max[imum] (count|amount|number|size) of players");
```suggestion
		Skript.registerExpression(ExprMaxPlayers.class, Integer.class, ExpressionType.PROPERTY,
				"[the] [1:(real|default)|2:(fake|shown|displayed)] max[imum] player[s] [count|amount|number|size]",
				"[the] [1:(real|default)|2:(fake|shown|displayed)] max[imum] (count|amount|number|size) of players"
			);
```
just some pattern cleanup while we're here

2022-12-10 20:14 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
> +			Skript.error("Modifying real max player count is not supported on this server version");
```suggestion
			Skript.error("Modifying the 'real max player count' is only supported on Paper 1.16 and newer");
```
Might be more helpful for users

2022-12-10 20:14 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
> +				if (!isReal) return CollectionUtils.array(Number.class);
```suggestion
				if (!isReal)
					return CollectionUtils.array(Number.class);
```

2022-12-14 05:45 UTC, TheLimeGlass approved these changes

2022-12-26 17:15 UTC, APickledWalrus approved these changes

2022-12-26 17:33 UTC, AyhamAl-Ali approved these changes

2022-12-27 05:05 UTC, merged