Re-add features.sk
SkriptLang/Skript pull request #5245
Opened 2022-12-16 02:43 UTC by TheLimeGlass

### Description
Re-add support for features.sk which was deleted potentially unintentionally. https://github.com/SkriptLang/Skript/pull/1604

---
Related Issues: https://github.com/SkriptLang/Skript/issues/3728

2022-12-17 20:04 UTC, Moderocky approved these changes

2022-12-27 15:19 UTC, APickledWalrus requested changes

2022-12-27 15:19 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/Skript.java
> +	public static <E extends SkriptEvent> SkriptEventInfo<E> registerEvent(String name, Class<E> event, Class<? extends Event>[] events, String... patterns) {
Do we also need to check `Skript.registerStructure`

2022-12-27 15:19 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +	public static void discard() {
should `alteredPatterns` also be cleared?

2022-12-27 15:19 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +					}
```suggestion
					try (InputStream in = zip.getInputStream(entry)) {
						FileUtils.save(in, saveTo);
					}
```
Should work

2022-12-27 15:19 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +				zip = new ZipFile(file);
Can also probably use try-with-resources here

2022-12-27 15:19 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +				for (Node node : new IteratorIterable<Node>(section.iterator())) {
```suggestion
				for (Node node : section) {		
```

2023-07-11 17:11 UTC, AyhamAl-Ali approved these changes

2023-08-28 06:28 UTC, sovdeeth approved these changes
Brilliant, this seems extremely useful, sad it got disabled.
I like the clear-er description changes, too.

2024-05-31 16:27 UTC, APickledWalrus requested changes

2024-05-31 16:27 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +	public static Pair<Boolean, String[]> contains(String className, String... patterns) {
Is there a reason for using a pair here? The second value doesn't seem to be used.

2024-05-31 16:27 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +				return new Pair<Boolean, String[]>(false, patterns);
Is it possible that more than one pattern could be altered (for the same syntax)? This terminates after the first success.

2024-05-31 16:27 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +				}
We could probably avoid this duplication by setting `loaded` later and calling this method again after the file is created (assuming no exception occurred).

2024-05-31 16:27 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/FeatureConfig.java
> +						"After re-add any nodes you've changed.");
```suggestion
						"After the updated file is created, re-add your changes.");
```

2024-12-15 03:28 UTC, sovdeeth commented
Closing due to inactivity

2024-12-15 03:28 UTC, closed without merging