Improve book edit event `event values`
SkriptLang/Skript pull request #5282
Opened 2022-12-27 09:55 UTC by APickledWalrus

### Description
Improves the event values and properly supports PAST/FUTURE

---
**Target Minecraft Versions:** Any
**Requirements:** N/A
**Related Issues:** None?

2022-12-27 10:51 UTC, Moderocky approved these changes

2022-12-27 15:20 UTC, AyhamAl-Ali requested changes

2022-12-27 15:20 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				ItemStack book = new ItemStack(Material.WRITABLE_BOOK);
Maybe we can make this a field so it only runs once?

2022-12-27 15:23 UTC, AyhamAl-Ali approved these changes

2022-12-28 07:24 UTC, TheLimeGlass approved these changes

2022-12-28 07:38 UTC, merged