Support Worlds into ExprName.java
SkriptLang/Skript pull request #5290
Opened 2022-12-28 19:43 UTC by DelayedGaming

### Description
***This PR is a replacement PR for https://github.com/SkriptLang/Skript/pull/5259.***

*Forwarded from above stated PR*
This PR adds World support to ExprName.java.

Before PR:
![image](https://user-images.githubusercontent.com/72163224/209167286-516a325e-848a-4969-88ae-5d5264711513.png)

After PR:
![imageA](https://user-images.githubusercontent.com/72163224/209168055-e27c6c0f-f920-4360-b45e-d4a2e1bea39c.png)

Requested changes stated from old PR has been carried over to this PR.
---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2022-12-28 19:47 UTC, AyhamAl-Ali requested changes

2022-12-28 19:47 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprName.java
> +	"	set the player's tab list name to \"&lt;green&gt;%player's name%\"",
```suggestion
	"\tplayer has permission \"name.red\"",
	"\tset the player's display name to \"&lt;red&gt;[admin] &lt;gold&gt;%name of player%\"",
	"\tset the player's tab list name to \"&lt;green&gt;%player's name%\"",
```

2022-12-28 19:47 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprName.java
> +@Since("before 2.1, 2.2-dev20 (inventory name), 2.4 (non-living entity support, changeable inventory name), INSERT VERSION (worlds support)")
```suggestion
@Since("before 2.1, 2.2-dev20 (inventory name), 2.4 (non-living entity, changeable inventory name), INSERT VERSION (worlds)")
```

2022-12-28 19:50 UTC, kiip1 requested changes

2022-12-28 19:50 UTC, kiip1 commented on src/main/java/ch/njol/skript/expressions/ExprName.java
> +	"Represents the Minecraft account, display or tab list name of a player, or the custom name of an item, entity, block, inventory, or gamerule.",
```suggestion
	"Represents the Minecraft account, display or tab list name of a player, or the custom name of an item, entity, block, inventory, gamerule or world.",
```

2022-12-28 19:50 UTC, kiip1 commented on src/main/java/ch/njol/skript/expressions/ExprName.java
> +	"\t</li>",
Like this but for world.

2022-12-28 20:20 UTC, kiip1 approved these changes

2022-12-29 13:50 UTC, AyhamAl-Ali approved these changes

2022-12-30 07:29 UTC, TheLimeGlass approved these changes

2023-01-02 13:28 UTC, merged