SimpleEntityData - add Enemy entity
SkriptLang/Skript pull request #5310
Opened 2023-01-02 17:29 UTC by ShaneBeee

### Description
This PR aims to add the Enemy Entity. 
This is an interface of entities that represents monsters and other entities which we normally consider monsters but aren't actually monsters, ie: Phantom, Slimes, Ghasts
See [**BUKKIT**](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/d352d96500fbd215d06f4561f374faabb1c0b1fd) for more details

---
**Target Minecraft Versions:** 1.19.3+
**Requirements:** none
**Related Issues:** none

2023-01-02 17:51 UTC, TheLimeGlass approved these changes
This will make
```vb
if player is an enemy
```
a valid syntax even though it'll be false.

2023-01-02 17:54 UTC, ShaneBeee commented
> This will make
> 
> ```vbnet
> if player is an enemy
> ```
> 
> a valid syntax even though it'll be false. Would be misleading in a damage event.

two things:
1) how so? no where in Minecraft is anything referred to as an "enemy", so that would strictly be a mindset of the Skript user. That said, the Skript user could misinterpret 100s of things in Skript, and they do every day.

2) maybeeeee.... `enemy entity` instead? Or any other suggestions?

2023-01-09 17:29 UTC, TheLimeGlass requested changes

2023-01-09 17:29 UTC, TheLimeGlass commented on src/main/resources/lang/default.lang
> +		name: enem¦y¦ies
```suggestion
		name: enem¦y¦ies @an
```

2023-01-10 12:40 UTC, AyhamAl-Ali approved these changes

2023-01-11 21:47 UTC, TheLimeGlass approved these changes

2023-01-11 22:05 UTC, merged