BukkitEventValues - current/past event-block both return the same for BlockSpreadEvent
SkriptLang/Skript pull request #5343
Opened 2023-01-12 19:14 UTC by ShaneBeee

### Description
This PR aims to fix an issue with event-values for BlockSpreadEvent (`on spread`)
both past/current event-block both returned the same block.
With this fix, the past event-block will be the old block, and event-block will be the new block.

---
**Target Minecraft Versions:** none
**Requirements:** none
**Related Issues:** none

2023-01-12 20:04 UTC, AyhamAl-Ali approved these changes

2023-01-13 05:24 UTC, TheLimeGlass requested changes
You still have the BlockSpreadEvent import and no reference to it.

2023-01-13 17:42 UTC, ShaneBeee commented
> You still have the BlockSpreadEvent import and no reference to it.

fixed :)

2023-01-13 23:03 UTC, TheLimeGlass approved these changes

2023-01-13 23:07 UTC, merged