Fix assertion effect throwing errors when verbose is in debug
SkriptLang/Skript pull request #5349
Opened 2023-01-14 07:58 UTC by TheLimeGlass

### Description
Fixes EffAssert throwing errors when the event and/or the condition is null when the verbose is set to debug.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5323

2023-01-14 18:11 UTC, Pikachu920 requested changes

2023-01-14 18:11 UTC, Pikachu920 commented on src/main/java/ch/njol/skript/tests/runner/EffAssert.java
> +		if (event == null || condition == null)
shouldn't this only be if condition is null? it is valid to pass a null event to the to string of a condition

2023-01-25 17:50 UTC, AyhamAl-Ali approved these changes

2023-01-26 04:59 UTC, APickledWalrus approved these changes

2023-01-26 21:50 UTC, Pikachu920 approved these changes

2023-01-26 22:02 UTC, merged