Add support for getting and modifying ItemType inventories
SkriptLang/Skript pull request #5366
Opened 2023-01-19 20:23 UTC by Pikachu920

### Description
This PR adds support for getting the inventory from an ItemType whose BlockStateMeta implements Container (e.g. shulkers, chests, etc). It also supports modifying the inventory via a proxy which applies any changes to the inventory to the ItemType. The proxy solution is not ideal, but it's the best solution I could find. If you are aware of a better alternative, please let me know!

---
**Target Minecraft Versions:** any
**Requirements:** N/A
**Related Issues:**  kinda sorta #2336

2023-02-04 03:48 UTC, TheLimeGlass requested changes

2023-02-04 03:48 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprInventory.java
> +				if (meta instanceof BlockStateMeta) {
could be a continue instead to reduce arrow code and improve readability.

2023-02-04 03:48 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprInventory.java
> +					if (state instanceof Container) {
could be a continue instead to reduce arrow code and improve readability.

2023-06-28 10:12 UTC, Moderocky approved these changes

2023-07-31 05:05 UTC, TheLimeGlass commented
@Pikachu920 conflicts

2023-12-20 06:21 UTC, merged