Add method exists condition for testing
SkriptLang/Skript pull request #5370
Opened 2023-01-20 00:29 UTC by Pikachu920

### Description
Adds a method exists condition to be used with test cases. This can be used as an alternative to the typical minecraft version checking pattern tests currently use.

---
**Target Minecraft Versions:** Any
**Requirements:**: Any
**Related Issues:** N/A

2023-01-20 00:37 UTC, TheLimeGlass commented
Shouldn't it be included in the test event? What if we want to make a test run for a Paper exclusive syntax? This will just error each time.

2023-01-20 00:39 UTC, Pikachu920 commented
> Shouldn't it be included in the test event? What if we want to make a test run for a Paper exclusive syntax? This will just error each time. Or have another structure or section to parse only if the method exists?

it should work in the test event - Pickle said that the test event supports using any condition (this makes sense because `CondMinecraftVersion` is in the same package). The reason I have a test for it is just to make sure it's working as intended. It's not meant to demo how you would actually use it in a test event (but I can see how that would be confusing lol).

2023-01-20 00:40 UTC, AyhamAl-Ali requested changes
Amazing PR ⚡

2023-01-20 00:40 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/tests/runner/CondMethodExists.java
> +		Skript.registerCondition(CondMethodExists.class, "method[s] %strings% [(1¦don't|1¦doesn't)] exist[s]");
```suggestion
		Skript.registerCondition(CondMethodExists.class, "method[s] %strings% [dont:do(esn't|n't)] exist[s]");
```
and `parseResult.hasTag("dont")`

2023-01-20 00:41 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/tests/runner/CondMethodExists.java
> +		Skript.registerCondition(CondMethodExists.class, "method[s] %strings% [(1¦don't|1¦doesn't)] exist[s]");
the `'t` can probably be after the grouping as well

2023-01-20 00:42 UTC, TheLimeGlass commented
You can place regex in the actual Skript syntax pattern `<your regex here>` instead of %string% and defining the field pattern.

2023-01-20 00:43 UTC, Pikachu920 commented
> You can place regex in the actual Skript syntax pattern `<your regex here>` instead of %string% and defining the field pattern.

hmmm... I think I would prefer to keep it this way as otherwise I'll have to do manual parsing for multiple strings. what do you think?

2023-01-20 00:45 UTC, Pikachu920 commented
Needs support for primitive params

2023-01-20 00:45 UTC, TheLimeGlass commented
> > You can place regex in the actual Skript syntax pattern `<your regex here>` instead of %string% and defining the field pattern.
> 
> hmmm... I think I would prefer to keep it this way as otherwise I'll have to do manual parsing for multiple strings. what do you think?

It shouldn't support multiple strings. You should make a separate test structure if that's the case. Typically if one method doesn't exist that insists that the functionality Skript is testing for is not present.

2023-01-20 00:48 UTC, Pikachu920 commented
> > > You can place regex in the actual Skript syntax pattern `<your regex here>` instead of %string% and defining the field pattern.
> > 
> > 
> > hmmm... I think I would prefer to keep it this way as otherwise I'll have to do manual parsing for multiple strings. what do you think?
> 
> It shouldn't support multiple strings. You should make a separate test structure if that's the case. Typically if one method doesn't exist that insists that the functionality Skript is testing for is not present.

I agree that typically it's only one, but could you explain why it shouldn't support multiple strings please?

2023-01-20 00:56 UTC, TheLimeGlass commented
> 
> I agree that typically it's only one, but could you explain why it shouldn't support multiple strings please?

I just did. A test shouldn't be taking two possible missing methods, it should be defined in a separate test structure.

2023-01-20 01:31 UTC, AyhamAl-Ali approved these changes
Approved so far. Will do another review after primitive params and arrays are supported ⚡

2023-01-20 01:31 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/tests/runner/CondMethodExists.java
> +	@Override
```suggestion
	@Override
	@SuppressWarnings("unchecked")
```

2023-01-23 20:05 UTC, kiip1 reviewed
Looks good, noticed one small thing.

2023-02-04 03:50 UTC, TheLimeGlass approved these changes

2023-02-04 03:58 UTC, merged