Turns CondIsWithinLocation into CondIsWithin
SkriptLang/Skript pull request #5371
Opened 2023-01-20 06:06 UTC by sovdeeth

### Description

Modifies CondIsWithinLocation to support checking if a location is within an entity's hitbox, a block's collision block (1.17+), a chunk, or a world.
Also removes CondIsInWorld in favor of the new syntax in CondIsWithin

---
**Target Minecraft Versions:** any 
**Requirements:** 1.17+ for within blocks, any otherwise 
**Related Issues:**

2023-01-20 13:06 UTC, UnderscoreTud requested changes

2023-01-20 13:48 UTC, AyhamAl-Ali requested changes
Very nice PR ⚡ Well done

2023-01-20 13:48 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/conditions/CondIsWithin.java
> +@RequiredPlugins("1.17 or newer (for within block)")
```suggestion
@RequiredPlugins("MC 1.17+ (within block)")
```

2023-01-20 13:48 UTC, AyhamAl-Ali commented on src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
> +	delete random entity of {_pig}
```suggestion
	delete random entity of {_pig}
	
```

2023-01-20 14:15 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondIsWithin.java
> +import ch.njol.skript.doc.*;
Oh my god intellij i set the limit to like 50 imports before stars should be used
I'm going to murder something

2023-01-20 19:42 UTC, AyhamAl-Ali approved these changes
Code wise looks clean, I haven't tested it tho hopefully it works 😄

2023-02-27 07:29 UTC, UnderscoreTud approved these changes

2023-02-27 07:29 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/conditions/CondIsWithin.java
> +			area = (Expression<Object>) exprs[1];
```suggestion
			area = exprs[1];
```

2023-02-27 19:07 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondIsWithin.java
> +			area = (Expression<Object>) exprs[1];
Oh good catch, I'll fix shortly :)

2023-02-28 07:19 UTC, TheLimeGlass requested changes

2023-02-28 07:19 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/conditions/CondIsWithin.java
> +			"%locations% (isn't|is not|aren't|are not) (within|in[side [of]]) %" + validTypes + "%");
```suggestion
				"%locations% (is|are) within %location% and %location%",
				"%locations% (isn't|is not|aren't|are not) within %location% and %location%",
				"%locations% (is|are) (within|in[side [of]]) %" + validTypes + "%",
				"%locations% (isn't|is not|aren't|are not) (within|in[side [of]]) %" + validTypes + "%"
		);
```

2023-03-08 07:54 UTC, TheLimeGlass approved these changes

2023-03-08 08:15 UTC, merged