add event value for BlockSpreadEvent.getSource();
SkriptLang/Skript pull request #5377
Opened 2023-01-20 21:28 UTC by GodModed

### Description
Added a way to get the source block in BlockSpreadEvent

---
**Target Minecraft Versions:** any
**Requirements:** No requirements
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5346

2023-01-20 22:39 UTC, GodModed commented
fixed

2023-01-20 22:59 UTC, APickledWalrus requested changes

2023-01-20 22:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +import org.bukkit.event.block.BlockSpreadEvent;
```suggestion
```
This can be removed

2023-01-20 22:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprSourceBlock.java
> +import ch.njol.skript.doc.*;
we avoid * imports

2023-01-20 22:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprSourceBlock.java
> +@Examples({
example is 🔥

2023-01-20 22:59 UTC, GodModed commented on src/main/java/ch/njol/skript/expressions/ExprSourceBlock.java
> +@Examples({
fr fr

2023-01-20 23:03 UTC, APickledWalrus approved these changes

2023-01-20 23:04 UTC, APickledWalrus approved these changes

2023-01-21 01:17 UTC, TheLimeGlass approved these changes

2023-01-21 01:18 UTC, merged