Automatically generate and push docs for nightly editions
SkriptLang/Skript pull request #5383
Opened 2023-01-21 00:27 UTC by Pikachu920

### Description
This PR adds a CI job that automatically generates and pushes nightly docs to https://docs.skriptlang.org/nightly/docs.html for any commits to the `master` or `dev/*` branches. Before merging, please reach out as we will need to add the deploy key to the SkriptLang/Skript actions secrets or the job will not work. I am also planning on adding a similar thing upon publish of a release.

---
**Target Minecraft Versions:** Any
**Requirements:** Any
**Related Issues:** Any

2023-01-21 12:19 UTC, Moderocky approved these changes
The config looks good to me (but you never know if a workflow is going to work until it actually runs haha) let me know if you need me to handle the key / any permissons. :)

2023-02-02 08:55 UTC, AyhamAl-Ali approved these changes

2023-02-02 08:58 UTC, TheLimeGlass requested changes

2023-02-02 08:58 UTC, TheLimeGlass commented on .github/workflows/docs.yml
> +            - 'dev/**'
I don't believe dev/ should be an event trigger. If a dev branch gets a push it'll update to a dev build and not master.

2023-02-02 09:06 UTC, merged