Remove getters from event values
SkriptLang/Skript pull request #5405
Opened 2023-01-27 10:24 UTC by TheLimeGlass

### Description
A rebase of pull request https://github.com/SkriptLang/Skript/pull/5013 the amount of changes was not worth the time dealing with conflicts.

Change Getter to Converter in EventValues.
Getter doesn't allow for Java lambdas, and most Skript classes use Converter directly.
I've also added a registerEventValue method without the time integer, which will default to TIME_NOW. As it's the most used time state.

This will allow for
```java
EventValues.registerEventValue(PlayerEggThrowEvent.class, Egg.class, PlayerEggThrowEvent::getEgg);
EventValues.registerEventValue(PlayerEggThrowEvent.class, Egg.class, PlayerEggThrowEvent::getEgg, EventValues.TIME_NOW);
```

Also code cleaned my main domain the EventValues.
Changed all raw field references to be using the getters that have never been used. Security.

---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5006

2023-01-27 12:08 UTC, AyhamAl-Ali requested changes
Amazing PR 🚀

Just few minor changes

2023-01-27 12:08 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +			public T convert(E e) {
```suggestion
			public T convert(E event) {
```

2023-01-27 12:10 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +	private final Class<? extends T> c;
Can't really have a nice name, and it's only used as the field now, as this pull changes it to the method getters. I'm not a fan of clazz.

2023-01-27 12:11 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		private final Class<T> c;
https://github.com/SkriptLang/Skript/pull/5405#discussion_r1088889218

2023-01-27 12:11 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +	private final Class<? extends T> c;
It wouldn't hurt keeping it, it's just annoying to have it. If there is no good option then keep it

2023-01-27 12:12 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		Converter<E, T> getConverter() {
We only want it private

2023-01-27 12:13 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		Class<E> getEventClass() {
We only want it private

2023-01-27 12:13 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		Class<T> getValueClass() {
We only want it private

2023-02-12 15:11 UTC, kiip1 commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +	private final Class<? extends T> c;
`type` or `returnType` could be a good name

2023-02-13 08:25 UTC, AyhamAl-Ali approved these changes
Looking good ⚡

2023-02-13 08:25 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		throw new IllegalArgumentException("time must be TIME_PAST, TIME_NOW, or TIME_FUTURE");
Shouldn't this print the values of the time states?
```suggestion
		throw new IllegalArgumentException("time must be " + TIME_PAST + ", " + TIME_NOW + ", or " + TIME_FUTURE);
```

2023-09-18 10:09 UTC, Moderocky approved these changes
Nice, will there be any breaking changes or do addons not interact with this?

2023-09-25 11:20 UTC, TheLimeGlass commented
> Nice, will there be any breaking changes or do addons not interact with this?

A getter implements a converter, so getters will still work. It's just getters won't be able to use lambdas, so that's up to the addons to utilize.

2024-03-19 16:52 UTC, sovdeeth approved these changes
Looks good, just some merge conflicts. Let's see if we can't get this in 2.9.

2024-05-08 16:09 UTC, Moderocky requested changes
This PR has some quite serious conflicts in event value expression that I can't fix for you in the web editor, you'll need to do this yourself in Git.

2024-06-06 18:57 UTC, APickledWalrus requested changes

2024-06-06 18:57 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +	private final Map<Class<? extends Event>, Converter<?, ? extends T>> converters = new HashMap<>();
This likely needs to be a ConcurrentHashMap for when parallel-loading is properly supported in the future

2024-06-06 18:57 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +			return converter == null ? null : converter.convert(event);
It shouldn't be null if we're checking containsKey right? Would it ever be the case that a value is null?

2024-06-06 18:57 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +				return entry.getValue() == null ? null : ((Converter<? super E, ? extends T>) entry.getValue()).convert(event);
Same here as above

2024-06-06 18:57 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
> +		converters.put(event.getClass(), null);
Agreed that this would be an improvement

2024-06-06 18:57 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		private final Class<T> c;
Per kiip's comment there, `returnType` would be a suitable name.

2024-06-06 18:57 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		Class<T> getValueClass() {
getReturnType would work better here

2024-11-16 00:06 UTC, sovdeeth commented
Closing due to inactivity

2024-11-16 00:06 UTC, closed without merging