ExprRandomNumber ArithmeticException fix
SkriptLang/Skript pull request #5443
Opened 2023-02-14 19:44 UTC by UnderscoreTud

### Description
This PR fixes an issue with the `random number` expression throwing an `ArithmeticException` when trying to get a random integer between two numbers with the same whole number but a different decimal. For example, `a random integer between 2.1 and 2.3` would result in an exception.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** I don't believe there are any (surprisingly)

2023-02-15 11:56 UTC, AyhamAl-Ali requested changes

2023-02-15 11:56 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
>  	private boolean integer;
Would be better to change `integer` to `isInteger`
```suggestion
	private boolean isInteger;
	private Expression<? extends Number> from, to;
	private final Random random = ThreadLocalRandom.current();
```

2023-02-15 11:56 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
> +	protected  Number[] get(Event e) {
```suggestion
	protected Number[] get(Event event) {
```

2023-02-16 00:42 UTC, TheLimeGlass requested changes

2023-02-16 00:42 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
> +	private Expression<? extends Number> from, to;
```suggestion
	private Expression<Number> from, to;
```

2023-02-20 19:33 UTC, TheLimeGlass approved these changes

2023-04-05 19:28 UTC, AyhamAl-Ali approved these changes

2023-04-05 22:40 UTC, merged