Add wrapper expression type
SkriptLang/Skript pull request #5450
Opened 2023-02-16 10:16 UTC by TheLimeGlass

### Description
Adds ExpressionType.WRAPPER which should be used for expressions that extend WrapperExpression, aswell as making the fields in ExpressionInfo private in favour of the un-used getter methods of that class. This is mainly for order sorting and in the future if we need to utilize expressions by type.

That's all that is the core of this pull request (ExpressionType.class addition and ExpressionInfo.class). The rest is just code standard updates for things touched.

Knowledge base:
- A wrapper expression is like an advanced converter. When converting an expression requires multiple inputs to convert. Example being a location using the direction to get another location or a block.
- The order of the enums in the ExpressionType.class is the order in which they're first grabbed.

The order here is to keep in standard with event values. Similarly here; Skript will grab the wrapper expressions after simple, combined and property. In event values the converter is always last in the order. (Of course pattern match everything should be last here though like it is)

2023-02-16 16:35 UTC, kiip1 approved these changes

2023-02-16 16:35 UTC, kiip1 commented on src/main/java/ch/njol/skript/expressions/base/WrapperExpression.java
>  	public WrapperExpression(final SimpleExpression<? extends T> expr) {
```suggestion
	public WrapperExpression(SimpleExpression<? extends T> expr) {
```

2023-07-12 08:11 UTC, Moderocky approved these changes

2024-04-07 13:56 UTC, Moderocky requested changes
This has conflicts that need fixing

2024-05-31 16:47 UTC, APickledWalrus approved these changes
Looks good. Conflicts need resolved first.

2024-11-16 00:02 UTC, sovdeeth commented
Closing due to inactivity

2024-11-16 00:02 UTC, closed without merging