Add Falling Block Expression
SkriptLang/Skript pull request #5484
Opened 2023-03-02 06:37 UTC by UnderscoreTud

### Description
This PR adds a new expression for getting a falling block entity data using item types, blocks and block datas

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4560

2023-03-08 03:32 UTC, TheLimeGlass commented
Should be using EntityData and the lang file. Not a new expression.

2023-04-18 22:38 UTC, TheLimeGlass requested changes
I think `falling (block(|1¦s)|(2¦)%-itemtype%)` should support the word `of` also can this not be `%-itemtype/blockdata%`?

2023-04-25 14:05 UTC, AyhamAl-Ali requested changes
Nice PR ⚡

2023-04-25 14:05 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/entity/FallingBlockData.java
> +			return data.equals(((FallingBlockData) obj).data);
Can block data checking replace item type checking? if not it shouldn't return if true only if false

2023-04-25 14:05 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/entity/FallingBlockData.java
> +	public String toString(int flags) {
Does it support the newly added feature `data`?

2023-09-21 12:55 UTC, UnderscoreTud commented
Not working on this anymore

2023-09-21 12:55 UTC, closed without merging