Add EventRegister API
SkriptLang/Skript pull request #5552
Opened 2023-03-25 06:32 UTC by APickledWalrus

### Description
As more and more API refactors and rewrites get underway, now is the perfect opportunity to provide expanded API for developers. This API is heavily inspired by the new Script Event API, which I would like to see expand into other places.
Essentially, an EventRegister contains these same methods. The goal is to provide a consistent Event API across Script for developers.

This PR also updates Script to make use of an EventRegister and adds ScriptLoader events (this is to avoid the need for future deprecations + refactorings)

FullChanges:
- Added EventRegister utility class
  - I put it in `api.event` for the package, not sure if somewhere else would be better.
- Added ScriptLoaderEvents
  - Right now it just has the same events as ScriptEvent did. I am allowing these events to be registered in both a global and script-specific context.
- Combined ScriptActiveEvent and ScriptInactiveEvent into ScriptActivityChangeEvent
  - I thought that it might be more useful for developers if they were combined, although I think the javadoc may be too confusing in its current state. Please leave any suggestions of concerns regarding this change.
- Added a ScriptUnloadEvent that is called right before the Script's Structures have unload methods called.

**To avoid later refactorings and unnecessary developer pain, this PR is targeting 2.7.**

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:** N/A

2023-03-25 06:34 UTC, TheLimeGlass commented
2.7?

2023-03-25 07:00 UTC, TheLimeGlass requested changes

2023-03-25 07:00 UTC, TheLimeGlass commented on src/main/java/org/skriptlang/skript/api/event/EventRegister.java
> +				.collect(Collectors.toSet())
```suggestion
					.filter(event -> type.isAssignableFrom(event.getClass()))
					.collect(Collectors.toSet())
```

2023-03-25 15:30 UTC, kiip1 reviewed
What if we allow for `EventRegister`s to define a parent `EventRegister`? This would let `Script`'s event register to define `ScriptLoader`'s event register as parent (= get events will include the parent, so duplicate code can be prevented). This would require `ScriptLoaderEvent` to extend `ScriptEvent` (because of generics).

Example:
```java
// Old
eventRegister.getEvents(ScriptLoaderEvent.ScriptUnloadEvent.class)
		.forEach(eventHandler -> eventHandler.onUnload(parser, script));
script.getEventRegister().getEvents(ScriptLoaderEvent.ScriptUnloadEvent.class)
		.forEach(eventHandler -> eventHandler.onUnload(parser, script));

// New
script.getEventRegister().getEvents(ScriptLoaderEvent.ScriptUnloadEvent.class)
		.forEach(eventHandler -> eventHandler.onUnload(parser, script));
```

Let me know if you have any questions :)

2023-03-25 15:40 UTC, APickledWalrus commented
> What if we allow for `EventRegister`s to define a parent `EventRegister`?

Discussed on Discord a little, but this might be difficult for ScriptEvents as ScriptLoader will eventually get unique events that only apply to it. This class *will* be extendable by developers though if they would have a case for this kind of functionality.

2023-09-18 22:13 UTC, sovdeeth approved these changes

2023-10-05 23:02 UTC, TheLimeGlass requested changes

2023-10-05 23:02 UTC, TheLimeGlass commented on src/main/java/org/skriptlang/skript/util/EventRegister.java
> +	private final Set<E> events = new HashSet<>(5);
Why do we need to predefine the size here? Leave it default?

2024-07-14 22:08 UTC, sovdeeth approved these changes

2024-08-22 08:19 UTC, Moderocky approved these changes

2024-09-15 20:47 UTC, sovdeeth commented
conflicts need resolving!

2024-09-22 17:39 UTC, sovdeeth approved these changes

2024-10-13 02:59 UTC, merged