Move documentation into it's own folder
SkriptLang/Skript pull request #5580
Opened 2023-04-04 11:58 UTC by TheLimeGlass

### Description
Move documentation into it's own folder read more at issue

---
**Related Issues:** https://github.com/SkriptLang/skript-docs/issues/34

2023-04-16 12:10 UTC, AyhamAl-Ali requested changes
As you suggested on skript-docs

2023-04-16 12:10 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/doc/Documentation.java
> +	private static final File DOCS_OUTPUT_DIRECTORY = new File(Skript.getInstance().getDataFolder(), "documentation/docs");
```suggestion
	private static final File DOCS_TEMPLATE_DIRECTORY = new File(Skript.getInstance().getDataFolder(), "documentation/templates");
	private static final File DOCS_OUTPUT_DIRECTORY = new File(Skript.getInstance().getDataFolder(), "documentation/output");
```

2023-04-18 10:48 UTC, AyhamAl-Ali approved these changes

2023-04-29 12:11 UTC, Moderocky approved these changes

2023-05-02 04:58 UTC, TheLimeGlass commented
@Pikachu920 or @AyhamAl-Ali are to merge, as the docs bot on the documentation repository needs to be updated.

2023-05-02 19:06 UTC, APickledWalrus approved these changes

2023-05-02 23:10 UTC, AyhamAl-Ali requested changes

2023-05-02 23:10 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/doc/Documentation.java
> +	private static final File DOCS_OUTPUT_DIRECTORY = new File(Skript.getInstance().getDataFolder(), "documentation/output");
```suggestion
	private static final File DOCS_TEMPLATE_DIRECTORY = new File(Skript.getInstance().getDataFolder(), "docs/templates");
	private static final File DOCS_OUTPUT_DIRECTORY = new File(Skript.getInstance().getDataFolder(), "docs");
```

2023-06-25 08:44 UTC, AyhamAl-Ali approved these changes

2023-09-18 10:39 UTC, merged