Restructure and add support for parsing of a date
SkriptLang/Skript pull request #5582
Opened 2023-04-04 23:46 UTC by TheLimeGlass

### Description
This pull request sets up future development for real time capabilities.

Changes:
- Moved the Date class to a `org.skriptlang.skript.util.date` while keeping the old class under deprecation subject to removal.
- Added parsing capabilities for Date. Skript defines a date format in the config.sk but it's not really user accessible but yet it's in the config.sk. So users can now properly use that configuration node. This is most likely what Njol had in plan for the future.
- Removed `duration` as a user option from TimePeriod as duration should represent real time and not Minecraft time. This will allow for usage of the duration tag in the future.
- Changed the default DateFormat from SHORT to FULL. Javadoc: `Tuesday, April 12, 1952 AD` or `3:30:42pm PST.` Skript should be writing out full statements, this is how Skript has always been. SHORT is still supported in serialization for indefinite due to legacy versions using it, and SHORT isn't getting removed, so we can keep SHORT as the serialization.
- Added class TimeParser which will be used in the future for other types like month, day of the week etc.
- Removed some extra new lines from the config.sk while I was in there updating the time comments.

2023-04-04 23:51 UTC, Pikachu920 commented
could we add some tests for date parsing?

2023-09-18 22:20 UTC, sovdeeth approved these changes

2023-09-18 22:20 UTC, sovdeeth commented on src/main/java/ch/njol/skript/SkriptConfig.java
> +	public static final Option<DateFormat> dateFormat = new Option<>("date format", shortDateFormat, format -> {
did you mean to use `fullDateFormat` here? Seems like the default is still the short one.

2024-04-07 13:40 UTC, sovdeeth commented
Closing due to 10 months of inactivity

2024-04-29 21:12 UTC, TheLimeGlass commented
Closed? There is no changes requested. Needs reviews.

2024-04-30 08:33 UTC, sovdeeth commented on src/main/java/ch/njol/skript/SkriptConfig.java
> +	public static final Option<DateFormat> dateFormat = new Option<>("date format", shortDateFormat, format -> {
@TheLimeGlass

2024-04-30 08:49 UTC, Moderocky requested changes
Date arithmetic tests are failing currently.

2024-06-06 19:56 UTC, APickledWalrus requested changes

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/util/Date.java
>  public class Date implements Comparable<Date>, YggdrasilSerializable {
We might wish to extend the new class here for enhanced compatibility

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/resources/config.sk
> +# They will be logged as [INFORMATION] in this format: '<player>: /<command> <arguments>'
```suggestion
```
this config setting was removed

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
> +						return TimeParser.parseDate(input);
Did you want to restrict this to only `parsed as`? I ask as your example in the description uses `parsed as`.

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/java/org/skriptlang/skript/util/date/Date.java
> +public class Date implements Comparable<Date>, YggdrasilSerializable {
Some docs for the class itself would be good - constructors too

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/java/org/skriptlang/skript/util/date/Date.java
> +	}
this should go at the beginning of the class

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/java/org/skriptlang/skript/util/date/Date.java
> +	}
This seems like it should be done in classinfo parser rather than built into the class

2024-06-06 19:56 UTC, APickledWalrus commented on src/main/java/org/skriptlang/skript/util/date/TimeParser.java
> + * Future implementation will be added to this class in a 'real time' pull request enhancement.
Additional docs about the class itself would be good

2024-11-16 00:03 UTC, sovdeeth commented
Closing due to inactivity

2024-11-16 00:03 UTC, closed without merging