New Expression: Attached Block at Arrow
SkriptLang/Skript pull request #5589
Opened 2023-04-08 16:57 UTC by DelayedGaming

### Description
This PR adds a new expression which [gets the attached block of arrow(s)](https://jd.papermc.io/paper/1.19/org/bukkit/entity/AbstractArrow.html#getAttachedBlock()) to Skript!

---
**Target Minecraft Versions:** any
**Requirements:** -
**Related Issues:** -

2023-04-08 17:01 UTC, sovdeeth commented
Is there a reason this isn't a SimplePropertyExpression?
And I'd suggest adding `hit block` as well as ``attached block``

2023-04-08 17:05 UTC, DelayedGaming commented
> Is there a reason this isn't a SimplePropertyExpression?

Then I wouldn't be able to allow usage of `at` keyword here `attached block *at* last shot arrow`

2023-04-08 17:08 UTC, sovdeeth commented
> > Is there a reason this isn't a SimplePropertyExpression?
> 
> Then I wouldn't be able to allow usage of `at` keyword here `attached block *at* last shot arrow`

I don't think that syntax is worth it. Personally, it doesn't even make much grammatical sense to me.
If it's the attached block at the arrow, what is it attached to? "attached" becomes a property of the block, rather than a relation between the block and the arrow.
I'd suggest just using the SimplePropertyExpression syntaxes, but I'm not sure if that's the majority opinion.

2023-04-08 17:25 UTC, AyhamAl-Ali requested changes
Reviewing from the phone isn't easy but nice PR ⚡️

2023-04-08 17:25 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
> +@Name("Attached Block")
```suggestion
@Name("Arrow Attached Block")
```

2023-04-08 17:25 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
> +			"%projectiles%'s (attached|hit) block",
```suggestion
			"%projectiles%'[s] (attached|hit) block",
```

2023-04-08 17:25 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
> +		return false;
```suggestion
		return projectiles.isSingle();
```

2023-04-08 17:29 UTC, DelayedGaming commented
@AyhamAl-Ali Discard your requested change? The expression's base class has been converted to SimplePropertyExpression.

2023-04-08 17:40 UTC, sovdeeth commented
> @AyhamAl-Ali Discard your requested changes? The expression's base class has been converted to SimplePropertyExpression. Although this kills multi-arrow projectile support in one line.

Just make the type plural.

2023-04-08 18:35 UTC, AyhamAl-Ali requested changes

2023-04-08 18:35 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
> +		register(ExprAttachedBlock.class, Block.class, "(attached|hit) block", "projectile");
This way you can have multiple projectiles support
```suggestion
		register(ExprAttachedBlock.class, Block.class, "(attached|hit) block", "projectiles");
```

2023-04-08 18:35 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
> +		}
```suggestion
		if (HAS_ABSTRACT_ARROW && projectile instanceof AbstractArrow) {
			return ((AbstractArrow) projectile).getAttachedBlock();
		} else if (projectile instanceof Arrow) {
			return ((Arrow) projectile).getAttachedBlock();
		}
```

2023-04-10 20:44 UTC, AyhamAl-Ali requested changes

2023-04-10 20:44 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
> +	private static final boolean hasAbstractArrow = Skript.classExists("org.bukkit.entity.AbstractArrow");
Revert the case change :\
It should be `HAS_ABSTRACT_METHOD` because it's static final

2023-04-11 07:37 UTC, AyhamAl-Ali approved these changes

2023-08-02 09:02 UTC, TheLimeGlass approved these changes

2023-08-02 09:07 UTC, merged