New Expression: Free / Max / Total Memory
SkriptLang/Skript pull request #5636
Opened 2023-04-24 17:26 UTC by DelayedGaming

### Description
This PR adds an expression to get the free, max, or total memory of the server to Skript!

---
**Target Minecraft Versions:** any
**Requirements:** -
**Related Issues:** #5628

2023-04-24 18:01 UTC, UnderscoreTud requested changes

2023-04-24 18:01 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +		return (type == Type.FREE ? "free" : type == Type.MAXIMUM ? "maximum" : "total") + " memory";
```suggestion
		return type.name().toLowercase(Locale.ENGLISH) + " memory";
```

2023-04-24 20:18 UTC, DelayedGaming commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +	protected @Nullable Number[] get(Event event) {
Removed `@Nullable` annotation as not possible of returning an empty array in this expression.

2023-04-24 20:26 UTC, DelayedGaming commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +		return CollectionUtils.array(memory.longValue() * 1.024e-6);
Awaiting results from a pending debation in skUnity's SkriptLang channel.

2023-04-25 06:18 UTC, DelayedGaming commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +		return CollectionUtils.array(memory.longValue() * 1.024e-6);
Using 1E-6 in a constant field.

2023-04-25 07:35 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +		Skript.registerExpression(ExprMemory.class, Double.class, ExpressionType.SIMPLE, "[the] (:free|:max[imum]|total) (memory|ram)");
```suggestion
		Skript.registerExpression(ExprMemory.class, Double.class, ExpressionType.SIMPLE, "[the] [server] (:free|:max[imum]|total) (memory|ram)");
```

2023-04-25 07:39 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +	private enum Type {
Let's move enum above the field declaration L54

2023-06-25 08:43 UTC, AyhamAl-Ali approved these changes

2023-08-29 07:57 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprMemory.java
> +		Skript.registerExpression(ExprMemory.class, Double.class, ExpressionType.SIMPLE, "[the] [server] (:free|:max[imum]|total) (memory|ram)");
If the user wrote `maximum` the tag would be `maximum` not `max`
```suggestion
		Skript.registerExpression(ExprMemory.class, Double.class, ExpressionType.SIMPLE, "[the] [server] (:free|max:max[imum]|total) (memory|ram)");
```

2023-08-29 08:19 UTC, merged