Get SQL databases working again
SkriptLang/Skript pull request #5646
Opened 2023-04-26 12:24 UTC by TheLimeGlass

### Description
- Adds H2 as a configurable database. Will probably make default eventually or maybe in this pull request?
- Removes SQLibrary and adds https://github.com/brettwooldridge/HikariCP as the main SQL wrapper.
- Revamped API for better registration and handling of JDBC (SQL) Java drivers
- Added a `commit changes` option which is essentially how Skript used to operate. Changed the JDBC standard to auto commit after every edit. This is standard and better for performance. Skript didn't for some reason. I speculate it was to allow MySQL to sync with other servers, so either way it's an option now.

### Perks
- Better configuration options with HikariCP.
- Way better performance with HikariCP.
- Easier implementation and not relying on a small project like SQLibary.
- Thread pooling potential with HikariCP.
- This new API design allows for quite literally any SQL implementation database.

### TODO
- [ ] Test MySQL and SQLite. Only tested H2 so far.
- [ ] Document all the possible options for databases or have an annotation documentation system.
- [ ] Write up and API tutorial for registering custom storage types.
- [ ] Maybe add MongoDB support https://github.com/SkriptLang/Skript/issues/1787
- [ ] Engineer a better API for matching the getReplaceQuery method with the table attributes, maybe a BiFunction similar to get() method.

Should we just kill SQLite support? It's not like anyone is using it right now, it doesn't even work currently.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/3948

2023-04-28 16:00 UTC, APickledWalrus requested changes
With a quick initial review of the current progress, these changes look excellent. Fantastic work! I would definitely like a review from others too as I am not the most familiar with SQL/the libraries being used

2023-04-28 17:10 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/variables/SerializedVariable.java
> +	private final String name;
SerializedVariable should only have been used internally. I enforced this to be using the methods as it's now going to be accessable via registering a custom storage with the API.

2023-04-28 17:12 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/variables/SQLiteStorage.java
> +			file = file + ".db"; // required by SQLibrary
It's required by SQLite not SQLibrary, should update that comment. It was an existing broad statement.

2023-05-05 04:24 UTC, xartuu commented
Wow, am I dreaming? Awesome that someone is taking on the SQL problem!

2023-06-28 10:29 UTC, Moderocky reviewed
The code looks fine, but I know very little about SQL so I don't feel I'm the right person to be reviewing this.

2023-10-28 09:53 UTC, TheLimeGlass commented
Not working on this anymore

2024-03-26 16:05 UTC, xartuu commented
Hello, do you have an implementation date already planned?

2024-03-26 16:40 UTC, Moderocky commented
> Hello, do you have an implementation date already planned?

It needs people to review it first.

2024-03-26 17:25 UTC, Lennord commented
Good evening, I tested the latest build of your new SQL and I have these errors (below), when I activate auto-commit + put the minotor for around 1 seconds, I tried to leave it by default but i have the same errors.

Link File Log and view Error: [latest.log](https://github.com/SkriptLang/Skript/files/14762309/latest.log)

2024-05-13 22:46 UTC, TheLimeGlass commented
- Swapped method names load_i and load (The internal method was not load_i when it should have been)
- Potentially fixes monitor changes, needs testing on each database type that uses SQL.
- Changed the get method to be a Function rather than BiFunction and made it have a boolean if it's a test operation and also return the rowid for monitor changes which is required for MySQL and Jdbc database that wants monitor changes.
- Added loadJdbcConfiguration(SectionNode section) method so Jdbc extended databases can have their own custom configuration in the config.sk
- Fixed an issue where if the monitor changes queue rowid was not being set. This was due to monitor changes being enabled requiring the the auto commit to be set to false, so it now ensures commits for the rowid setting are set in the prepared statement.
- Changed the 'cannot load variables fast enough' error to not error on first load, as the first load will be more resource heavy. Long time coming TODO comment.
- Monitor changes now only work when a rowid has been returned when loading.

Test jar available when checks are complete at https://github.com/SkriptLang/Skript/actions/runs/9070821309

2024-08-02 06:28 UTC, Prorickey commented
What's being waited on to merge this?

2024-08-02 11:12 UTC, EquipableMC commented
> What's being waited on to merge this?

There has to be a lot of testing done before this can be merged, considering this is a big change, it will most likely come in 2.10.

2024-09-09 10:27 UTC, Hundred-Killer commented
If they fix it, I'll be happy.

2024-09-20 15:28 UTC, TheLimeGlass commented on src/main/resources/plugin.yml
> +libraries:
dev/feature no longer supports 1.16, marking resolved.

2024-12-15 22:55 UTC, sovdeeth approved these changes
The skript side of this PR looks solid. I am not familiar enough with SQL to comment on the storage implementations, but I'll be testing it to make sure it works.

Only a few small comments (the licenses at the start of files should also be removed)

nice work lime!

2024-12-15 22:55 UTC, sovdeeth commented on src/main/java/ch/njol/skript/variables/Variables.java
> +								"Meaning you will be losing out on drastic performance.\n" +
```suggestion
								"Meaning you will be losing out on drastic performance.\n" +
```
drastic performance what?
i think this should say `drastic performance improvements`

2024-12-15 23:11 UTC, sovdeeth commented
Also some pretty big conflicts that need resolving, and I unfortunately am not familiar enough with the code to do it for ya

2024-12-17 20:13 UTC, APickledWalrus requested changes
Looks pretty good. My SQL knowledge is limited, but from what I do know, it seems fine. I know this has gone through testing on Discord as well.
Just a few minor things, re-request for approval

2024-12-17 20:13 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/variables/SerializedVariable.java
For the modified fields/added methods, `@Nullable` annotations can be placed inline before the type.

2024-12-17 20:13 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/variables/VariableStorage.java
> +	public final boolean load_i(SectionNode sectionNode) {
Not sure about a public method being suffixed `_i`. Could we come up with a different name?

2024-12-17 20:13 UTC, APickledWalrus commented on src/main/java/org/skriptlang/skript/variables/storage/SQLiteStorage.java
> +@Deprecated
`@deprecated` javadocs would be good to point users to H2/MySQL storage

2024-12-17 20:13 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/variables/JdbcStorage.java
> +public abstract class JdbcStorage extends VariableStorage {
docs?

2024-12-17 20:13 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/variables/JdbcStorage.java
> +					if (WRITE_QUERY != null)
Can the `try` statements go within the null checks?

2024-12-17 20:13 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/variables/JdbcStorage.java
> +			Timespan monitor_interval = getValue(section, "monitor interval", Timespan.class);
I would prefer to stick to camel case

2025-02-08 12:25 UTC, Lennord commented
@TheLimeGlass Hi, can you update for Skript 2.10.1 and fixed the big issues with auto-commit please.

2025-03-02 17:20 UTC, Lennord commented
@TheLimeGlass Hello, can you fix the issues reported on auto-commit please?

2025-03-10 21:29 UTC, sovdeeth commented
closing in favor of https://github.com/SkriptLang/Skript/pull/7653

2025-03-10 21:29 UTC, closed without merging