Add reset block change effect
SkriptLang/Skript pull request #5672
Opened 2023-05-05 01:45 UTC by TheLimeGlass

### Description
Adds a reset syntax to the block change effect.
Removed 1.13 reflection.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/1428

2023-05-05 02:02 UTC, DelayedGaming commented
There’s an active PR which removes legacy code and support with the new methods #5661

2023-09-08 10:44 UTC, Moderocky requested changes

2023-09-08 10:44 UTC, Moderocky commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +		return String.format("make %s see %s as %s",
The format pattern will be wrong if the reset pattern was used.

2024-05-03 06:46 UTC, Moderocky approved these changes

2024-05-04 13:18 UTC, sovdeeth reviewed
I don't like the third pattern but i don't think it needs to be removed, so refraining from approval/requesting changes

2024-05-04 13:18 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +				"(reset|sync) %blocks% (for|to) %players% [with the server]");
i think this pattern's a little awkward and doesn't really add much. The 2nd pattern seems to cover the role very well and matches the format better.

2024-05-13 19:53 UTC, sovdeeth requested changes

2024-05-13 19:53 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +		if (matchedPattern == 1)
Shouldn't this be == 0?

2024-08-16 20:58 UTC, APickledWalrus requested changes

2024-08-16 20:58 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +		if (matchedPattern == 1)
```suggestion
		if (matchedPattern == 0)
```

2024-09-13 14:42 UTC, sovdeeth requested changes

2024-09-13 14:42 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
>  			BlockData blockData = (BlockData) object;
pattern vars

2024-09-13 14:42 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
>  			ItemType itemType = (ItemType) object;
pattern vars

2024-11-17 19:26 UTC, sovdeeth requested changes
looks good, just need to fix a bug from the existing code

2024-11-17 19:26 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +				for (Block block : blocks.getArray(event)) {
this evaluates the blocks expression multiple times
getArray needs to be done outside the loop

2024-11-17 19:26 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +				for (Block block : blocks.getArray(event)) {
this evaluates the blocks expression multiple times
getArray needs to be done outside the loop

2024-11-17 19:26 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +				for (Block block : blocks.getArray(event)) {
this evaluates the blocks expression multiple times
getArray needs to be done outside the loop

2024-11-22 16:07 UTC, APickledWalrus requested changes
Should be good after Sovde's comments are addressed. Feel free to re-request at that point and I will approve.

2024-11-22 16:07 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
> +	public String toString(@Nullable Event event, boolean debug) {
Could use the SyntaxStringBuilder that was recently introduced

2025-05-06 21:52 UTC, sovdeeth commented
Inactive

2025-05-06 21:52 UTC, closed without merging