🚀 Add event values to events in docs
SkriptLang/Skript pull request #5690
Opened 2023-05-10 20:05 UTC by AyhamAl-Ali

### Description

- Added event values to events in docs
- Added `EventValueInfo#getTime()`
- Added `EventValueInfo#isEventExcluded(Class)`
- Overloaded `EventValueInfo` constructor and deprecated the old one due to `time` param
- Added `EventValues#getPerEventEventValues()` for getting all events values per event -- useful for docs

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:** 
- closes https://github.com/SkriptLang/skript-docs/issues/37

2023-05-12 21:03 UTC, APickledWalrus requested changes

2023-05-12 21:03 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +		for (int i = -1; i < 2; i++) {
```suggestion
		for (int i = TIME_PAST; i <= TIME_FUTURE; i++) {
```
maybe? :)

2023-05-12 21:03 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/doc/HTMLGenerator.java
> +					String className = eventValueInfo.c.getSimpleName().toLowerCase(Locale.ENGLISH);
should this use the ClassInfo name instead of replacing?

2023-07-11 04:21 UTC, TheLimeGlass requested changes

2023-07-11 04:21 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/doc/HTMLGenerator.java
> +		List<String> eventValues = new ArrayList<>(0);
```suggestion
		List<String> eventValues = new ArrayList<>();
```
No need to initialize the array list here, unless you want to do eventValuesSet.size()

2023-07-11 04:21 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/registrations/EventValues.java
> +				}
Java won't run the for loop if null
```suggestion
			for (Class<? extends Event> exclude : excludes) {
				if (exclude.isAssignableFrom(c))
					return true;
			}
```

2023-07-11 04:21 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/doc/HTMLGenerator.java
> +	private Map<Class<? extends Event>, List<EventValues.EventValueInfo<?, ?>>> eventValuesCache = new HashMap<>();
Should clear this cache after the templates have been generated, we don't need it sitting in here.

2024-09-15 20:19 UTC, sovdeeth commented
closing due to inactivity

2024-09-15 20:19 UTC, closed without merging