Expression Skull Owner
SkriptLang/Skript pull request #5698
Opened 2023-05-15 07:44 UTC by DelayedGaming

### Description
This PR adds skull owner expression into Skript!
Javadocs:
- https://jd.papermc.io/paper/1.19/org/bukkit/block/Skull.html#getOwningPlayer()
- https://jd.papermc.io/paper/1.19/org/bukkit/block/Skull.html#setOwningPlayer(org.bukkit.OfflinePlayer)

---
**Target Minecraft Versions:** any
**Requirements:** -
**Related Issues:** -

2023-05-15 07:51 UTC, AyhamAl-Ali requested changes
Nice PR ⚡

2023-05-15 07:51 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +	public @Nullable OfflinePlayer convert(Block block) {
We can improve this by adding an init and check for literals if the block is not a skull it would error

2023-06-02 05:51 UTC, TheLimeGlass requested changes

2023-06-02 05:51 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +	"set skull owner of {_block} to player"
Provide an understanding of username setting.
```suggestion
	"set skull owner of {_block} to \"Njol\" parsed as offlineplayer"
```

2023-06-02 05:51 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +	public @Nullable Class<?>[] acceptChange(ChangeMode mode) {
```suggestion
	@Override
	@Nullable
	public Class<?>[] acceptChange(ChangeMode mode) {
```

2023-06-02 05:51 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +		return null;
```suggestion
		BlockState state = block.getState();
		if (!(state instanceof Skull))
			return null;
		return ((Skull) state).getOwningPlayer();
```

2023-06-02 05:51 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +		}
Cache the cast, and use BlockState for future proofing.
```suggestion
		OfflinePlayer offlinePlayer = (OfflinePlayer) delta[0];
		for (Block block : getExpr().getArray(event)) {
			BlockState state = block.getState();
			if (state instanceof Skull) {
				Skull skull = (Skull) state;
				skull.setOwningPlayer(offlinePlayer);
				skull.update();
			}
		}
```

2023-06-02 05:54 UTC, TheLimeGlass requested changes
Skript already has ItemType set block with Skull, but this allows to properly get the username of the skull without parsing the itemtype `skull of LimeGlass`

2023-06-02 05:54 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +				skull.update();
Don't apply physics
```suggestion
				skull.update(true, false);
```

2024-03-19 20:59 UTC, sovdeeth approved these changes
With Ayham's request, looks good.

2024-04-20 07:23 UTC, AyhamAl-Ali approved these changes

2024-07-01 08:18 UTC, Moderocky approved these changes

2024-07-01 23:32 UTC, APickledWalrus approved these changes

2024-07-01 23:37 UTC, merged