Fix the stop sound effect pattern
SkriptLang/Skript pull request #5758
Opened 2023-06-23 23:18 UTC by TheLimeGlass

### Description
Fix the stop sound effect pattern.

---
**Target Minecraft Versions:** 1.17+
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5756

2023-07-12 08:04 UTC, Moderocky approved these changes

2023-08-04 09:13 UTC, TheLimeGlass commented
The 2.7 target of this pull was merged. Waiting on another approval. Any requested changes will require another 2.7 target pull request to clone changes.

2023-08-04 11:16 UTC, AyhamAl-Ali requested changes

2023-08-04 17:57 UTC, sovdeeth approved these changes

2023-08-04 22:05 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/effects/EffStopSound.java
> +		String stopPattern = STOP_ALL_SUPPORTED ? "(all:all sound[s]|sound[s] %-strings%)" : "sound[s] %strings%";
The expression isn't optional therefore making it doesn't make sense

2023-08-04 22:40 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/effects/EffStopSound.java
> +		String stopPattern = STOP_ALL_SUPPORTED ? "(all:all sound[s]|sound[s] %-strings%)" : "sound[s] %strings%";
A string could be anything from the event. I don't even think we have a sound string as a default value. This would not work.

2023-09-08 21:34 UTC, APickledWalrus approved these changes

2023-09-09 10:45 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/effects/EffStopSound.java
> +		String stopPattern = STOP_ALL_SUPPORTED ? "(all:all sound[s]|sound[s] %-strings%)" : "sound[s] %strings%";
This was already merged into 2.7, any changes are separate. I made both the 2.7 target and this at the same time, the 2.7 target got merged first I guess.

2023-10-17 18:36 UTC, closed without merging

2023-10-17 18:37 UTC, TheLimeGlass commented
Closing because this got merged in 2.7 and was at the time when the release cycle changed, so it got added to feature branch.