Add condition type to fix parsing order
SkriptLang/Skript pull request #5809
Opened 2023-07-10 02:27 UTC by TheLimeGlass

### Description
Add condition type to fix parsing order.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5804 probably fixes other issues too.

2023-07-10 08:14 UTC, Moderocky approved these changes
Looks good, I'd like to make sure this isn't going to (somehow) break a bunch of scripts by changing the parsing orders.

2023-07-10 11:41 UTC, TheLimeGlass commented
> Looks good, I'd like to make sure this isn't going to (somehow) break a bunch of scripts by changing the parsing orders.

2.8 betas will find out, I didn't find any from the tests, but I got the proper conditions to work, so that's a plus.

2024-02-22 19:28 UTC, TheLimeGlass commented
Tests failing are unrelated. Currently failing outside this pull request.

2024-03-05 15:09 UTC, sovdeeth approved these changes

2024-04-26 18:11 UTC, Moderocky requested changes
Conflicts need fixing.

2024-08-16 22:09 UTC, APickledWalrus approved these changes
Implementation is fine. The idea of condition priorities exists in <https://github.com/SkriptLang/Skript/pull/6246> which may end up getting merged for 2.10 (meaning this PR may only need to set priorities for something like CondCompare)

2024-08-16 22:09 UTC, APickledWalrus commented on src/test/skript/tests/regressions/5804-is-burning.sk
> +
```suggestion
```

2024-08-19 17:42 UTC, TheLimeGlass commented
When I created this pull request, I wanna add that this fix actually turned out surprisingly well, it fixed so many issues, and it's very simple in the fact that it's just modifying the list order like Expressions with ExpressionType.

2024-08-19 17:56 UTC, Moderocky approved these changes

2024-08-19 17:56 UTC, APickledWalrus commented
Oh yeah I think the idea is good. I'm fine with merging this.

2024-08-19 17:56 UTC, merged