Add player time expression
SkriptLang/Skript pull request #5832
Opened 2023-07-14 09:25 UTC by Fusezion

### Description

This PR aims to add support for per player time

---
**Target Minecraft Versions:**  any
**Requirements:**  none
**Related Issues:**  #5828

2023-07-14 09:31 UTC, Fusezion commented
I do want to make this as a opinion, this class isn't technically needed in a new file I could probably transfer this into the `ExprTime` class where we change world time. If anyone agrees that it might be better to add it there please let me know and I'll look into doing it

2023-07-14 11:17 UTC, AyhamAl-Ali approved these changes

2023-07-14 11:17 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +	"When setting relative time for a player, their time will tick inline with the world, without it will be static."})
```suggestion
	"When setting relative time for a player, their time will tick inline with the world, without it will be static."
})
```

2023-07-14 11:17 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +	"set player time of player to dusk, 10:00 or midnight",
For beginners not to misunderstand this.
```suggestion
	"set player time of player to dusk, 10:00 or midnight # random out of the three options",
```

2023-07-14 11:17 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +					player.setPlayerTime(Math.max(newTime,0), relative);
```suggestion
					player.setPlayerTime(Math.max(newTime, 0), relative);
```

2023-07-14 11:24 UTC, ahmadMsaleem approved these changes

2023-07-14 19:39 UTC, TheLimeGlass requested changes

2023-07-14 19:39 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +	public @Nullable Time convert(Player player) {
```suggestion
	@Override
	@Nullable
	public Time convert(Player player) {
```

2023-07-14 19:39 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +		switch (mode) {
missing default, return null in the default so a return null isn't needed after switch.

2023-07-14 19:39 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +	}
```suggestion
	}

```

2023-07-14 19:39 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprPlayerTime.java
> +					player.setPlayerTime(Math.max(newTime, 0), relative);
```suggestion
					player.setPlayerTime(Math.max(0, newTime), relative);
```

2023-07-16 23:34 UTC, TheLimeGlass requested changes
This should be merged with https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprTime.java which can be SimplePropertyExpression by the way, it's old so it isn't.

2023-07-16 23:36 UTC, Fusezion commented
> This should be merged with https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprTime.java which can be SimplePropertyExpression by the way, it's old so it isn't.

Was thinking it might be possible but does register default work with multiple types?

2023-07-16 23:43 UTC, TheLimeGlass commented
> > This should be merged with https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprTime.java which can be SimplePropertyExpression by the way, it's old so it isn't.
> 
> Was thinking it might be possible but does register default work with multiple types?

Yes it should work. But in my opinion now that you're changing it to support multiple types it wouldn't make sense to do against the Player and also would be a breaking change. As a world and player event-value can be present at the same time. So what would `time` refer to, right?

A syntax suggestion to help you out, could follow;
```
[the] time[s] [([with]in|of) %worlds%]
[the] [:relative] time[s] of %players%
%worlds/players%'[s] [:relative] time[s] #relative would do nothing for world.
```
Either calling SimplePropertyExpression#register twice or using Skript#registerExpression of the modified syntaxes. Place comment stating default expressions should only be done for the world type.

2024-07-16 06:44 UTC, sovdeeth commented
Closing due to inactivity.

2024-07-16 06:44 UTC, closed without merging