⚒ Fix enchanting multiple items
SkriptLang/Skript pull request #5927
Opened 2023-08-20 07:28 UTC by AyhamAl-Ali

### Description

A quick fix for #5530 instead of waiting for #4366 since that might take sometime and this fix should also target 2.7

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:** 
- #5530

2023-08-20 07:44 UTC, Moderocky approved these changes

2023-08-20 08:13 UTC, Fusezion approved these changes
Testing went fine didn't run into any other errors while using this build.

2023-08-23 09:13 UTC, TheLimeGlass requested changes

2023-08-23 09:13 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/effects/EffEnchant.java
>  	@Override
```suggestion
	@Override
	@SuppressWarnings("unchecked")
```

2023-08-23 09:13 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/effects/EffEnchant.java
> +					assert enchantment != null;
An assertion means nothing here without a testing environment. Potentially add tests to this pull request.

2023-08-23 09:22 UTC, merged