Allow numbers in the changer for ExprHotbarSlot
SkriptLang/Skript pull request #6139
Opened 2023-10-21 05:18 UTC by TheLimeGlass

### Description
The ExprHotbarSlot currently requires a slot to be able to change the index of the slot.
This means that you have to type `set the currently selected hotbar slot of player to slot 8 of player`

This pull request allows for that still, but also removes the redundancy of typing out the entire slot
`set hotbar slot of player to 8`

The setHeldItemSlot only takes in an integer, so it makes to sense to support a direct input of an integer.

Also fixes a bug where there was no integer check for the input value being under 0 which could lead to an IllegalArgumentException being thrown.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2023-10-21 08:37 UTC, Moderocky approved these changes

2023-10-21 10:55 UTC, UnderscoreTud requested changes

2023-10-21 10:55 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
> +			if (!(slot instanceof InventorySlot))
What's the point of having two instance checks? Can't you just replace the outer one with this?

2023-10-21 10:55 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
> +			Slot slot = (Slot) delta[0];
Why are you using `delta[0]` rather than the variable you set earlier?

2023-10-21 13:09 UTC, UnderscoreTud requested changes

2023-10-21 13:09 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
> +			number = ((InventorySlot) slot).getIndex();
Tests are failing; you never declare `slot`.

2023-10-22 17:36 UTC, UnderscoreTud approved these changes

2023-10-22 20:12 UTC, merged