Add tests for item syntaxes.
SkriptLang/Skript pull request #6164
Opened 2023-11-01 09:43 UTC by Moderocky

### Description

Adds tests for some item-related syntaxes.

Please feel free to contribute any that I have missed.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6158

2024-04-30 23:55 UTC, sovdeeth approved these changes

2024-04-30 23:56 UTC, sovdeeth requested changes
oh almost forgot!

2024-04-30 23:56 UTC, sovdeeth commented on src/test/skript/tests/syntaxes/expressions/ExprItemsIn.sk
> +	assert {_list::3} is 36 of iron ingot with "new third item failed: %{_list::3}%"
```suggestion
	assert size of {_list::*} is 4 with "size of items in failed"
	assert {_list::1} is stone with "first item failed"
	assert {_list::2} is stone named "bread" with "second item failed"
	assert {_list::3} is 64 of iron ingot with "third item failed"
	assert {_list::4} is 36 of iron ingot with "split fourth item failed"
	remove stone from {_inventory}
	set {_list::*} to items in {_inventory}
	assert size of {_list::*} is 3 with "size of second items in failed"
	assert {_list::1} is stone named "bread" with "new first item failed"
	assert {_list::2} is 64 of iron ingot with "new second item failed"
	assert {_list::3} is 36 of iron ingot with "new third item failed"
```

2024-05-01 16:50 UTC, sovdeeth approved these changes

2024-06-06 20:00 UTC, APickledWalrus approved these changes

2024-06-06 20:00 UTC, APickledWalrus commented on src/test/skript/tests/syntaxes/expressions/ExprItemsIn.sk
> +
```suggestion
```

2024-07-01 13:35 UTC, merged