Add inventory size to the slots syntax
SkriptLang/Skript pull request #6236
Opened 2023-12-18 05:27 UTC by TheLimeGlass

### Description
Add `inventory size of %inventories%` to the slots syntax. Many people don't know inventory size actually exists in Skript. Addons call this term "inventory size", so this pull adds an aliases for it.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2023-12-18 05:38 UTC, Fusezion commented
I personally fine the usage of "inventory size" confusing and don't believe this should be something encouraged to use. For me when I see "inventory size" this feels more related to "rows" and not "slots" oh the inventory size of a barrel is 3 makes sense but
reading it as inventory size of a barrel is 27 that's much less understanding as we're not talking about a size of the inventory to me.

And lastly is there any way to possible make the syntax look like less of a mess?
`(holder[s]|viewers|[amount of] rows|([amount of] slots|inventory size)) of %inventories%`

This issue is too prevalent on skript expressions where there's multiple options and should be changed to make reading docs understandable.

2024-03-21 17:58 UTC, sovdeeth commented
> And lastly is there any way to possible make the syntax look like less of a mess? `(holder[s]|viewers|[amount of] rows|([amount of] slots|inventory size)) of %inventories%`
> 
> This issue is too prevalent on skript expressions where there's multiple options and should be changed to make reading docs easier and more understandable.

I agree, these should each be different patterns.

2024-04-30 09:17 UTC, Moderocky requested changes

2024-04-30 09:17 UTC, Moderocky commented on src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
> +				"(" + HOLDER + "¦holder[s]|" + VIEWERS + "¦viewers|" + ROWS + "¦[amount of] rows|" + SLOTS + "¦([amount of] slots|inventory size))" + " of %inventories%",
We don't use the old split pipe `¦` parse mark anymore.

2024-04-30 09:17 UTC, Moderocky commented on src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
> +				"%inventories%'[s] (" + HOLDER + "¦holder[s]|" + VIEWERS + "¦viewers|" + ROWS + "¦[amount of] rows|" + SLOTS + "¦([amount of] slots|inventory size))"
I think `inventory size` is quite ambiguous and might return what somebody doesn't expect. Having the rows/slots part explicit was probably better.

2024-11-15 23:57 UTC, sovdeeth commented
Closing due to inactivity

2024-11-15 23:57 UTC, closed without merging