Fix CondCompare Logging
SkriptLang/Skript pull request #6266
Opened 2023-12-29 18:29 UTC by APickledWalrus

### Description

This fixes logging problems with CondCompare that were the cause of the issue below. The errors in the linked issue are ghost errors from CondCompare reparsing literals to find a good comparison. The problem is, even when CondCompare is successful, it prints the entire log which includes errors from failed Classes.parse attempts.

To combat this issue, I have replaced the RetainingLogHandler with a ParseLogHandler. When it needs to print an error, it will print the most recent/relevant error. At the end, when successful, it will print all non-error log messages (e.g. warnings that are likely to be applicable).

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:**
- https://github.com/SkriptLang/Skript/issues/6251

2023-12-29 18:35 UTC, Fusezion requested changes
Looks good to me and runs as intended, regression test should be added

2023-12-29 18:40 UTC, TheLimeGlass approved these changes

2023-12-29 20:07 UTC, AyhamAl-Ali approved these changes
Tests would be beneficial indeed.

2023-12-30 07:30 UTC, sovdeeth approved these changes

2023-12-30 22:03 UTC, APickledWalrus commented
I'm not sure of any easy way to test this as the errors did not occur with a vanilla Skript installation. I think it will be alright without a test since the changes are minimal.

2023-12-30 22:03 UTC, merged