Add Russian translation
SkriptLang/Skript pull request #6272
Opened 2023-12-31 12:08 UTC by envizar

### Description
Simply add russian translation

---
**Target Minecraft Versions:** any
**Requirements:** none 
**Related Issues:** none

2023-12-31 13:39 UTC, DelayedGaming commented
Don’t forget to add `Russian` as an available option in [config.sk](https://github.com/SkriptLang/Skript/blob/7178dc41c4c6a2e8b68c082e3c7d83c1739c791c/src/main/resources/config.sk#L34).

2023-12-31 21:46 UTC, AyhamAl-Ali commented
Thank you for your contribution⚡We will be waiting for Russian users to review and approve this PR.

2024-02-14 08:13 UTC, Lotzyprod requested changes
Fix some mistakes

2024-02-14 08:13 UTC, Lotzyprod commented on src/main/resources/lang/russian.lang
> +		12 hours: Вы используйте 12-ти часовой формат, так что Вы не можете использовать больше 12 часов
```suggestion
		12 hours: Вы используете 12-ти часовой формат, так что Вы не можете использовать больше 12 часов
```

2024-02-14 08:13 UTC, Lotzyprod commented on src/main/resources/lang/russian.lang
> +			description: Проверить наличие обновлений, почитать список изменений или скачать последнюю версию Skript
```suggestion
			description: Проверить наличие обновлений, прочитать список изменений, или скачать последнюю версию Skript
```

2024-02-14 08:13 UTC, Lotzyprod commented on src/main/resources/lang/russian.lang
> +			description: Перезагружает один скрипт, все скрипты, конфиг или всё сразу
```suggestion
			description: Перезагружает один скрипт, все скрипты, основной конфиг, или всё сразу
```

2024-02-14 08:13 UTC, Lotzyprod commented on src/main/resources/lang/russian.lang
> +			all: Перезагружает конфиг, все конфиги алиасов и все скрипты
```suggestion
			all: Перезагружает основной конфиг, конфиги алиасов и все скрипты
```

2024-02-14 08:13 UTC, Lotzyprod commented on src/main/resources/lang/russian.lang
> +	no scripts: Папка со скриптами пуста. Думаю, тебе стоит её наполнить :)
```suggestion
	no scripts: Папка со скриптами пуста. Думаю, вам стоит её наполнить :)
```

2024-02-14 08:13 UTC, Lotzyprod commented on src/main/resources/lang/russian.lang
> +	quotes error: Неверное использование кавычек ("). Если необходимо использовать кавычки внутри строки, просто продублируйте их: "".
```suggestion
	quotes error: Неверное использование кавычек ("). Если вам необходимо использовать кавычки внутри строки, просто продублируйте их: "".
```

2024-02-14 10:01 UTC, envizar reviewed
Спасибо!

2024-02-14 10:09 UTC, Lotzyprod approved these changes

2024-04-08 11:33 UTC, Lotzyprod approved these changes

2024-04-08 12:45 UTC, Moderocky approved these changes

2024-04-09 08:33 UTC, lumik0 reviewed
Not a single bad word found
Improved some

2024-04-09 08:33 UTC, lumik0 commented on src/main/resources/lang/russian.lang
> +	no player starts with: Мы не нашли игрока, чьё имя начинается с '%s'
Не найден игрок, имя которое начинается с '%s'.

2024-04-09 08:33 UTC, lumik0 commented on src/main/resources/lang/russian.lang
> +	multiple players start with: Мы нашли несколько игроков, чьё имя начинается с '%s'
Не найдено игроков, имя которых начинается с '%s'.

2024-04-09 08:33 UTC, lumik0 commented on src/main/resources/lang/russian.lang
> +	error: Не смогли подключиться к %1$s. Это может произойти, если Skript ещё не поддерживает установленную версию %1$s
Не удалось подключиться к %1$s. Это может произойти, если Skript ещё не поддерживает установленную версию %1$s

2024-04-09 08:33 UTC, lumik0 commented on src/main/resources/lang/russian.lang
> +	loaded x aliases from: Загружено %s английских алиасов из %s
remove английских

2024-04-09 08:33 UTC, lumik0 commented on src/main/resources/lang/russian.lang
> +	loaded x aliases: Загружено %s английских алиасов
remove английских

2024-04-09 08:33 UTC, lumik0 commented on src/main/resources/lang/russian.lang
> +	no permission message: У Вас отсутствует необходимое разрешение для выполнения этой команды
It’s better this way: “Нет прав для выполнения этой команды” since all Russian popular servers use this way

2024-04-09 13:38 UTC, aBobby5415 commented
Although it’s a small thing, it’s really necessary 👍

2024-04-13 08:11 UTC, Moderocky commented
I shall count this as being reviewed sufficiently.

2024-04-13 08:11 UTC, merged