Add multiple locations to ExprLocation
SkriptLang/Skript pull request #6343
Opened 2024-01-18 03:40 UTC by TheLimeGlass

Add multiple locations to ExprLocation

### Description
Add multiple locations to ExprLocation. Direction.combine already supports acceptance of multiple locations and directions, so it should be supported.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-02-02 17:41 UTC, sovdeeth requested changes
This causes code like
```
location 1 above me, location at me, location left of me
```
to act differently. It's now parsed like
```
(location 1 above (me, location at (me, location left of me)))
```
instead of
```
(location 1 above me), (location at me), (location left of me)
```
I think that this needs to be fixed if this change is to be made.

2024-02-02 17:41 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprLocation.java
> +		Skript.registerExpression(ExprLocation.class, Location.class, ExpressionType.COMBINED, "[the] (location|position) %directions% [%locations%]");
```suggestion
		Skript.registerExpression(ExprLocation.class, Location.class, ExpressionType.COMBINED, "[the] (location|position)[s] %directions% [%locations%]");
```

Also add `s` depending on plurality to the toString

2024-03-29 15:53 UTC, AyhamAl-Ali commented
I like it but marking it as **up for debate** due to an important current parser limitation ([Sovde's comment](https://github.com/SkriptLang/Skript/pull/6343#pullrequestreview-1859936630))

2024-04-07 13:28 UTC, sovdeeth requested changes
My previous issues have not been addressed. Why'd you re-request me?

2024-04-07 14:17 UTC, TheLimeGlass commented
> My previous issues have not been addressed. Why'd you re-request me?

Plurality requested change was applied. Multiple list elements parsing is an unrelated bug see function parameter parsing issue, and incorrect example of how supposed parsing happens. An At literal requires a location or a default expression.

2024-04-07 14:29 UTC, sovdeeth commented
> > My previous issues have not been addressed. Why'd you re-request me?
> 
> Plurality requested change was applied. Multiple list elements parsing is an unrelated bug see function parameter parsing issue, and incorrect example of how supposed parsing happens. An At literal requires a location or a default expression.

I promise you it's a correct example. Here's some evidence:

BEFORE:
```
[16:20:53 INFO]: [Skript] send (the location [[long:1]] meter(s) above me, the location at me and the location 0 meters in front of and to the right of me)[class org.bukkit.Location] to [player:Sahvde [location:(world:-73.39182313896981,91.11813596549652,17.05509446310981|yaw=-83.87316/pitch=35.849674)]]
[16:21:05 INFO]: x: -73.39, y: 92.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
[16:21:05 INFO]: x: -73.39, y: 91.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
[16:21:05 INFO]: x: -73.31, y: 91.12, z: 16.25, yaw: -83.87, pitch: 35.85 in 'world'
```

AFTER:
```
[16:27:06 INFO]: [Skript] broadcast location [[long:1]] meter(s) above (me, location at me and location 0 meters in front of and to the right of me)[class org.bukkit.Location]
[16:27:10 INFO]: x: -73.39, y: 92.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
[16:27:10 INFO]: x: -73.39, y: 92.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
[16:27:10 INFO]: x: -73.31, y: 92.12, z: 16.25, yaw: -83.87, pitch: 35.85 in 'world'
```
![image](https://github.com/SkriptLang/Skript/assets/10354869/e426b4b7-5d32-44e3-8847-0cbfac0b6f15)

2024-04-07 15:18 UTC, TheLimeGlass commented
> > > My previous issues have not been addressed. Why'd you re-request me?
> > 
> > 
> > Plurality requested change was applied. Multiple list elements parsing is an unrelated bug see function parameter parsing issue, and incorrect example of how supposed parsing happens. An At literal requires a location or a default expression.
> 
> I promise you it's a correct example. Here's some evidence:
> 
> BEFORE:
> 
> ```
> [16:20:53 INFO]: [Skript] send (the location [[long:1]] meter(s) above me, the location at me and the location 0 meters in front of and to the right of me)[class org.bukkit.Location] to [player:Sahvde [location:(world:-73.39182313896981,91.11813596549652,17.05509446310981|yaw=-83.87316/pitch=35.849674)]]
> [16:21:05 INFO]: x: -73.39, y: 92.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
> [16:21:05 INFO]: x: -73.39, y: 91.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
> [16:21:05 INFO]: x: -73.31, y: 91.12, z: 16.25, yaw: -83.87, pitch: 35.85 in 'world'
> ```
> 
> AFTER:
> 
> ```
> [16:27:06 INFO]: [Skript] broadcast location [[long:1]] meter(s) above (me, location at me and location 0 meters in front of and to the right of me)[class org.bukkit.Location]
> [16:27:10 INFO]: x: -73.39, y: 92.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
> [16:27:10 INFO]: x: -73.39, y: 92.12, z: 17.06, yaw: -83.87, pitch: 35.85 in 'world'
> [16:27:10 INFO]: x: -73.31, y: 92.12, z: 16.25, yaw: -83.87, pitch: 35.85 in 'world'
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/10354869/320288826-e426b4b7-5d32-44e3-8847-0cbfac0b6f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDMzNjQsIm5iZiI6MTcxMjUwMzA2NCwicGF0aCI6Ii8xMDM1NDg2OS8zMjAyODg4MjYtZTQyNmI0YjctNWQzMi00NGUzLTg4NDctMGNiZmFjMGI2ZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE1MTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTMzZjE4Y2I4YjdhMjM5Y2ZlMzE3NzJhZWM5NzgyNTJjMDJkYjA1OTI5ZWI1OWUwYzY1MjM1MThjOGQzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rIZkAzcQXzO6PAelOw1JLdPyz_MxtMel3JnUts24nmY)

Fixing the function parameter parsing is on my to-do list, I'll investigate this at a later matter.

2024-08-17 16:14 UTC, Moderocky commented
> Fixing the function parameter parsing is on my to-do list, I'll investigate this at a later matter.


Did my changes to function parameter lists impact this?

2024-09-17 20:54 UTC, TheLimeGlass commented
> > Fixing the function parameter parsing is on my to-do list, I'll investigate this at a later matter.
> 
> Did my changes to function parameter lists impact this?

Pull request link?

2025-04-07 22:09 UTC, sovdeeth commented
Closing due to inactivity and unaddressed parsing concerns

2025-04-07 22:09 UTC, closed without merging