Create ExitHandlingSection interface
SkriptLang/Skript pull request #6349
Opened 2024-01-20 15:58 UTC by takejohn

### Description

* Add an interface `ExitHandlingSection`, having one method `exit(Event)`.
* Change `LoopSection` to implement this.
* Change the 'exit' and 'return' effects to check if the enclosing nodes are ExitHandlingSections instead of checking for LoopSections.

This PR enables addons to add sections which don't need to hold loop counters doing something when exited.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-01-20 16:23 UTC, sovdeeth approved these changes
Looks like a nice change to me!

2024-01-20 16:54 UTC, APickledWalrus commented
I'm not sure about the name. What do you think about something like `ExitableSection`

2024-01-20 17:23 UTC, AyhamAl-Ali requested changes
Nice change

2024-01-20 17:23 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/lang/ExitHandlingSection.java
I agree with Pickle, I think the name `SectionExitHandler` would be better

2024-01-20 17:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/ExitHandlingSection.java
yeah something like that is probably a better name giving that it's not actually a section itself

2024-02-17 22:14 UTC, AyhamAl-Ali approved these changes

2024-03-09 20:08 UTC, APickledWalrus approved these changes

2024-03-09 20:15 UTC, merged

2024-03-09 20:15 UTC, APickledWalrus commented
Thanks for this!