Fix ExprPlain always getting the base material from ItemTypes
SkriptLang/Skript pull request #6391
Opened 2024-02-02 16:31 UTC by sovdeeth

### Description

Calls ItemType#getRandom() to ensure the item is a accurate representation of the alias (e.g. any sword) before getting the material.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5994

2024-02-02 19:17 UTC, AyhamAl-Ali approved these changes

2024-02-02 21:54 UTC, APickledWalrus approved these changes

2024-02-03 02:42 UTC, Pikachu920 commented
can we add a regression test please?

2024-02-03 08:32 UTC, sovdeeth commented
> can we add a regression test please?

I didn't know how to do one that didn't have an inherently random chance of failing. Any advice?

2024-02-03 13:43 UTC, Moderocky approved these changes

2024-02-04 02:43 UTC, Pikachu920 commented
> > can we add a regression test please?
> 
> I didn't know how to do one that didn't have an inherently random chance of failing. Any advice?

i think you could use mockito to ensure getRandom gets called on the itemtype

2024-02-04 18:51 UTC, Pikachu920 requested changes

2024-02-04 18:51 UTC, Pikachu920 commented on src/test/java/org/skriptlang/skript/test/tests/regression/ExprPlainAliasTest.java
> +
```suggestion
// https://github.com/SkriptLang/Skript/issues/5994
```

2024-02-04 19:26 UTC, Pikachu920 approved these changes

2024-02-04 21:36 UTC, merged