Add teleport eventually to EffTeleport
SkriptLang/Skript pull request #6448
Opened 2024-02-21 00:23 UTC by Pikachu920

### Description

This PR adds a "teleport eventually" effect which can be used to teleport something async but without pausing script execution until the teleport completes. This is mainly intended for utilizing async teleports in functions that don't rely on the teleport happening immediately in order to run

---
**Target Minecraft Versions:** any 
**Requirements:** Paper if you want the async loading
**Related Issues:** #6444

2024-02-21 20:41 UTC, Fusezion requested changes

2024-02-21 20:41 UTC, Fusezion commented on src/main/java/ch/njol/skript/effects/EffTeleport.java
>  	}
Let me know if I'm wrong but it looks like we're missing `%` on `direction` in the last 2 patterns, now it's just `teleport %entity% direction %location%`
```suggestion
		Skript.registerEffect(EffTeleport.class,
			"teleport %entities% (to|%direction%) %location%",
					"(force|immediately) teleport %entities% (to|%direction%) %location%",
					"teleport %entities% (to|%direction%) %location% (eventually|as soon as possible)"
			);
	}
```

2024-02-21 20:49 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffTeleport.java
> +			Bukkit.getScheduler().runTask(Skript.getInstance(), () -> {
might be worth using the Task util class, e.g. https://github.com/SkriptLang/Skript/blob/0bfec0b709cf74bace063d315d0eb501058cac14/src/main/java/ch/njol/skript/util/Task.java#L147

2024-09-15 20:17 UTC, sovdeeth commented
closing due to inactivity

2024-09-15 20:17 UTC, closed without merging