Adds pathfinding condition
SkriptLang/Skript pull request #6506
Opened 2024-03-22 23:59 UTC by TheLimeGlass

### Description
Adds pathfinding condition

---
**Target Minecraft Versions:** any 
**Requirements:** Paper
**Related Issues:** none

2024-03-23 16:56 UTC, sovdeeth requested changes

2024-03-23 16:56 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondIsPathfinding.java
> +			PropertyCondition.register(CondIsPathfinding.class, "pathfinding [to[wards] %-livingentity/location%]", "livingentities");
You're registering a negated pattern but never handling it in the code for the condition.

2024-03-23 17:49 UTC, sovdeeth approved these changes

2024-03-27 18:05 UTC, Moderocky approved these changes

2024-03-27 18:22 UTC, AyhamAl-Ali approved these changes

2024-03-29 07:36 UTC, merged