Changes to the Leash effect's Description and Examples.
SkriptLang/Skript pull request #6528
Opened 2024-04-03 01:50 UTC by Asleeepp

### Description

Changes the examples and description of the Leash effect to make it more clear.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-04-03 01:57 UTC, AyhamAl-Ali requested changes

2024-04-03 01:57 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/effects/EffLeash.java
> +				"\tsend \"&aYou leashed &2%event-entity%!\" to player"})
Quick correction to indentation, we use 1 indentation
```suggestion
@Examples({
	"on right click:",
		"\tleash event-entity to player",
		"\tsend \"&aYou leashed &2%event-entity%!\" to player"
})
```

2024-04-03 01:57 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/effects/EffLeash.java
> +@Description("Leash living entities to other entities. When trying to leash an Ender Dragon, Wither, Player, or a Bat, this effect will not work.")
I actually think spigot javadocs reference is useful here as the list may change later on
```suggestion
@Description("Leash living entities to other entities. When trying to leash an Ender Dragon, Wither, Player, or a Bat, this effect will not work. See <a href="https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#setLeashHolder(org.bukkit.entity.Entity)">Spigot's Javadocs for more info</a>.")
```

2024-04-03 13:00 UTC, Moderocky approved these changes

2024-04-04 09:59 UTC, AyhamAl-Ali approved these changes

2024-04-04 09:59 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/effects/EffLeash.java
> +		"\tsend \"&aYou leashed &2%event-entity%!\" to player"})
Just formatting stuff
```suggestion
@Description({
	"Leash living entities to other entities. When trying to leash an Ender Dragon, Wither, Player, or a Bat, this effect will not work.",
	"See <a href=\"https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#setLeashHolder(org.bukkit.entity.Entity)\">Spigot's Javadocs for more info</a>."
})
@Examples({
	"on right click:",
		"\tleash event-entity to player",
		"\tsend \"&aYou leashed &2%event-entity%!\" to player"
})
```

2024-04-04 16:49 UTC, AyhamAl-Ali approved these changes

2024-04-08 09:25 UTC, merged