Raise the minimum Java version to 11.
SkriptLang/Skript pull request #6557
Opened 2024-04-12 13:44 UTC by Moderocky

### Description

Raises Skript's compile target from Java 8 to Java 11.
Raises the test runners (and test server tasks) to use Java 11.

With 2.9 we are dropping support for Java 8. We will still support Minecraft versions 1.13.2+ with this Skript version, as long as they are running Java 11.

---
**Target Minecraft Versions:** any 
**Requirements:** Java 11 
**Related Issues:** #4625 & closes #1321

2024-04-12 20:10 UTC, AyhamAl-Ali approved these changes

2024-04-12 20:51 UTC, sovdeeth approved these changes

2024-04-13 06:59 UTC, Moderocky commented
This is probably to be the last thing merged before 2.9, in case anybody needs to make an unofficial Java 8 build by checking out the final commit.

Ironically, the first post-2.9 feature commit will probably be bumping the version again to Java 17.

2024-05-07 17:34 UTC, sovdeeth requested changes
https://github.com/SkriptLang/Skript/blob/b0052d25d6314c0cf7279d089aa4201bad23f713/README.md?plain=1#L23

change 1.8 to 1.12 (and resolve conflicts :) )

2024-05-07 19:06 UTC, sovdeeth approved these changes

2024-05-07 20:43 UTC, UnderscoreTud approved these changes

2024-05-08 19:45 UTC, APickledWalrus approved these changes

2024-05-13 04:14 UTC, TheLimeGlass commented
Make it Java 17. Java 11 doesn't benefit much. Other than less MC versions from 1.17

2024-06-30 19:06 UTC, merged