EffectCommandEvent: SkriptEvent support
SkriptLang/Skript pull request #6575
Opened 2024-04-16 07:40 UTC by NotSoDelayed

### Description
This PR adds support for Skript users to listen to EffectCommandEvent, and cleans up the involved classes.

Event values are:
- `event-sender` returns the sender (i.e. Player, Console)
- `[the] command` (from ExprCommand) returns the involved command

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-04-16 08:04 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/events/EvtEffectCommand.java
> +	}
I can see this implementation will definitely put into a good use!

2024-04-16 09:12 UTC, sovdeeth requested changes

2024-04-16 09:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtEffectCommand.java
> +	}
I'd vastly prefer an Enum, a Kleenean doesn't make much contextual sense to me. That said, you could simplify the logic a bit by using parse marks and the ordinal of the enum, if you wanted.

2024-04-16 09:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprCommand.java
> +		} else { // It's an EffectCommandEvent
best to make sure

2024-04-16 09:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtEffectCommand.java
> +		PLAYER("player ");
```suggestion
		CONSOLE("console"),
		PLAYER("player");
```
spacing should be handled by the caller.

2024-04-16 12:52 UTC, AyhamAl-Ali commented on src/main/java/ch/njol/skript/events/EvtEffectCommand.java
> +								"\tlog \"%sender%: %command%\" to file \"effectcommand.log\"")
```suggestion
							"\tlog \"%sender%: %command%\" to file \"effectcommands.log\"")
```

2024-04-19 06:42 UTC, NotSoDelayed commented
Closing, in favour of #6587

2024-04-19 06:42 UTC, closed without merging