Inventory Click event-value null check
SkriptLang/Skript pull request #6578
Opened 2024-04-17 16:07 UTC by Asleeepp

### Description

adds a null check to the event-slot of the inventory click event
I tested it, it just returns air when clicking outside the inventory, which should be fine (probably)

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6458

2024-04-17 16:08 UTC, Moderocky approved these changes

2024-04-17 16:09 UTC, Moderocky commented
Ah nuts I switched it to the wrong branch, give me a few minutes to fix the mess 😬

2024-04-17 16:10 UTC, Asleeepp commented
> Ah nuts I switched it to the wrong branch, give me a few minutes to fix the mess 😬

i was so confused when it suddenly switched to 23 commits

2024-04-17 16:14 UTC, Moderocky commented
Okay *now* I shall try to press the right button 🤣

2024-04-17 16:17 UTC, sovdeeth requested changes
wee woo wee woo brace police

2024-04-17 16:17 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				}
```suggestion
				if (invi == null)
					return null;
```

2024-04-17 16:21 UTC, sovdeeth approved these changes

2024-04-17 16:25 UTC, merged

2024-04-20 18:40 UTC, Blizzmond commented
where can I download the latest skript.jar that contains this fix?

2024-04-20 18:41 UTC, sovdeeth commented
checks tab -> java 17 -> artifacts -> download the zip

2024-04-20 18:44 UTC, Blizzmond commented
sorry im not too familiar with github, could you send a link or further guidiance? apologies.

2024-04-20 18:59 UTC, sovdeeth commented
checks tab
![image](https://github.com/SkriptLang/Skript/assets/10354869/ec831eab-08f0-4c4a-9997-e804625a53c9)
java 17
![image](https://github.com/SkriptLang/Skript/assets/10354869/539dee4a-b457-4b7a-a53c-97e2dec3862b)
artifacts -> download zip
![image](https://github.com/SkriptLang/Skript/assets/10354869/7095a869-8d57-467e-be57-996c5e0ac5b0)