Add .toString() to Script class
SkriptLang/Skript pull request #6582
Opened 2024-04-18 16:43 UTC by erenkarakal

### Description
Adds a .toString() method to the Script class.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #5834

2024-04-18 16:48 UTC, AyhamAl-Ali approved these changes
⚡

2024-04-19 16:19 UTC, sovdeeth commented
to sum up conversation on discord, I think the toString should hold more information about the Script object than just its file name, perhaps using the common structure of ``Script{field = value}``

2024-04-22 08:45 UTC, Moderocky requested changes
I don't really like this being the config file name.

2024-05-01 00:00 UTC, sovdeeth requested changes

2024-05-01 00:00 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprPlayerProtocolVersion.java
> +
You've polluted this branch, this pr shouldn't have viaversion stuff.

2024-05-11 01:51 UTC, TheLimeGlass commented on src/main/java/org/skriptlang/skript/lang/script/Script.java
> +		return this.getConfig().getFileName();
This should be the path string, or atleast the furthest minimum the /scripts/ directory parent as there can be different directories pertaining the same script file name.
```suggestion
		Config config = this.getConfig();
		return Optional.ofNullable(config::getPath).orElse(config::getFileName);
```

2024-05-11 01:52 UTC, TheLimeGlass commented on src/main/java/org/skriptlang/skript/lang/script/Script.java
> +		return this.getConfig().getFileName();
Would need Optional import if using suggestion.

2024-05-11 01:53 UTC, TheLimeGlass commented
> I don't really like this being the config file name.

Do you have an alternative suggestion or you don't like the pull request. This is blocking.

2024-05-30 07:38 UTC, Moderocky requested changes

2024-05-30 07:38 UTC, Moderocky commented on src/main/java/ch/njol/skript/expressions/ExprPlayerProtocolVersion.java
> +        }
Still needs the viaversion stuff removed.

2024-05-30 07:38 UTC, Moderocky commented on src/main/java/org/skriptlang/skript/lang/script/Script.java
> +		return this.getConfig().getFileName();
This should return something more like the IDE's default suggestion, e.g. 
```java
"Script[" +
	"config=" + config +
	", structures=" + structures +
	", suppressedWarnings=" + suppressedWarnings +
	", scriptData=" + scriptData +
	", eventHandlers=" + eventHandlers +
	']';
```

Script objects are holders for the structures and the script data, they aren't analogous to files. They also might not have a properly-linked config with a useful path if they were created by some addon at runtime. The Config toString should contain the path name, not the Script object.

2024-11-16 00:00 UTC, sovdeeth commented
Closing due to inactivity

2024-11-16 00:00 UTC, closed without merging