Replace SkriptParser ExprInfo Cache
SkriptLang/Skript pull request #6594
Opened 2024-04-19 21:09 UTC by APickledWalrus

### Description
This PR is a follow up to #6591. It aims to replace the ExprInfo cache with the usage of the existing, compiled SkriptPatterns (rather than creating csubstrings). This should help to reduce any performance impact.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-04-20 09:05 UTC, Moderocky requested changes

2024-04-20 09:05 UTC, Moderocky commented on src/main/java/ch/njol/skript/patterns/SkriptPattern.java
> +				//noinspection unchecked - it is checked with isInstance
You can use the cast method for things like this, by the way.

2024-04-20 09:05 UTC, Moderocky commented on src/main/java/ch/njol/skript/lang/SkriptParser.java
> +							List<TypePatternElement> types = parseResult.source.getElements(TypePatternElement.class);
Do we have to iterate to find TypePatternElements here? Could they be referenced separately since they're special?

2024-04-23 08:40 UTC, Moderocky approved these changes

2024-04-23 09:24 UTC, sovdeeth commented on src/main/java/ch/njol/skript/patterns/SkriptPattern.java
> +			}
```suggestion
			if (types == null)
				types = ImmutableList.copyOf(getElements(TypePatternElement.class, first, new ArrayList<>()));
```

2024-04-23 09:33 UTC, merged