Add getName() and getWorld() support to regions
SkriptLang/Skript pull request #6657
Opened 2024-05-07 21:11 UTC by aabssmc

### Description

Added region support to ExprName and ExprWorld so you don't have to do `if region at player contains "region name"` or  `if region at player contains "world name"` and instead you can do `if name of region at player is "region name"` and `if world of region at player is "world name"`.
Same with world
---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-05-07 21:12 UTC, Asleeepp commented
I don't think they would accept this, iirc they are trying to get rid of worldguard support in favor of skript-worldguard. its up to the team though i guess

2024-05-07 21:12 UTC, sovdeeth commented
Region support is being phased out of Skript and being replaced by skript-worldguard (eventually), so I'd suggest PR-ing this to skript-worldguard instead.

2024-05-07 21:13 UTC, aabssmc commented
😔

> Region support is being phased out of Skript and being replaced by skript-worldguard (eventually), so I'd suggest PR-ing this to skript-worldguard instead.

😔

2024-05-07 22:21 UTC, sovdeeth requested changes

2024-05-07 22:21 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprName.java
> +		register(ExprName.class, String.class, "(1¦name[s]|2¦(display|nick|chat|custom)[ ]name[s])", "offlineplayers/entities/blocks/itemtypes/inventories/slots/worlds/regions"
if this was added, it'd need to check for worldguard before allowing region.
another reason why thing should be in skript-worldguard instead

2024-08-20 08:43 UTC, Moderocky reviewed
Region support is moving to skript-worldguard.

2024-11-16 00:12 UTC, closed without merging

2024-11-16 00:12 UTC, sovdeeth commented
Closing due to inactivity