Basic Experience API Enhancement
SkriptLang/Skript pull request #6661
Opened 2024-05-08 08:15 UTC by NotSoDelayed

### Description
This PR provides light enhancements to Skript's Experience API with:
- Allowing Experience object into ExprTotalExperience (`add 10 xp to player' total xp`)
- Add changers to Experience objects (`set {-xp} to 10 xp`, `add 10 xp to {-xp}`; results `20 xp`)
*and top it off with some dusting in Experience class.*

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #6649

2024-05-08 11:41 UTC, NotSoDelayed commented
Tests will be added.

2024-05-08 16:36 UTC, sovdeeth requested changes

2024-05-08 16:36 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
> +							xp.setInternalXP(xp.getInternalXP() + change);
needs bound checking

2024-05-13 19:45 UTC, sovdeeth approved these changes
Some tests with an entity's xp would be nice, if we don't already have any.

2024-05-20 11:25 UTC, NotSoDelayed commented
> Some tests with an entity's xp would be nice, if we don't already have any.

I only recalled Player have XP. How does one do it with non-player entities?

2024-05-29 08:23 UTC, sovdeeth commented
> > Some tests with an entity's xp would be nice, if we don't already have any.
> 
> I only recalled Player have XP. How does one do it with non-player entities?

ExperienceOrb, no?

2024-08-20 08:45 UTC, Moderocky approved these changes

2024-10-13 04:14 UTC, NotSoDelayed commented
Closing due to stale progress

2024-10-13 04:14 UTC, closed without merging