Deprecate outdated utils/synchronized reference
SkriptLang/Skript pull request #6671
Opened 2024-05-08 12:38 UTC by kiip1

2024-05-08 15:55 UTC, Moderocky reviewed
This looks correct but I feel like it would be good for somebody to test it works first.

2024-12-17 19:11 UTC, APickledWalrus requested changes
If this happens to get taken over, I just have a function documentation-related thoughts. I am not a huge fan of the VectorMath changes, as there is a lot of method duplication going on now.

2024-12-17 19:11 UTC, APickledWalrus commented on src/main/java/ch/njol/util/Predicate.java
>   *
```suggestion
 * @deprecated Use {@link java.util.function.Predicate}
```

2024-12-17 19:11 UTC, APickledWalrus commented on src/main/java/ch/njol/util/Setter.java
> +@Deprecated
```suggestion
/**
 * Use {@link Consumer}
 */
@Deprecated
```

2024-12-20 15:52 UTC, APickledWalrus commented
Given this is rather outdated, and seems to mostly be duplicated/featured in https://github.com/SkriptLang/Skript/pull/6670, I will be closing it.

2024-12-20 15:52 UTC, closed without merging