Condition Slot has Space for Item
SkriptLang/Skript pull request #6677
Opened 2024-05-09 09:33 UTC by NotSoDelayed

### Description
This PR adds a condition to check for whether a slot has space for an item.

Tests dedicated to CondCanHold.java is also added.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #6256

2024-06-10 15:53 UTC, sovdeeth requested changes

2024-06-10 15:53 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondCanHold.java
> +				"%slots% (can(no|')t hold|(ha(s|ve) not|ha(s|ve)n't|do[es]n't have) [enough] space (for|to hold)) %itemtype%");
why are the patterns duplicated? just use %slots/inventories%

2024-06-10 15:53 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondCanHold.java
> +	public boolean check(Event event) {
the slot and inventory logic could be separated into helper methods.

2024-10-03 07:16 UTC, NotSoDelayed commented
Closing due to stale progress

2024-10-03 07:16 UTC, closed without merging