Context Switch Enhancements
SkriptLang/Skript pull request #6699
Opened 2024-05-15 22:35 UTC by APickledWalrus

### Description
This PR introduces some new features and makes some changes to provide clarity around interacting with the ParserInstance and managing context-switches.

### ParserInstance Backups

Support for creating and restoring a backup of a ParserInstance has been introduced. A ParserInstance backup contains a copy of a ParserInstance's data, excluding anything related to logging. I have also added a method to reset a ParserInstance to its default state. That is, it clears everything out except the current script and any logging related information (this is essentially the state a ParserInstance is in when first loading a script).

### SecConditional/ParseIf Changes

I have replaced the usage of SkriptParseEvent with more standard ContextlessEvent. I deleted the class outright, as it was marked for internal use (and is no longer internally used). I have also removed the changing of the current structure. There is no reason that this needs to change, and it opens up parse if conditional to syntax that is only restricted by Structure. Just changing the current event is fine here, as we are only *removing* context, not adding any.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-05-15 23:39 UTC, UnderscoreTud requested changes

2024-05-15 23:39 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/lang/Section.java
> +		Backup parserSnapshot = parser.backup();
Shouldn't this be renamed to `parserBackup`

2024-05-15 23:39 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
> +			this.dataMap.putAll(parser.dataMap);
```suggestion
			this.dataMap = new HashMap<>(parser.dataMap);
```

2024-05-15 23:39 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
> +			this.currentSections.addAll(parser.currentSections);
```suggestion
			this.currentSections = new ArrayList<>(parser.currentSections);
```

2024-05-29 08:00 UTC, sovdeeth approved these changes

2024-05-29 08:02 UTC, UnderscoreTud approved these changes

2024-05-29 15:00 UTC, Moderocky approved these changes

2024-05-31 18:36 UTC, merged