Allow any script in `using` condition.
SkriptLang/Skript pull request #6706
Opened 2024-05-18 21:32 UTC by Moderocky

### Description

The original purpose of the `is using` condition was to be able to test other scripts. Initially, this wasn't really possible (so it just supported the current script) but with script references it is.

Based on #6702, the only actual change is in `ch.njol.skript.conditions.CondIsUsingFeature`.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** requires #6702

2024-05-29 08:11 UTC, sovdeeth approved these changes

2024-11-20 01:31 UTC, APickledWalrus requested changes

2024-11-20 01:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondIsUsingFeature.java
> +	private Expression<Script> script;
Should be `scripts`

2024-11-21 10:29 UTC, Efnilite approved these changes

2024-11-22 15:41 UTC, APickledWalrus approved these changes
Nice work

2024-11-23 07:54 UTC, merged