User configs
SkriptLang/Skript pull request #6720
Opened 2024-05-24 19:51 UTC by Moderocky

### Description
User-provided config files.

I was inspired by a conversation with Walrus yesterday around the lack of config stuff in Skript when they're normally such a big part of setting up a server.
We talked a lot about safety (I suggested registration, he suggested storing them in a `/configs/` directory) and this was the basic layout I came up with.

<details>
<summary><h3>Additions</h3></summary>

This adds:
    - Config registration structure
    - Config get expression
    - Changers for nodes
    - Config reloading & saving via `EffScriptFile`

A script-maker can register their own config file within a script. They are then able to read (and write) this config, in order to take input from a user in a more sanitary way than in-script options.
This also means users don't have to download and learn an unsafe file addon in order to make a config file.

It's primarily aimed at people publishing their resources, but it's also potentially a better alternative to the suggestion in historic issue #2028, since it allows common values to be collated in one safe place and shared between scripts.

There is a heavy focus on resource safety.

</details>

<details>
<summary><h3>Syntax</h3></summary>

```
register config %*string%

[the] config [named] %*string%
(load|reload|unload|save) %config%
```

</details>

<details>
<summary><h3>What does this actually do?</h3></summary>

It allows users to register a config file used by their script.
This file is **linked** to the script: they are loaded, reloaded and discarded together.
A config can be registered by multiple scripts.

Config values can be edited via the node tree.

```applescript
register config "my cool config" # we register here

on load:
    set {config} to the config named "my cool config"
    # there's actually no point setting a variable since `config named x` config literals are handled during parse but i thought it looked cooler in my amazing example

on join:
    set {_node} to node "welcome message" in {config}
    broadcast the text value of {_node}

    set {_node} to node "join item" in {config}
    give player (item type value of {_type})
    

command /reset the config:
    trigger:
        set the text value at "welcome message" in {config} to "Welcome!"
        set the number value at "maximum players" in {config} to 15
        set the text value at "message.prefix" in {config} to "[message]"
        set the color value at "message.color" in {config} to red
        save {config}
```

</details>

<details>
<summary><h3>Other Notes</h3></summary>

I considered opening this up to other `.sk` files, since it wouldn't be a huge stretch to allow users to read and write general data files in the same way.

That said, I was concerned about not being able to manage the opening/closing of unknown files safely and decided that was better left to an addon or a future project.

For anybody wishing to implement that themselves, you'd just need to return a `Config` or even a `Node` from some expression.

</details>

---

This is part of a series of linked stages around config and script management.

<img width="1300" alt="image" src="https://github.com/SkriptLang/Skript/assets/14147477/20e12562-5b4e-4c60-8e90-8d2d3be5ad22">

---
**Related Issues:** requires #6718, requires #6702, requires #6719, fixes #2028

2024-11-22 18:24 UTC, APickledWalrus requested changes
Feel free to re-request me once conflicts are resolved/branch updated

2024-12-26 22:12 UTC, sovdeeth requested changes

2024-12-26 22:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/config/ConfigRegistry.java
> + */
```suggestion
```

2024-12-26 22:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/config/SharedConfig.java
> + */
```suggestion
```

2024-12-26 22:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/config/UnlinkedNode.java
> + */
```suggestion
```

2024-12-26 22:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/structures/StructRegisterConfig.java
> + */
```suggestion
```

2024-12-27 08:11 UTC, Moderocky commented on src/main/java/ch/njol/skript/config/NodeNavigator.java
> + */
```suggestion
```

2024-12-27 23:25 UTC, sovdeeth approved these changes

2025-08-30 07:34 UTC, closed without merging