Improve new line pattern.
SkriptLang/Skript pull request #6733
Opened 2024-05-28 11:29 UTC by Moderocky

### Description

The current pattern for the new line literal is `n[ew]l[ine]` or `line[ ]break`.
A keen-eyed observer might spot that this means `nline` and `newl` are both valid options, but `new line` isn't, which seems a little silly.

I've changed it to `nl`, `new[ ]line` or `line[ ]break`.

Since this is technically a breaking change (for all the die-hard `newl` fans out there) I'm entering it for `feature` instead of `patch`.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-05-29 13:07 UTC, sovdeeth requested changes

2024-05-29 13:07 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/LitNewLine.java
> +	public boolean init(final Expression<?>[] expressions, final int matchedPattern, final Kleenean isDelayed, final SkriptParser.ParseResult result) {
```suggestion
	public boolean init(Expression<?>[] expressions, int matchedPattern, Kleenean isDelayed, ParseResult result) {
```

2024-05-30 07:52 UTC, sovdeeth approved these changes

2024-05-31 18:29 UTC, APickledWalrus approved these changes

2024-07-01 13:25 UTC, merged