Improve variable names in EffChange
SkriptLang/Skript pull request #6779
Opened 2024-06-10 19:27 UTC by Pikachu920

### Description
Adds some more descriptive variable names to EffChange. It also swaps complicated ternaries for if/else instead.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-06-10 21:03 UTC, Moderocky requested changes

2024-06-10 21:03 UTC, Moderocky commented on src/main/java/ch/njol/skript/effects/EffChange.java
>  				}
Maybe it's just github UI messing up but it looks like we have two ifs nested in here and neither of them have an `else`, maybe they could be combined or tidied up somehow?

2024-06-10 21:03 UTC, Moderocky commented on src/main/java/ch/njol/skript/effects/EffChange.java
> +		assert deltaValuesExpression != null;
Won't this cause problems in test mode if it ever gets stringified? For `DELETE` and `RESET` it is null, right? (If not the field probably shouldn't be `@Nullable` so we won't need this assertion)

2024-06-28 15:44 UTC, sovdeeth approved these changes
other than kenzie things, seems good

2024-08-19 20:15 UTC, UnderscoreTud approved these changes
Could you remove all occurrences of `ErrorQuality.SEMANTIC_ERROR` since it's already the default?

2025-04-07 22:12 UTC, sovdeeth commented
@Pikachu920 do you intend to finish this?

2025-05-19 19:02 UTC, closed without merging