Fixed SimpleExpression#getArray() throwing an error when length of values array is 0
SkriptLang/Skript pull request #6822
Opened 2024-06-27 11:39 UTC by TFSMads

### Description
I fixed an issue where casting empty array throws an error

---
**Target Minecraft Versions:** any 
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6817

2024-06-28 15:26 UTC, sovdeeth approved these changes

2024-06-30 04:35 UTC, UnderscoreTud commented
I think it may be better to check the class of the array. There's no reason to create a new array instance reflectively if the given array is of the correct type

2024-08-17 16:16 UTC, Moderocky approved these changes

2024-08-17 16:31 UTC, APickledWalrus commented
I also question whether this is something we should be doing at all. Really, this is due to ExprXOf violating its contract. When `amount` is null, it returns an empty Object array. However, its return type is not guaranteed to be Object (which is what is occurring here). I think we are better off ensuring that all syntax are returning arrays based on their return type rather than cleaning it up for them when there is an issue.

2024-08-17 16:32 UTC, Moderocky commented
> I think we are better off ensuring that all syntax are returning arrays based on their return type rather than cleaning it up for them when there is an issue.

I completely agree in principle and I spent a while trying to fix all of these bad returns in a previous PR, but what I worry is that there is no easy way to hold addons, etc. to this contract, so it's likely bad API use will slip through the net, and we either need to catch that at the first opportunity and give a proper error for it (so people know to fix it) or we need to try and accommodate it in a reasonable way, so that it doesn't error where possible.

2024-08-17 16:44 UTC, Pikachu920 commented
> > I think we are better off ensuring that all syntax are returning arrays based on their return type rather than cleaning it up for them when there is an issue.
> 
> I completely agree in principle and I spent a while trying to fix all of these bad returns in a previous PR, but what I worry is that there is no easy way to hold addons, etc. to this contract, so it's likely bad API use will slip through the net, and we either need to catch that at the first opportunity and give a proper error for it (so people know to fix it) or we need to try and accommodate it in a reasonable way, so that it doesn't error where possible.

I would be in favor of an error

2024-08-17 16:47 UTC, Moderocky commented
> I would be in favor of an error

That's fine, do you think that should be done in this PR or its own? Also, where do you think is the best place to test for the array being of the wrong (unreported) type?

2024-12-16 19:21 UTC, APickledWalrus requested changes
Based on the discussion above, I would be in favor of (at most) catching this and erroring about an API violation. I'm not sure it's necessary for us to cover every misuse of the API (including this one), in fact I would prefer leaving the method as-is, but I understand the concern.

2025-01-18 20:54 UTC, Moderocky commented
Closing. We probably don't want to handle this issue in this method, it's the syntax's responsibility to follow the contract.

2025-01-18 20:54 UTC, closed without merging