Added holder instanceof DoubleChest check to converter
SkriptLang/Skript pull request #6823
Opened 2024-06-27 12:39 UTC by TFSMads

### Description
I have added a converter check for DoubleChest. Aswell as a regression test.

---
**Target Minecraft Versions:** any
**Requirements:** none 
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6811

2024-06-27 13:08 UTC, sovdeeth requested changes

2024-06-27 13:08 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
> +						: null;
This should be normal if statements instead of a massive ternary.

2024-06-27 13:08 UTC, sovdeeth commented on src/test/skript/tests/regressions/6811-inventory-holder-location-doublechest.sk
> +    assert {_b-loc::*} contains {_a-loc} with "holder location of double chest differs from block location"
```suggestion
    assert {_b-loc::*} contains {_a-loc} with "holder location of double chest differs from block location"

```

2024-06-27 13:08 UTC, sovdeeth commented on src/test/skript/tests/regressions/6811-inventory-holder-location-doublechest.sk
> +	broadcast {_prev::*}
```suggestion
```

2024-06-27 13:08 UTC, sovdeeth commented on src/test/skript/tests/regressions/6811-inventory-holder-location-doublechest.sk
> +	set {_prev::2} to type of block at {_b::1}
```suggestion
	set {_prev::2} to type of block at {_b::2}
```

2024-06-28 15:23 UTC, sovdeeth requested changes
indentation still broken in tests

2024-06-29 22:03 UTC, sovdeeth approved these changes

2024-06-30 04:49 UTC, UnderscoreTud approved these changes

2024-06-30 04:49 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
> +			if(holder instanceof DoubleChest) {
```suggestion
			if (holder instanceof DoubleChest) {
```

2024-06-30 04:49 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
> +			}
```suggestion
				DoubleChest doubleChest = (DoubleChest) holder;
				if (doubleChest.getLeftSide() != null) {
					return BlockUtils.getLocation(((BlockState) doubleChest.getLeftSide()).getBlock());
				} else if (((DoubleChest) holder).getRightSide() != null) {
					return BlockUtils.getLocation(((BlockState) doubleChest.getRightSide()).getBlock());
				}
			}
```

2024-07-01 13:08 UTC, merged