Exposes 'load default aliases' config option and removes hardcoded alias dependencies
SkriptLang/Skript pull request #6834
Opened 2024-06-30 18:15 UTC by sovdeeth

### Description

These changes are aimed around giving users the ability to disable aliases they don't want to use, via disabling the default ones and using just the alias folder instead. 

Skript had hard dependencies on many aliases that have now been replaced with Materials or Tag references.

This also fixes some issues with torch placement in 1.19+, as well as a bug with the block setter's flags always being true, and makes sure aliases are always generated for all Materials.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-06-30 20:31 UTC, APickledWalrus requested changes

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
> +	private static final boolean HAS_FENCE_TAGS = !Skript.isRunningMinecraft(1,14);
```suggestion
	private static final boolean HAS_FENCE_TAGS = !Skript.isRunningMinecraft(1, 14);
```

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
> +			return block.getBlockData() instanceof Fence || block.getBlockData() instanceof Wall;
Is there a Fence Gate blockdata?

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
> +				} else if (Material.WALL_TORCH == type) {
```suggestion
				} else if (type == Material.WALL_TORCH) {
```

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/entity/BoatChestData.java
> +		else if (spruceBoat == type)
```suggestion
		else if (type == spruceBoat)
```
and for the rest 🙂

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/entity/BoatData.java
> +		else if (Material.SPRUCE_BOAT == type)
```suggestion
		else if (type == Material.SPRUCE_BOAT)
```
and for the rest 🙂

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/entity/BoatChestData.java
> +			oakBoat = Material.getMaterial("OAK_CHEST_BOAT");
it should be safe to reference the enum values directly since registration is locked behind this check

2024-06-30 20:31 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprSpawnerType.java
> +		if (block.getType() != Material.SPAWNER)
Would likely be better to use an instanceof CreatureSpawner state check

2024-07-01 08:04 UTC, Moderocky approved these changes

2024-07-01 16:35 UTC, APickledWalrus approved these changes

2024-07-01 16:35 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprSpawnerType.java
> +			if (b.getType() != Material.SPAWNER)
```suggestion
			if (!(b.getState() instanceof CreatureSpawner))
```

2024-07-01 20:38 UTC, merged