EffBan - add option to kick
SkriptLang/Skript pull request #6835
Opened 2024-06-30 18:43 UTC by ShaneBeee

### Description
This PR adds an option to kick when banning players.
It's a common misconception that people assuming banning kicks the player as well.
This helps eliminate the need for 2 lines

Did a little code cleanup too.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-06-30 18:45 UTC, sovdeeth requested changes

2024-06-30 18:45 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffBan.java
> +						Bukkit.getBanList(BanList.Type.NAME).addBan(player.getName(), reason, expires, source); // FIXME [UUID] ban UUID
ban via uuid?

2024-06-30 18:45 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffBan.java
> +		return ip + ban + andKick + players + reason + time;
good spot for a StringBuilder

2024-06-30 19:01 UTC, sovdeeth approved these changes

2024-07-01 08:01 UTC, Moderocky approved these changes

2024-07-01 12:42 UTC, merged