Adds some more taming syntax
SkriptLang/Skript pull request #6850
Opened 2024-07-02 03:34 UTC by cheeezburga

This PR adds an effect to tame an entity and a condition to check if an entity is tamed.

2024-07-02 04:55 UTC, NotSoDelayed requested changes
Add missing Skript docs

2024-07-02 14:29 UTC, NotSoDelayed requested changes

2024-07-02 14:29 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/conditions/CondIsTamed.java
> +@Name("Is tamed")
```suggestion
@Name("Is Tamed")
```

2024-07-02 14:29 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/conditions/CondIsTamed.java
> +	"tame {_horse} if {_horse} is untamed"})
```suggestion
@Examples({
    "send true if {_horse} is tamed",
	"tame {_horse} if {_horse} is untamed"
})
```
Although im not sure if we would use Skript's ternary expression as apart of the examples, just saying.

2024-07-02 14:29 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/effects/EffTame.java
> +	"untame {_horse}"})
```suggestion
@Examples({
    "tame {_horse}",
	"untame {_horse}"
})
```

2024-07-02 14:29 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/conditions/CondIsTamed.java
> +}
```suggestion
	}

}
```
Skript's standardised formatting

2024-07-02 14:29 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/effects/EffTame.java
> +	@Override
```suggestion
	@Override
	@SuppressWarnings("unchecked")
```

2024-07-02 14:29 UTC, NotSoDelayed commented on src/test/skript/tests/syntaxes/conditions/CondIsTamed.sk
> +	kill value within {_z}
```suggestion
	kill value within {_z}

```
Skript's standardised formatting

2024-07-03 11:29 UTC, cheeezburga commented on src/test/skript/tests/syntaxes/conditions/CondIsTamed.sk
> +	kill value within {_z}
Deleting throws an error: `value within {_e} (and {_z}) cannot be deleted`. Isn't killing fine for this anyway? The values in those variables are never gonna not be horse and zombie.

2024-07-03 16:20 UTC, APickledWalrus commented on src/test/skript/tests/syntaxes/conditions/CondIsTamed.sk
> +	kill value within {_z}
Try doing `delete entity within {_e}`

2024-07-04 05:42 UTC, NotSoDelayed requested changes

2024-07-04 05:42 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/effects/EffTame.java
> +	}
```suggestion
	}

```
Missed one for Skript’s standardised formatting

2024-07-04 07:20 UTC, NotSoDelayed approved these changes

2024-07-12 22:52 UTC, sovdeeth approved these changes

2024-07-14 04:03 UTC, APickledWalrus approved these changes

2024-07-21 04:33 UTC, TheLimeGlass requested changes
Looking good pull request

2024-07-21 04:33 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/conditions/CondIsTamed.java
> +		if (entity instanceof Tameable)
`return entity instance of Tameable && ((Tameable) entity).isTamed();`

2024-08-15 00:23 UTC, merged