Update CondIsCharged
SkriptLang/Skript pull request #6860
Opened 2024-07-04 02:17 UTC by cheeezburga

This PR adds wither skulls to the `is charged` condition.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-07-04 15:17 UTC, Pikachu920 commented
can you please add tests?

2024-07-12 23:09 UTC, sovdeeth requested changes

2024-07-12 23:09 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffCharge.java
> +	"\tcharge the event-entity"
```suggestion
		"\tcharge the event-entity"
```

2024-07-12 23:09 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffCharge.java
> +@Name("Charge")
```suggestion
@Name("Charge Entity")
```

2024-07-18 06:12 UTC, sovdeeth approved these changes

2024-07-18 06:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffCharge.java
>  import org.eclipse.jdt.annotation.Nullable;
jetbrains nullable!

2024-07-21 04:39 UTC, TheLimeGlass approved these changes

2024-07-21 04:39 UTC, TheLimeGlass commented on src/test/skript/tests/syntaxes/conditions/CondIsCharged.sk
> +	spawn a creeper at (spawn of world "world"):
You can also use event-location in the case that we change the location for some reason.

2024-08-17 16:27 UTC, Moderocky approved these changes

2024-08-30 10:58 UTC, merged