Fix bugs with Timespan#getAs
SkriptLang/Skript pull request #6909
Opened 2024-07-16 16:00 UTC by sovdeeth

### Description

Remove rounding from getAs (it should truncate anyway) to avoid limiting as int max value. Fix bug where millis was multiplied instead of divided.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6908

2024-07-16 16:56 UTC, UnderscoreTud approved these changes

2024-07-16 16:59 UTC, APickledWalrus approved these changes

2024-07-16 23:01 UTC, TheLimeGlass requested changes
Line 213 needs the Javadoc fixed aswell
```diff
-@deprecated Use {@link Timespan#Timespan(TimePeriod, long)}
+@deprecated Use {@link #Timespan(TimePeriod, long)}
```

2024-07-16 23:03 UTC, sovdeeth commented
> Line 213 needs the Javadoc fixed aswell
> 
> ```diff
> -@deprecated Use {@link Timespan#Timespan(TimePeriod, long)}
> +@deprecated Use {@link #Timespan(TimePeriod, long)}
> ```

Is this an issue? Seems fine either way to me.

2024-07-16 23:15 UTC, TheLimeGlass commented
> 
> Is this an issue? Seems fine either way to me.

There is no subclass called `new Timespan.Timespan(TimePeriod, long)`

2024-07-16 23:17 UTC, sovdeeth commented
> > Is this an issue? Seems fine either way to me.
> 
> There is no subclass called `new Timespan.Timespan(TimePeriod, long)`

No, that's just the way to reference the constructor. It appear fine on javadocs:
![image](https://github.com/user-attachments/assets/8d0df4dc-6088-4569-9335-052070966d33)

2024-07-16 23:31 UTC, TheLimeGlass commented
> 
> No, that's just the way to reference the constructor. It appear fine on javadocs: ![image](https://private-user-images.githubusercontent.com/10354869/349300008-8d0df4dc-6088-4569-9335-052070966d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzI5NDMsIm5iZiI6MTcyMTE3MjY0MywicGF0aCI6Ii8xMDM1NDg2OS8zNDkzMDAwMDgtOGQwZGY0ZGMtNjA4OC00NTY5LTkzMzUtMDUyMDcwOTY2ZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIzMzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMTRhNzBiNDBhOTY3OGNjYjlhMjU4MjQ1MTc4NTA2YzJmM2YwMmY5YmU2MWRhMzg3NGEyYjFmODllM2NhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1aInMcQO_o6OLlyiSSYfRDoSd-aFfG0YgNM-nGIiMa0) ![image](https://private-user-images.githubusercontent.com/10354869/349300095-604c8e11-2815-4dc9-876c-d5f05881b0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzI5NDMsIm5iZiI6MTcyMTE3MjY0MywicGF0aCI6Ii8xMDM1NDg2OS8zNDkzMDAwOTUtNjA0YzhlMTEtMjgxNS00ZGM5LTg3NmMtZDVmMDU4ODFiMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIzMzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNjk3MzllMmQwYWMxNGQyZGU3M2ExNzA1ZjZjNTY3NzI1OWUwNzlkYjg5ZDM3MWU0YzliZTNiMGRlODgxMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjB-_mx23z69CNQ3_xb24o_DoUKdWC5hvFzPxZFuPwA)

VSCode using IntelliSense and Eclipse state otherwise
<img width="577" alt="Untitled" src="https://github.com/user-attachments/assets/ab74ab40-04a6-413c-bbf4-1fb181dd131c">

2024-07-16 23:50 UTC, sovdeeth commented
> > No, that's just the way to reference the constructor. It appear fine on javadocs: ![image](https://private-user-images.githubusercontent.com/10354869/349300008-8d0df4dc-6088-4569-9335-052070966d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzI5NDMsIm5iZiI6MTcyMTE3MjY0MywicGF0aCI6Ii8xMDM1NDg2OS8zNDkzMDAwMDgtOGQwZGY0ZGMtNjA4OC00NTY5LTkzMzUtMDUyMDcwOTY2ZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIzMzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMTRhNzBiNDBhOTY3OGNjYjlhMjU4MjQ1MTc4NTA2YzJmM2YwMmY5YmU2MWRhMzg3NGEyYjFmODllM2NhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1aInMcQO_o6OLlyiSSYfRDoSd-aFfG0YgNM-nGIiMa0) ![image](https://private-user-images.githubusercontent.com/10354869/349300095-604c8e11-2815-4dc9-876c-d5f05881b0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzI5NDMsIm5iZiI6MTcyMTE3MjY0MywicGF0aCI6Ii8xMDM1NDg2OS8zNDkzMDAwOTUtNjA0YzhlMTEtMjgxNS00ZGM5LTg3NmMtZDVmMDU4ODFiMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIzMzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNjk3MzllMmQwYWMxNGQyZGU3M2ExNzA1ZjZjNTY3NzI1OWUwNzlkYjg5ZDM3MWU0YzliZTNiMGRlODgxMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjB-_mx23z69CNQ3_xb24o_DoUKdWC5hvFzPxZFuPwA)
> 
> VSCode using IntelliSense and Eclipse state otherwise <img alt="Untitled" width="577" src="https://private-user-images.githubusercontent.com/16087552/349302207-ab74ab40-04a6-413c-bbf4-1fb181dd131c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzM5MDYsIm5iZiI6MTcyMTE3MzYwNiwicGF0aCI6Ii8xNjA4NzU1Mi8zNDkzMDIyMDctYWI3NGFiNDAtMDRhNi00MTNjLWJiZjQtMWZiMTgxZGQxMzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIzNDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMGRmOGVmMTIwZmZjYTM3MGUyMDExODM4M2U0OWM1NzRhMzE0OTY1OTg5YTMzMDM4MWM0NjAzOTBlMjE2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PD-wwCt7ViWn1wYUVOca3kWdYGSMmrkEz44r8DzlaGo">

Seems like an issue with those extensions, then, because it's valid in java docs specifications.
![image](https://github.com/user-attachments/assets/daeeb936-9fb0-4e27-b10c-dc8829080e77)
from <https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#tag>

2024-07-17 00:46 UTC, TheLimeGlass commented
> 
> Seems like an issue with those extensions, then, because it's valid in java docs specifications. ![image](https://private-user-images.githubusercontent.com/10354869/349307434-daeeb936-9fb0-4e27-b10c-dc8829080e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzc0NDgsIm5iZiI6MTcyMTE3NzE0OCwicGF0aCI6Ii8xMDM1NDg2OS8zNDkzMDc0MzQtZGFlZWI5MzYtOWZiMC00ZTI3LWIxMGMtZGM4ODI5MDgwZTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAwNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MzhjMmZmNjBkYmFmNzY1ZjgwYTYzNmNlYjNiZWY0ZTQyNGJiZTIyMGZiMTM0MjBmZDA1ODVlMmFjMzYxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XFkDSrBETETXtg3_oKF8xi2-7ibPdEbtH-KuOB5pJpg) from https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#tag

Applying my suggestion solves the issue for IDE's and the Javadoc

2024-07-17 00:48 UTC, sovdeeth commented
> > Seems like an issue with those extensions, then, because it's valid in java docs specifications. ![image](https://private-user-images.githubusercontent.com/10354869/349307434-daeeb936-9fb0-4e27-b10c-dc8829080e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzc0NDgsIm5iZiI6MTcyMTE3NzE0OCwicGF0aCI6Ii8xMDM1NDg2OS8zNDkzMDc0MzQtZGFlZWI5MzYtOWZiMC00ZTI3LWIxMGMtZGM4ODI5MDgwZTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAwNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MzhjMmZmNjBkYmFmNzY1ZjgwYTYzNmNlYjNiZWY0ZTQyNGJiZTIyMGZiMTM0MjBmZDA1ODVlMmFjMzYxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XFkDSrBETETXtg3_oKF8xi2-7ibPdEbtH-KuOB5pJpg) from https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#tag
> 
> Applying my suggestion solves the issue for IDE's and the Javadoc

I can make the change but you should probably report that as a bug and/or get a better extension/IDE, since it displays fine on intellij too

2024-07-17 01:13 UTC, TheLimeGlass approved these changes

2024-07-18 06:03 UTC, merged