Add trailing empty string ignoring and tests to ExprJoinSplit
SkriptLang/Skript pull request #6930
Opened 2024-07-19 21:12 UTC by Efnilite

### Description
Adds option to ignore trailing empty strings if the split identifier is at the end of the string and adds tests for ExprJoinSplit.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6929

2024-07-19 23:26 UTC, sovdeeth requested changes

2024-07-19 23:26 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
> +			(regex ? "" : "(case sensitive: " + caseSensitivity + ")");
toString needs to reflect whether the new option was used or not

2024-07-20 23:33 UTC, sovdeeth approved these changes

2024-07-21 03:17 UTC, TheLimeGlass approved these changes
This should be the standard honestly. A trim syntax would be good aswell.

2024-07-21 16:21 UTC, Efnilite commented
> This should be the standard honestly. A seperate trim syntax would be good aswell.

agreed, but would probably break backwards compatibility

2024-07-21 18:01 UTC, UnderscoreTud approved these changes

2024-07-21 18:01 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
> +			return strings[0].split(regex ? delimiter : (caseSensitivity ? "" : "(?i)") + Pattern.quote(delimiter),
The method call is getting long, reassign `delimiter` above it if `regex` is false

2024-07-24 17:26 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
> +			"regex %string% split (at|using|by) [[the] delimiter] %string% [trailing:without [the] trailing [empty] string]");
it might be good to allow `text` in place of `string` as `text` is commonly used in other places

2024-08-15 00:15 UTC, merged