ExprPrefixSuffix Cleanup
SkriptLang/Skript pull request #6970
Opened 2024-08-10 20:41 UTC by Asleeepp

### Description

I've cleaned up some bits in ExprPrefixSuffix, by adding a CompleteableFuture.runAsync, similar to ExprGroup, to prevent any possible stack traces from LuckPerms, i've also added a reset/delete changer. 

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-08-11 05:43 UTC, sovdeeth requested changes
you should fix the method ordering while you're here, as well as switch to Jetbrains @Nullable, remove finals from method params, and rename variables to reasonable names,

2024-08-11 16:02 UTC, UnderscoreTud requested changes
Could add some tests

2024-08-11 16:02 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
>  	}
Did you test this? You never updated the `acceptChange` method. The reset/delete modes aren't valid

2024-08-11 16:02 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +				}
Use the newer switch syntax

2024-08-11 16:02 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +							VaultHook.chat.setPlayerSuffix(player, (String) delta[0]);
```suggestion
						if (prefix) {
							VaultHook.chat.setPlayerPrefix(player, (String) delta[0]);
						} else {
							VaultHook.chat.setPlayerSuffix(player, (String) delta[0]);
						}
```

2024-08-11 16:02 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +							VaultHook.chat.setPlayerSuffix(player, null);
```suggestion
						if (prefix) {
							VaultHook.chat.setPlayerPrefix(player, null);
						} else {
							VaultHook.chat.setPlayerSuffix(player, null);
						}
```

2024-08-11 17:59 UTC, Asleeepp commented
> Could add some tests

not sure how I do that for this, sorry 😬

2024-08-12 14:38 UTC, UnderscoreTud commented
> > Could add some tests
> 
> not sure how I do that for this, sorry 😬

https://github.com/SkriptLang/Skript/blob/master/src/test/skript/README.md

2024-08-12 15:27 UTC, EquipableMC commented
> > > Could add some tests
> > 
> > 
> > not sure how I do that for this, sorry 😬
> 
> https://github.com/SkriptLang/Skript/blob/master/src/test/skript/README.md

I think what he means is how would he do tests for this expression exactly

2024-08-14 21:55 UTC, sovdeeth requested changes

2024-08-14 21:55 UTC, sovdeeth commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +	public Class<?>[] acceptChange(ChangeMode mode) {
```suggestion
	public Class<?> @Nullable [] acceptChange(ChangeMode mode) {
```

2024-08-14 21:55 UTC, sovdeeth commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +			case RESET, REMOVE -> new Class[] {null};
this is illegal! the array cannot contain nulls

2024-08-14 21:55 UTC, sovdeeth commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +	public void change(Event event, @Nullable Object[] delta, ChangeMode mode) {
```suggestion
	public void change(Event event, Object @Nullable [] delta, ChangeMode mode) {
```

2024-08-14 22:29 UTC, sovdeeth approved these changes

2024-08-16 20:23 UTC, UnderscoreTud approved these changes

2024-08-19 17:17 UTC, Moderocky approved these changes

2024-08-23 11:50 UTC, UnderscoreTud submitted a review, later dismissed

2024-08-23 11:50 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +			case RESET, REMOVE -> new Class<?>[0];
```suggestion
			case RESET, DELETE -> new Class<?>[0];
```

2024-08-23 11:50 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
> +					case RESET, REMOVE -> {
```suggestion
					case RESET, DELETE -> {
```

2024-10-13 04:21 UTC, merged