Temporary fix for plural endings error.
SkriptLang/Skript pull request #6982
Opened 2024-08-18 21:07 UTC by Moderocky

### Description

Some plural word endings are incorrectly detected, e.g. `-us` -> `-i` picks up "gui" as being a plural of (the well known word) "guus", and `-fe` -> `-ves` picks up "objectives" as being a plural of "objectife".

This PR patches these two cases _for now_ (by adding an alternative first) and I've moved to a queue and a helper class rather than a fixed-size array to make the follow-up API a little easier: you should be able to add stuff to the beginning or end of the queue without trouble.

I'd like to follow up with a proper system for doing this a little more effectively, and the ability for addons to fix any of their own problematic cases by registering plural overrides.
That's probably out of scope for a patch version so it will likely be a 2.10 feature, maybe using some registrations stuff?

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** fixes #6981, fixes #5879

2024-08-18 21:35 UTC, APickledWalrus approved these changes

2024-08-19 09:03 UTC, Moderocky commented
So the test uses `knife` -> `knives` which was broken by the `ive` -> `ives` change.
It seems like there are significantly more `ive` words than `ife` words, so I chose to add the `ife` words manually.

They all seem to be compounds of `*life`, `*wife` or `*knife` so I just added those three endings. I did not add `*rife` because no compound word is ever a noun that would be pluralised.

2024-08-31 20:28 UTC, sovdeeth requested changes

2024-08-31 20:28 UTC, sovdeeth commented on src/main/java/ch/njol/skript/util/Utils.java
> +			if (word.endsWith(ending.singular()))
```suggestion
	public static String toEnglishPlural(String word) {
		assert word != null && word.length() != 0;
		for (WordEnding ending : plurals) {
			if (word.endsWith(ending.singular()))
```

2024-08-31 20:28 UTC, sovdeeth commented on src/main/java/ch/njol/skript/util/Utils.java
> +	public static NonNullPair<String, Boolean> getEnglishPlural(final String word) {
```suggestion
	public static NonNullPair<String, Boolean> getEnglishPlural(String word) {
```

2024-08-31 20:28 UTC, sovdeeth commented on src/main/java/ch/njol/skript/util/Utils.java
>  	@SuppressWarnings("null")
it'd be nice to move this to a noinspection if feasible

2024-08-31 20:31 UTC, sovdeeth approved these changes

2024-08-31 20:46 UTC, merged