Add explicit sort order to EffSort
SkriptLang/Skript pull request #6997
Opened 2024-08-23 11:41 UTC by TenFont

### Description
Simply adds an explicit sort order to the sort effect, defaulting to ascending order.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6991

2024-08-23 11:45 UTC, UnderscoreTud approved these changes

2024-08-23 11:46 UTC, Moderocky requested changes
Since you've changed the pattern you'll need to change the `toString` to reflect this.

2024-08-23 17:08 UTC, Fusezion approved these changes
Besides kenzie's requested change and this one looks fine to me

2024-08-23 17:08 UTC, Fusezion commented on src/main/java/ch/njol/skript/effects/EffSort.java
> +@Since("2.9.0, INSERT VERSION (explicit order)")
```suggestion
@Since("2.9.0, INSERT VERSION (sortorder)")
```

2024-08-24 11:45 UTC, Moderocky approved these changes

2024-08-24 11:55 UTC, merged