Adds entity sound expression and test
SkriptLang/Skript pull request #7019
Opened 2024-08-31 14:35 UTC by cheeezburga

### Description
This PR adds an expression to get a sound of a living entity. The gettable sounds are `death, damage, swim, fall, high fall, fall from x distance, splash, speedy splash, eating, eating with x item, drinking, drinking with x item`

---
**Target Minecraft Versions:** 1.19.2 and higher
**Requirements:** none
**Related Issues:** none

2024-08-31 15:14 UTC, UnderscoreTud requested changes

2024-08-31 15:14 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
> +			(big ? entity.getFallDamageSoundBig() : entity.getFallDamageSoundSmall());
You should use if statements for better readability

2024-08-31 15:14 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
> +		ItemStack item = this.item == null ? defaultItem : this.item.getOptionalSingle(event).orElse(new ItemType(defaultItem)).getRandom();
```suggestion
		ItemStack item = this.item == null ? defaultItem : this.item.getOptionalSingle(event).map(ItemType::getRandom).orElse(defaultItem);
```

2024-08-31 15:14 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
> +		}
You could use a switch expression to return the string directly rather than reassigning the variable

2024-08-31 15:33 UTC, TheLimeGlass approved these changes

2024-08-31 15:33 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
> +		return sounds.toArray(String[]::new);
Can use a stream here. Import required.
```suggestion
		return entities.stream(event)
				.map(entity -> getEntitySound(entity, event))
				.map(Objects::nonNull)
				.toArray(String[]::new);
```

2024-08-31 15:33 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
> +	private int sound;
Can this be renamed to signify that it's of the sound pattern?
```suggestion
	private int soundPattern;
```

2024-08-31 15:33 UTC, TheLimeGlass commented on src/test/skript/tests/syntaxes/expressions/ExprEntitySound.sk
> +		set {_z} to entity
You can do all the assertions within the section safely.

2024-08-31 15:33 UTC, TheLimeGlass commented on src/test/skript/tests/syntaxes/expressions/ExprEntitySound.sk
> +	spawn a zombie at (spawn of world "world"):
You can use `event-location` to ensure consistency within the tests. Optional.

2024-08-31 18:31 UTC, Moderocky approved these changes

2024-09-13 15:21 UTC, UnderscoreTud approved these changes

2024-09-26 04:06 UTC, sovdeeth approved these changes
you could probably combine height and item into a single object parameter but that might just be worse

seems good

2024-10-13 05:05 UTC, merged