Underscores in numbers
SkriptLang/Skript pull request #7030
Opened 2024-09-02 21:28 UTC by Efnilite

### Description
Resolves #7015. Adds underscore support for formatting in numbers. 

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7015

2024-09-02 21:31 UTC, Fusezion commented
I don't believe we need a regression test currently but an actual test added, this isn't so much resolving a bug as much as adding an enhancement to numbers.

2024-09-02 21:32 UTC, Efnilite commented
> I don't believe we need a regression test currently but an actual test added, this isn't so much resolving a bug as much as adding an enhancement to numbers.

Should I put it in the misc folder then?

2024-09-02 21:38 UTC, Fusezion commented
Yeah I think misc is fair as this isn't syntax related

2024-09-02 21:57 UTC, Asleeepp commented
Kenzie mentioned something about adding a way to detect if it was a valid number, something like ____1___ shouldn't be valid

2024-09-02 22:03 UTC, UnderscoreTud commented
> Kenzie mentioned something about adding a way to detect if it was a valid number, something like ____1___ shouldn't be valid
> 
> heres the discord conversation if you're curious: [here](https://discord.com/channels/135877399391764480/836220422223036467/1279182736682254376)

That already isn't valid, but my main concern is how you can have adjacent underscores, for example `1___0` is valid when I don't think it makes that much sense.

2024-09-02 22:04 UTC, Efnilite commented
> Kenzie mentioned something about adding a way to detect if it was a valid number, something like ____1___ shouldn't be valid
> 
> heres the discord conversation if you're curious: [here](https://discord.com/channels/135877399391764480/836220422223036467/1279182736682254376)

This has already been addressed in the last lines of the test. Parsing the numbers starting and/or ending with `_` seems to resolve to none, as these numbers don't match the updated regex. If anything else should be changed, please lmk

2024-09-02 23:01 UTC, Efnilite commented
> > Kenzie mentioned something about adding a way to detect if it was a valid number, something like __**1**_ shouldn't be valid
> > heres the discord conversation if you're curious: [here](https://discord.com/channels/135877399391764480/836220422223036467/1279182736682254376)
> 
> That already isn't valid, but my main concern is how you can have adjacent underscores, for example `1___0` is valid when I don't think it makes that much sense.

Personally I agree that having multiple `_` is a little silly but someone might have a genuine use case for it, like maybe someone prefers `1__000__000` over `1_000_000`. Java also support this. 

I do think adding this is beneficial, although it would be possible to limit it to just one `_` if more people think it's a good idea.

2024-09-02 23:06 UTC, Asleeepp commented
> > > Kenzie mentioned something about adding a way to detect if it was a valid number, something like __**1**_ shouldn't be valid
> > > heres the discord conversation if you're curious: [here](https://discord.com/channels/135877399391764480/836220422223036467/1279182736682254376)
> > 
> > 
> > That already isn't valid, but my main concern is how you can have adjacent underscores, for example `1___0` is valid when I don't think it makes that much sense.
> 
> Personally I agree that having multiple `_` is a little silly but someone might have a genuine use case for it, like maybe someone prefers `1__000__000` over `1_000_000`. Java also support this.
> 
> I don't think this reason should axe this entire PR. It would be possible to limit it to just one `_` if more people think it's a good idea.

then i think that it would be better to make it consistent across the whole number
someone cant do `1__000_000` for example
though maybe there should also be a limit on how many underscores you can use

2024-09-02 23:09 UTC, UnderscoreTud commented
> > > Kenzie mentioned something about adding a way to detect if it was a valid number, something like __**1**_ shouldn't be valid
> > > heres the discord conversation if you're curious: [here](https://discord.com/channels/135877399391764480/836220422223036467/1279182736682254376)
> > 
> > 
> > That already isn't valid, but my main concern is how you can have adjacent underscores, for example `1___0` is valid when I don't think it makes that much sense.
> 
> Personally I agree that having multiple `_` is a little silly but someone might have a genuine use case for it, like maybe someone prefers `1__000__000` over `1_000_000`. Java also support this.
> 
> I don't think this reason should axe this entire PR. It would be possible to limit it to just one `_` if more people think it's a good idea.

Me and @APickledWalrus talked about it on discord and he also thought the same thing (that it shouldn't be allowed), but we can wait and see what the other members think

2024-09-02 23:19 UTC, sovdeeth commented
oh yes i definitely don't think it you should axe this pr
but i do agree that only 1 underscore makes sense and should be the requirement

2024-09-02 23:34 UTC, Efnilite commented
Aight, changed it to at most one and added tests for making sure that having multiple isn't supported

2024-09-02 23:57 UTC, Asleeepp requested changes

2024-09-02 23:57 UTC, Asleeepp commented on src/test/skript/tests/misc/underscores in numbers.sk
> +	assert ("___1.2_3_6___" parsed as number) is not a number with "___1.2_3_6___ is a number"
```suggestion
	assert ("___1.2_3_6___" parsed as number) is not a number with "___1.2_3_6___ is a number"

```

2024-09-03 00:26 UTC, sovdeeth approved these changes

2024-09-03 16:59 UTC, Asleeepp approved these changes
since you requested my review (my approval does nothing haha)

2024-09-16 06:15 UTC, Moderocky approved these changes

2024-10-13 05:11 UTC, merged