Fix Message when reloading multiple scripts with an error.
SkriptLang/Skript pull request #7031
Opened 2024-09-02 23:55 UTC by Asleeepp

### Description

Noticed while updating my server (and i had some errors) that when i reloaded an entire folder, the "in" was colored green, which looked pretty strange. this pr fixes that. 
Although, not sure if lime is even used much across Skript (apart from reloading correctly), so maybe the lime color should just be changed overall. lmk!

Not sure if you guys want it in the other langs too, but im not sure how i could do that, im not a polyglot 🤷 

---
![image](https://github.com/user-attachments/assets/dcd039e9-decb-47cc-a55b-6223417b94a0)

**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-09-03 22:34 UTC, sovdeeth commented
you should just change the light green to light red. nothing should be green in that message imo

2024-09-03 23:12 UTC, Asleeepp commented
> you should just change the light green to light red. nothing should be green in that message imo

would you like me to do it for the other langs too? since its just a color change should be fairly simple

2024-09-04 07:12 UTC, Moderocky requested changes
This was made green because of #6136.
Unfortunately, we didn't know at the time it's also used in another place (which was presumably why it was left white to begin with).

You're either going to have to separate it into two language nodes or find some colour that works for both.

2024-09-15 07:40 UTC, Moderocky approved these changes

2024-09-23 22:12 UTC, Efnilite approved these changes

2024-09-30 13:44 UTC, UnderscoreTud approved these changes

2024-10-01 13:18 UTC, APickledWalrus approved these changes
One minor thing

2024-10-01 13:18 UTC, APickledWalrus commented on src/main/resources/lang/french.lang
> +		x scripts in folder success: <gold>%2$s <light red>script¦¦s¦ dans <gold>%1$s<reset>
```suggestion
		x scripts in folder errors: <gold>%2$s <light red>script¦¦s¦ dans <gold>%1$s<reset>
```
oops!

2024-10-01 16:37 UTC, merged