Fix missing "and" warnings
SkriptLang/Skript pull request #7036
Opened 2024-09-04 16:13 UTC by Efnilite

### Description
Fixes missing `and` warnings in a few tests. This reduces the amount warnings that show up, increasing the chances of contributors finding warnings in their own PRs, and making it easier to find errors.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-09-04 16:24 UTC, sovdeeth approved these changes

2024-09-04 16:40 UTC, APickledWalrus requested changes

2024-09-04 16:40 UTC, APickledWalrus commented on src/test/skript/tests/regressions/pull-6586-effhealth item mutation.sk
> +	repair {_item1}, and {_item2}
Can we remove the comma in cases like this where there are only two values?

2024-09-04 17:14 UTC, APickledWalrus approved these changes

2024-09-04 17:15 UTC, APickledWalrus commented
Oh this could probably target patch if you want to rebase it

2024-09-04 17:16 UTC, Moderocky commented
Seems it didn't like changing the base, I can rebase this for you if you need.

2024-09-04 17:25 UTC, Moderocky commented
I think I fixed it for you please double check it looks right though!

2024-09-04 18:15 UTC, Efnilite commented
SecFilter and ExprJoinSplit are not up to date, do I have to redo them

2024-09-05 09:49 UTC, Moderocky commented
> SecFilter and ExprJoinSplit are not up to date, do I have to redo them

Don't worry I removed them (they were feature-only tests) it should be all fine now.

2024-09-21 19:52 UTC, merged