Wolf Variants
SkriptLang/Skript pull request #7041
Opened 2024-09-06 03:22 UTC by TheAbsolutionism

### Description

This PR aims to add wolf variants
---
**Target Minecraft Versions:** 1.21+ 
**Requirements:** none 
**Related Issues:** #6923

2024-09-06 08:22 UTC, Moderocky approved these changes

2024-09-13 13:34 UTC, sovdeeth requested changes

2024-09-13 13:34 UTC, sovdeeth commented on src/main/java/ch/njol/skript/entity/WolfData.java
>  	private DyeColor collarColor;
```suggestion
	private @Nullable Object variant;
	private @Nullable DyeColor collarColor;
```

2024-09-13 13:34 UTC, sovdeeth commented on src/main/java/ch/njol/skript/entity/WolfData.java
> +			(collarColor == null ? true : entity.getCollarColor() == collarColor) && (variant == null ? true : entity.getVariant() == variant);
```suggestion
			(collarColor == null || entity.getCollarColor() == collarColor) && (variant == null || entity.getVariant() == variant);
```

2024-09-13 13:34 UTC, sovdeeth commented on src/test/skript/tests/syntaxes/effects/EffSpawn.sk
> +	assert size of all wolves = 0 with "Size of all wolves is greater than 0 after all were deleted"
```suggestion
	assert size of all wolves = 0 with "Size of all wolves is greater than 0 after all were deleted"

```

2024-09-13 14:40 UTC, sovdeeth requested changes

2024-09-13 14:40 UTC, sovdeeth commented on src/main/java/ch/njol/skript/entity/WolfData.java
> +			return (angry == 0 || wolfData.angry == angry) && (tamed == 0 || wolfData.tamed == tamed) && (wolfData.collarColor == collarColor) && (variantsEnabled ? wolfData.variant == variant : true);
```suggestion
			return (angry == 0 || wolfData.angry == angry) && (tamed == 0 || wolfData.tamed == tamed) && (wolfData.collarColor == collarColor) && (!variantsEnabled || wolfData.variant == variant);
```

2024-09-13 14:40 UTC, sovdeeth commented on src/test/skript/tests/syntaxes/effects/EffSpawn.sk
> +
```suggestion

```

2024-09-13 14:41 UTC, TheAbsolutionism commented on src/test/skript/tests/syntaxes/effects/EffSpawn.sk
> +
Didnt you just suggest to add that? or?

2024-09-13 14:54 UTC, sovdeeth requested changes

2024-09-13 14:54 UTC, sovdeeth commented on src/test/skript/tests/syntaxes/effects/EffSpawn.sk
> +	assert size of all wolves = 0 with "Size of all wolves is greater than 0 after all were deleted"
unresolved

2024-09-14 05:52 UTC, cheeezburga approved these changes

2024-09-14 05:52 UTC, cheeezburga commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +			.requiredPlugins("Minecraft 1.21 or newer")
```suggestion
			.requiredPlugins("Minecraft 1.21+")
```

2024-09-20 00:12 UTC, sovdeeth approved these changes

2024-10-13 05:22 UTC, merged