Adds PropertyExpression helper method
SkriptLang/Skript pull request #7043
Opened 2024-09-06 12:39 UTC by cheeezburga

### Description
This PR adds a `getPatterns` helper method to PropertyExpression.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-09-06 13:37 UTC, sovdeeth requested changes

2024-09-06 13:37 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
> +	 * i.e. "property of %types%" and "%types%'[s] property"
```suggestion
	 * i.e. "[the] property of %types%" and "%types%'[s] property"
```

2024-09-06 13:37 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
> +			return null;
i would suggest an exception here instead, there's no case in which one of these being null is intended

2024-09-06 23:40 UTC, UnderscoreTud requested changes

2024-09-06 23:40 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
> +		Skript.registerExpression(expressionClass, type, ExpressionType.PROPERTY, getPatterns(property, fromType));
This is not registering a pattern with a default expression anymore

2024-09-07 16:04 UTC, UnderscoreTud requested changes

2024-09-07 16:04 UTC, UnderscoreTud commented on src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
> +	public static String[] getPatterns(String property, String fromType, boolean defaultExpression) {
You should overload the method and default `defaultExpression` to false.
Or better yet, remove the boolean parameter and make them two separate methods.

2024-09-13 15:01 UTC, UnderscoreTud approved these changes

2024-09-16 06:15 UTC, Moderocky approved these changes
Good.

2024-10-13 05:25 UTC, merged