Update EffCancelEvent
SkriptLang/Skript pull request #7066
Opened 2024-09-10 16:02 UTC by Efnilite

### Description
Adds error for trying to cancel the swim toggle event and updates `EffCancelEvent`:

- Added test
- Use tag for uncancel
- Updated formatting

---

**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7054

2024-09-10 16:15 UTC, Pikachu920 commented on src/main/java/ch/njol/skript/effects/EffCancelEvent.java
> +		Skript.registerEffect(EffCancelEvent.class, "[:un]cancel [the] event");
why not two patterns :(

2024-09-10 16:16 UTC, cheeezburga commented
Sorry! I misclicked

2024-09-10 16:34 UTC, Pikachu920 requested changes

2024-09-10 16:34 UTC, Pikachu920 commented on src/test/skript/junit/EffCancelEvent.sk
> +		complete objective "uncancel event" for {_test}
new line at end of file pls

2024-09-10 16:34 UTC, Pikachu920 commented on src/test/skript/junit/EffCancelEvent.sk
> +test "SimpleJUnitTest" when running JUnit:
could you please also add a test for the swim event error (maybe the player login one too if you want)? you can use the parse structure to ensure it errors as expected

2024-09-11 15:07 UTC, Efnilite commented
Is awaiting merge of #7066

2024-09-13 14:15 UTC, sovdeeth requested changes

2024-09-13 14:15 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffCancelEvent.java
> +			Skript.error("Cancelling a toggle swim event has no effect", ErrorQuality.SEMANTIC_ERROR);
```suggestion
			Skript.error("Cancelling a toggle swim event has no effect");
```

2024-09-20 00:12 UTC, sovdeeth approved these changes

2024-09-23 17:01 UTC, Pikachu920 approved these changes
woooooooooooooooooooo

2024-10-01 13:24 UTC, APickledWalrus approved these changes

2024-10-01 13:24 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffCancelEvent.java
> +			Skript.error("Can't cancel an event after it has already passed", ErrorQuality.SEMANTIC_ERROR);
```suggestion
			Skript.error("An event cannot be cancelled after it has already passed", ErrorQuality.SEMANTIC_ERROR);
```
I think this is a better statement to make

2024-10-01 13:24 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffCancelEvent.java
> +			Skript.error("Cancelling a toggle swim event has no effect");
Should this be a warning? Or do we want to return false here?

2024-10-01 22:21 UTC, merged