Fix events in StructParse
SkriptLang/Skript pull request #7067
Opened 2024-09-11 15:06 UTC by Efnilite

### Description
Fix events not working in StructParse.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7066

2024-09-11 15:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/test/runner/StructParse.java
> +				structure.load();
We need to make sure that preLoad did not return false. postLoad must do the same for load

2024-09-11 15:24 UTC, sovdeeth requested changes

2024-09-11 15:24 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/StructParse.java
> +			if (structure != null && (!structure.preLoad() || !structure.load() || !structure.postLoad())) {
should it be `(structure == null || (...))`?

2024-09-11 15:24 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/StructParse.java
> +			if (structure != null && (!structure.preLoad() || !structure.load() || !structure.postLoad())) {
you may also need to remove current structure if failed, not sure

2024-09-11 20:17 UTC, sovdeeth approved these changes

2024-09-11 20:18 UTC, APickledWalrus approved these changes
looks good

2024-09-11 20:22 UTC, Pikachu920 approved these changes
thanks!!

2024-09-12 20:39 UTC, merged

2024-09-19 17:19 UTC, TheLimeGlass commented on src/test/skript/tests/regressions/pull-7067-events in structs.sk
> +	assert {StructEvent::parse::*} is not set with "using event in struct caused an error"
Can this return a value to ensure that the parse section parsed?