BlockDropItemEvent
SkriptLang/Skript pull request #7075
Opened 2024-09-13 18:18 UTC by TheAbsolutionism

### Description
This PR aims to add the `BlockDropItemEvent`

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5959

2024-09-14 10:36 UTC, Efnilite requested changes

2024-09-14 10:36 UTC, Efnilite commented on src/main/java/ch/njol/skript/events/EvtBlock.java
> +				"</ul>",
is there a precedent for this?

2024-09-14 10:36 UTC, Efnilite commented on src/main/java/ch/njol/skript/events/EvtBlock.java
> +				"Called when a block broken by a player drops items",
```suggestion
				"Called when a block broken by a player drops something.",
```

2024-09-14 10:36 UTC, Efnilite commented on src/main/java/ch/njol/skript/events/EvtBlock.java
> +				"If the breaking of the block leads to others being broken, such as torches, they will appear",
appear where?

2024-09-14 10:36 UTC, Efnilite commented on src/main/java/ch/njol/skript/events/EvtBlock.java
> +			.examples("on block drop:", "on block drop of oak log:")
should have at least some code in the event itself like broadcast, doesnt matter

2024-09-14 10:36 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
> +			Skript.error("The expression 'drops' can only be used in death events and block drop events", ErrorQuality.SEMANTIC_ERROR);
```suggestion
			Skript.error("The expression 'drops' can only be used in death events and block drop events");
``` 
semantic is default

2024-09-14 22:05 UTC, Efnilite approved these changes

2024-09-14 22:05 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
>  			switch (mode) {
enhanced switch

2024-09-20 00:03 UTC, sovdeeth requested changes

2024-09-20 00:03 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +			}
remove nullable if can't return null

2024-09-20 00:03 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
> +	protected @Nullable ItemType[] get(Event event) {
```suggestion
	protected ItemType @Nullable [] get(Event event) {
```

2024-09-20 00:03 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
> +				case REMOVE -> {entityDeathEvent.setDroppedExp(originalExperience - deltaExperience);} // fallthrough to check for removeAllExperience
this doesn't fall through anymore

2024-09-20 11:47 UTC, TheLimeGlass approved these changes

2024-09-20 11:47 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/events/EvtBlock.java
> +	public @NotNull String toString(@Nullable Event event, boolean debug) {
This `@NotNull` isn't needed at this position when Skript is the one to call this, and Skript already asserts it not null.
Same with import for this annotation.

2024-09-20 11:47 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
> +
```suggestion
```

2024-09-20 11:47 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
> +		}
```suggestion
		}
		assert false;
```
Optional as there aren't any tests to catch this.

2024-09-21 14:25 UTC, sovdeeth requested changes

2024-09-21 14:25 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +			}
still need nullables addressed

2024-09-21 14:25 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprDrops.java
> +				case REMOVE -> {entityDeathEvent.setDroppedExp(originalExperience - deltaExperience);} // fallthrough to check for removeAllExperience
unresolved?

2024-09-26 04:10 UTC, sovdeeth approved these changes

2024-10-13 06:09 UTC, merged