Server icons
SkriptLang/Skript pull request #7101
Opened 2024-09-20 12:57 UTC by Efnilite

### Description
Updates server icon syntax classes and adds a test (requires #7053)

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7053

2024-09-20 21:44 UTC, cheeezburga approved these changes

2024-09-20 21:44 UTC, cheeezburga commented on src/main/java/ch/njol/skript/expressions/ExprServerIcon.java
> +	public @Nullable Class<?>[] acceptChange(ChangeMode mode) {
```suggestion
	public Class<?> @Nullable [] acceptChange(ChangeMode mode) {
```

2024-09-20 21:44 UTC, cheeezburga commented on src/main/java/ch/njol/skript/expressions/ExprServerIcon.java
> +	public @Nullable CachedServerIcon[] get(Event event) {
```suggestion
	public CachedServerIcon @Nullable [] get(Event event) {
```

2024-11-30 14:14 UTC, Moderocky requested changes
You need to resolve these conflicts manually.

2025-01-01 17:14 UTC, closed without merging