Add chat client options
SkriptLang/Skript pull request #7105
Opened 2024-09-21 13:54 UTC by Efnilite

### Description
- Adds chat visibility expression and type
- Adds condition for whether the player has chat filtering enabled
- Adds condition for whether the player has chat colours enabled

---
**Target Minecraft Versions:** any 
**Requirements:** Paper 
**Related Issues:** none

2024-09-21 14:57 UTC, sovdeeth requested changes

2024-09-21 14:57 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondChatColors.java
> +		return "can see chat colors";
```suggestion
		return "see chat colors";
```

2024-09-21 14:57 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondChatFiltering.java
> +		return "has chat filtering enabled";
```suggestion
		return "chat filtering enabled";
```

2024-09-21 14:57 UTC, sovdeeth commented on src/main/resources/lang/default.lang
> +	full: full, visible
```suggestion
	full: fully visible, visible
```

2024-09-21 14:57 UTC, sovdeeth commented on src/main/resources/lang/default.lang
> +	system: system, commands only, only commands
```suggestion
	system: system messages only, only system messages, commands only, only commands
```

2024-09-21 14:57 UTC, sovdeeth commented on src/test/skript/junit/ExprChatVisibility.sk
> +		complete objective "can see chat colours" for {_test}
```suggestion
		complete objective "can see chat colours" for {_test}

```

2024-09-21 14:57 UTC, sovdeeth commented on src/test/skript/junit/ExprChatVisibility.sk
> +	if player's chat visibility is only commands:
honestly seeing this syntax makes me think this should be a custom condition. I'd rather see `if player can only see commands in chat` or something to that effect

2024-09-26 04:03 UTC, sovdeeth approved these changes

2024-09-26 04:03 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +import com.destroystokyo.paper.ClientOption;
this file doesn't need to be edited

2024-09-26 04:03 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondChatVisibility.java
> +	}
```suggestion
	}

```

2024-09-29 05:36 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/conditions/CondChatVisibility.java
> +})
```suggestion
})
@RequiredPlugins("Paper")
```

2024-10-26 14:35 UTC, Moderocky approved these changes

2024-10-31 20:21 UTC, merged