Function Locate
SkriptLang/Skript pull request #7108
Opened 2024-09-22 06:10 UTC by TheAbsolutionism

### Description
This PR aims to add the ability to locate functions by providing the script it's in as well as the line number. 
Useful for big projects or dev teams that need to find a function.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-09-26 21:00 UTC, Efnilite commented on src/main/java/ch/njol/skript/lang/function/Signature.java
> +  	@Override
does this use spaces?

2024-09-26 21:02 UTC, Efnilite commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +		).add("locate");
```suggestion
		.add("help")
		.add("locate");
```

2024-09-26 21:02 UTC, Efnilite commented on src/main/java/ch/njol/skript/SkriptCommand.java
>  		).add("info"
```suggestion
		).add("info")
```

2024-09-29 10:00 UTC, Efnilite approved these changes

2024-12-25 17:46 UTC, erenkarakal requested changes

2024-12-25 17:46 UTC, erenkarakal commented on src/main/resources/lang/turkish.lang
> +		locate: Bir işlevi bulmak için kullanılır
Bir fonksiyonu bulmak için kullanılır.

2024-12-25 17:46 UTC, erenkarakal commented on src/main/resources/lang/turkish.lang
> +		function provided: İşlev '&e%s&f' tarafından sağlanır Skript
Fonksiyon '&e%s&f' Skript tarafından eklendi.

2024-12-25 17:46 UTC, erenkarakal commented on src/main/resources/lang/turkish.lang
> +		function not found: İşlev '%s' bulunamıyor
'%s' isimli fonksiyon bulunamadı.

2024-12-25 19:50 UTC, closed without merging