Implement ADD and REMOVE changers to ExprMetadata
SkriptLang/Skript pull request #7113
Opened 2024-09-26 21:01 UTC by UnderscoreTud

### Description
This PR adds `add` and `remove` changers to the metadata value expression, similar to the behaviour of adding and removing values from variables.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-09-26 21:08 UTC, Efnilite approved these changes
nice

2024-09-26 21:08 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprMetadata.java
>  	public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean isDelayed, SkriptParser.ParseResult parseResult) {
```suggestion
	public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean isDelayed, ParseResult parseResult) {
```

2024-09-26 21:08 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprMetadata.java
>   */
can be removed

2024-09-26 21:15 UTC, Efnilite approved these changes

2024-09-26 22:40 UTC, sovdeeth approved these changes

2024-09-26 22:40 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprMetadata.java
>  }
```suggestion
}

```

2024-10-13 17:05 UTC, cheeezburga approved these changes

2024-10-13 17:09 UTC, Pikachu920 requested changes

2024-10-13 17:09 UTC, Pikachu920 commented on src/main/java/ch/njol/skript/expressions/ExprMetadata.java
> +						if (metadata.isEmpty() || (value = metadata.get(metadata.size() - 1).value()) == null) {
can we please not do the assignment here

2024-10-13 17:09 UTC, Pikachu920 commented on src/test/skript/tests/syntaxes/expressions/ExprMetadata.sk
> +test "metadata value":
could we please get some tests for adding/removing/setting to incorrect typed and null values

2024-10-13 17:28 UTC, Moderocky approved these changes

2024-10-13 18:07 UTC, Pikachu920 approved these changes

2024-10-31 18:52 UTC, merged