Make visual effects serializable
SkriptLang/Skript pull request #7114
Opened 2024-09-26 21:04 UTC by Romitou

### Description

Started by @TPGamesNL in PR #4123 (the commit has been cherry-picked and the author has been kept for credits), providing a serializer for `VisualEffectType` allows to serialize `VisualEffect` correctly. In fact, this should have been handled by `simpleClassLoaders`, where this specific class was originally registered.

However, the `Yggdrasil#getSerializer` method did not return a serializer: a `SimpleClassResolver` extends from `ClassResolver` and not from a `YggdrasilSerializer` like the others. A fix is therefore to directly register this serializer at the root of `classResolvers`.

https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/yggdrasil/Yggdrasil.java

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:**

2024-09-26 21:12 UTC, Efnilite requested changes

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public Class<? extends VisualEffectType> getClass(String id) {
```suggestion
			public @Nullable Class<? extends VisualEffectType> getClass(String id) {
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public Fields serialize(VisualEffectType o) {
```suggestion
			public Fields serialize(VisualEffectType visualEffectType) {
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +				Fields f = new Fields();
```suggestion
				Fields fields = new Fields();
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public <E extends VisualEffectType> E newInstance(Class<E> c) {
```suggestion
			public @Nullable <E extends VisualEffectType> E newInstance(Class<E> clazz) {
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public boolean canBeInstantiated(Class<? extends VisualEffectType> c) {
```suggestion
			public boolean canBeInstantiated(Class<? extends VisualEffectType> clazz) {
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public void deserialize(VisualEffectType o, Fields fields) { }
```suggestion
			public void deserialize(VisualEffectType visualEffectType, Fields fields) { }
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			@Override
```suggestion
			@Override
			@SuppressWarnings("unchecked")
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public <E extends VisualEffectType> E deserialize(Class<E> c, Fields fields) throws StreamCorruptedException, NotSerializableException {
```suggestion
			public <E extends VisualEffectType> E deserialize(Class<E> clazz, Fields fields) throws StreamCorruptedException, NotSerializableException {
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +			public String getID(Class<?> c) {
```suggestion
			public @Nullable String getID(Class<?> clazz) {
```

2024-09-26 21:12 UTC, Efnilite commented on src/main/java/ch/njol/skript/util/visual/VisualEffects.java
> +	public static VisualEffectType get(String id) {
```suggestion
	public static @Nullable VisualEffectType get(String id) {
```

2024-09-26 21:14 UTC, Efnilite commented
also you can remove the license from the top of the files

2024-09-26 22:55 UTC, sovdeeth requested changes
Does this handle types with data, like vibrations or dust particles? Also, I'd like to see some regression tests if possible.

2024-09-29 05:47 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
> +				fields.putObject("id", visualEffectType.getId());
doing a quick look thru the VisualEffectType code, I see this regarding IDs
```java
public String getId() {
	return effect.getDeclaringClass().getSimpleName() + "." + effect.name();
}
```
The issue here is the ID is the class name and enum name.
Problem comes from the fact Mojang has changed particle names several times in the last few versions.
And as of I believe 1.21 Bukkit has changed a whole bunch of the enums.
That said, this is not version safe.

2025-04-07 22:17 UTC, sovdeeth commented
Closing due to inactivity

2025-04-07 22:17 UTC, closed without merging