Update files to match checkstyle (part 1)
SkriptLang/Skript pull request #7117
Opened 2024-09-27 09:30 UTC by Efnilite

### Description
Updates some of the worst offenders, who are least likely to be affected by other PRs.
I removed the copyright header, used IntellIJ's formatting shortcut, and split lines that were >120 chars.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-09-27 17:46 UTC, Moderocky commented on src/main/java/ch/njol/skript/effects/EffFeed.java
> +		Skript.registerEffect(EffFeed.class, "feed [the] %players% [by %-number% [beef[s]]]");
```suggestion
		Skript.registerEffect(EffFeed.class, "feed [the] %players% [by %-number% [beef[s]]]");
```
Beefs 😭

2024-09-28 04:22 UTC, cheeezburga approved these changes
There's some `e`s that could be `event`s, and switches that could be updated, but if this is just a styling thing then looks good

2024-09-28 04:22 UTC, cheeezburga commented on src/main/java/ch/njol/skript/entity/RabbitData.java
> +	@Override
```suggestion
	@Override
	@SuppressWarnings("null")
```

2024-09-28 04:22 UTC, cheeezburga commented on src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
> +	private Expression<Date> date;
```suggestion
	private @Nullable Expression<Date> date;
```

2024-09-28 04:22 UTC, cheeezburga commented on src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
> +	protected Date[] get(Event e) {
```suggestion
	@Nullable
	@SuppressWarnings("null")
	protected Date[] get(Event e) {
```
```suggestion
	@SuppressWarnings("null")
	protected Date @Nullable [] get(Event e) {
```

2024-09-30 14:49 UTC, sovdeeth requested changes

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffFeed.java
> +	}
```suggestion
	protected void execute(Event event) {
		int level = 20;

		if (beefs != null) {
			Number levelNum = beefs.getSingle(event);
			if (levelNum == null)
				return;
			level = levelNum.intValue();
		}
		for (Player player : players.getArray(event)) {
			player.setFoodLevel(player.getFoodLevel() + level);
		}
	}
```

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffFeed.java
> +	}
```suggestion
	public String toString(@Nullable Event event, boolean debug) {
		return "feed " + players.toString(event, debug) + (beefs != null ? " by " + beefs.toString(event, debug) : "");
	}
```

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/entity/RabbitData.java
> +	}
```suggestion
	protected boolean equals_i(EntityData<?> otherData) {
		if (!(otherData instanceof RabbitData))
			return false;
		RabbitData other = (RabbitData) otherData;
		return type == other.type;
	}
```

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/entity/RabbitData.java
> +	}
```suggestion
	public boolean isSupertypeOf(EntityData<?> data) {
		return data instanceof RabbitData && (type == 0 || ((RabbitData) data).type == type);
	}
```

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
> +	protected Date[] get(Event e) {
change event param name too

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
>  			: (date != null ? "after " + date.toString(e, debug) : "later"));
```suggestion
	public String toString(@Nullable Event event, boolean debug) {
		return timespan.toString(event, debug) + " " +
			(ago ? (date != null ? "before " + date.toString(event, debug) : "ago")
			: (date != null ? "after " + date.toString(event, debug) : "later"));
```

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/hooks/regions/PreciousStonesHook.java
> +	public boolean canBuild_i(final Player p, final Location l) {
better names

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/hooks/regions/PreciousStonesHook.java
> +	public Collection<? extends Region> getRegionsAt_i(final Location l) {
better param name

2024-09-30 14:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/hooks/regions/PreciousStonesHook.java
>  public class PreciousStonesHook extends RegionsPlugin<PreciousStones> {
this whole class just needs better variable names and removal of extra finals

2024-10-01 16:54 UTC, sovdeeth approved these changes

2024-10-26 14:28 UTC, Moderocky approved these changes

2024-11-29 04:08 UTC, cheeezburga approved these changes

2024-12-01 09:55 UTC, closed without merging