Fix some syntaxes overwriting variable list indices and add new helper method for changing expressions.
SkriptLang/Skript pull request #7120
Opened 2024-09-30 18:04 UTC by sovdeeth

### Description

A few expressions/effects currently clear the indices of variable lists used in them, since they use ChangeMode#SET indiscriminately. This PR adds a new default method on Expression, changeInPlace(Event, Function), which applies a Function to each value of the Expression, then calls change() with SET using the new values. 
For Variables, this method is overwritten to use the variable's iterator, meaning that calling `expr.changeInPlace()` is a safe way to change all expressions while maintaining indices for variable lists.

Behavior change is limited to not overwriting variable indices anymore, but also it does not remove elements of the wrong type from variable lists: ```
	set {_test::1} to vector(0,3,0)
	set {_test::a} to vector(0,0,4)
	set {_test::hello world} to "abc"
	set vector length of {_test::*} to 1
	# {_test::*} still contains "abc" now
```

I believe this to be bug fixing rather than breaking, but let me know if you disagree.
or if you disagree with the implementation!

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-09-30 20:31 UTC, Efnilite requested changes

2024-09-30 20:31 UTC, Efnilite commented on src/main/java/ch/njol/skript/effects/EffReplace.java
> +
```suggestion
```

2024-09-30 20:31 UTC, Efnilite commented on src/main/java/ch/njol/skript/effects/EffReplace.java
> +				for (Object n : needles) {
```suggestion
				for (Object needle : needles) {
```

2024-09-30 20:31 UTC, Efnilite commented on src/test/skript/tests/regressions/pull-7120-changes overwriting indices.sk
> +test "effreplace overwriting var indices":
```suggestion
test "EffReplace overwriting var indices":
```

2024-09-30 20:31 UTC, Efnilite commented on src/test/skript/tests/regressions/pull-7120-changes overwriting indices.sk
> +test "effenchant overwriting var indices":
```suggestion
test "EffEnchant overwriting var indices":
```

2024-09-30 20:31 UTC, Efnilite commented on src/main/java/ch/njol/skript/effects/EffReplace.java
> +				for (Object n : needles) {
```suggestion
				for (Object needle : needles) {
```

2024-09-30 20:31 UTC, Efnilite commented on src/main/java/ch/njol/skript/effects/EffReplace.java
> +					haystackString = StringUtils.replaceFirst(haystackString, (String)n, Matcher.quoteReplacement(replacement), caseSensitive);
```suggestion
					haystackString = StringUtils.replaceFirst(haystackString, (String) n, Matcher.quoteReplacement(replacement), caseSensitive);
```

2024-09-30 20:31 UTC, Efnilite commented on src/main/java/ch/njol/skript/effects/EffEnchant.java
> +
```suggestion
```

2024-09-30 20:31 UTC, Efnilite commented on src/main/java/ch/njol/skript/lang/Expression.java
> +	default <R> void changeInPlace(Event event, Function<T, R> changeFunction, boolean all) {
`useAll` might better clarify that it uses getAll instead of confusing this for whether to apply it to all values or something, but idk

2024-09-30 23:37 UTC, Efnilite approved these changes

2024-10-26 14:30 UTC, Moderocky approved these changes

2024-11-06 16:24 UTC, UnderscoreTud approved these changes

2024-11-23 05:20 UTC, merged