Pretty Quote Error
SkriptLang/Skript pull request #7129
Opened 2024-10-03 22:50 UTC by TheAbsolutionism

### Description
This PR aims to produce a proper error when users use pretty quotes instead of regular.
Was hoping to allow the usage of them though.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6810

2024-10-04 10:29 UTC, Efnilite approved these changes

2024-10-04 16:49 UTC, sovdeeth approved these changes

2024-10-05 07:53 UTC, cheeezburga approved these changes

2024-10-26 14:39 UTC, Moderocky requested changes

2024-10-26 14:39 UTC, Moderocky commented on src/test/skript/tests/misc/pull-7129-pretty-quotes.sk
> +		set {-PrettyQuoteArg} to arg
This - stuff isn't a thing in the testing environment so you need to actually delete the variable when the test is done instead.

2024-11-01 08:30 UTC, Moderocky approved these changes

2024-11-23 05:23 UTC, merged