On Click BlockData
SkriptLang/Skript pull request #7130
Opened 2024-10-04 18:37 UTC by TheAbsolutionism

### Description
This PR aims to support blockdata for on click

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6305

2024-10-05 07:43 UTC, cheeezburga requested changes
Just some small stuff, but you should also remove `final`s that are scattered throughout, and theres still code that can be updated (switch statements, etc.).

2024-10-05 07:43 UTC, cheeezburga commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +						"on click on chest[facing=north]:")
```suggestion
						"on click on chest[facing=north]:",
						"on click on campfire[lit=true]")
```

2024-10-05 07:43 UTC, cheeezburga commented on src/main/java/ch/njol/skript/events/EvtClick.java
>  	 * Only trigger when then item player clicks with is one of these.
```suggestion
	 * Only trigger when the item that the player clicks with is one of these.
```

2024-10-05 07:43 UTC, cheeezburga commented on src/main/java/ch/njol/skript/events/EvtClick.java
>  			public boolean check(final ItemType t) {
```suggestion
			public boolean check(final ItemType itemType) {
```

2024-10-05 07:43 UTC, cheeezburga commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +			Action a = interactEvent.getAction();
```suggestion
			Action action = interactEvent.getAction();
```

2024-10-05 10:43 UTC, Efnilite approved these changes
looks good with @cheeezburga's changes

2024-10-05 10:43 UTC, Efnilite commented on src/main/java/ch/njol/skript/events/EvtClick.java
>  				public boolean check(final Object o) {
```suggestion
				public boolean check(Object object) {
```

2024-10-05 16:25 UTC, TheAbsolutionism commented
> Just some small stuff, but you should also remove `final`s that are scattered throughout, and theres still code that can be updated (switch statements, etc.).

I could change to an enhanced switch, but I cant put both `case PHYSICAL` and `default` on the same line leading to two `return false`s
Other than that, I dont really see anything else sticking out that might need to be updated, imo, but if you would like to point out some things I can take a look.

2024-10-09 16:32 UTC, TheLimeGlass approved these changes

2024-10-09 16:32 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +	public static ClickEventTracker interactTracker = new ClickEventTracker(Skript.getInstance());
The final can remain on fields. This is not related to the common final abuse of parameters seen in Skript coding standards.
```suggestion
	public final static ClickEventTracker interactTracker = new ClickEventTracker(Skript.getInstance());
```

2024-10-09 16:32 UTC, TheLimeGlass commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +	private static int RIGHT = 1, LEFT = 2, ANY = RIGHT | LEFT;
The final can remain on fields. This is not related to the common final abuse of parameters seen in Skript coding standards.
```suggestion
	private final static int RIGHT = 1, LEFT = 2, ANY = RIGHT | LEFT;
```

2024-10-09 20:49 UTC, cheeezburga approved these changes

2024-10-09 20:57 UTC, cheeezburga commented
> I could change to an enhanced switch, but I cant put both `case PHYSICAL` and `default` on the same line leading to two `return false`s Other than that, I dont really see anything else sticking out that might need to be updated, imo, but if you would like to point out some things I can take a look.

I think an enhanced one would look a bit nicer, but up to you. I don't think there was anything else, but I wouldn't hate if you wanted to change the error messages a bit in `init`, as they seem a bit clunky and/or misleading at the moment.

2024-10-12 03:58 UTC, sovdeeth requested changes

2024-10-12 03:58 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
>  				}
These were fine; I don't think they need changes beyond the addition of `a vehicle` like the change above.

2024-10-12 03:58 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
>  			}
the checker could just be a lambda

2024-10-12 13:39 UTC, sovdeeth requested changes

2024-10-12 13:39 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +						"Change this event to a rightclick to fix this warning message.");
why were the tabs removed? a continuation of a line should have two tabs following it re: coding conventions

2024-10-12 13:39 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +					? invi.getItemInMainHand() : invi.getItemInOffHand();
same here, two tabs

2024-10-12 13:39 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +						return object instanceof EntityData ? ((EntityData<?>) object).isInstance(entity) : Relation.EQUAL.isImpliedBy(DefaultComparators.entityItemComparator.compare(EntityData.fromEntity(entity), (It
should split over multiple lines, very far over the 180 char limit

2024-10-12 13:39 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +		return (click == LEFT ? "left" : click == RIGHT ? "right" : "") + "click" + (type != null ? " on " + type.toString(event, debug) : "") + (tools != null ? " holding " + tools.toString(event, debug)
also split over multiple lines

2024-10-12 23:04 UTC, sovdeeth requested changes

2024-10-12 23:04 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +				}
can't these be collapsed into one?

2024-10-12 23:04 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +		})) { return false; }
```suggestion
		})) {
			return false;
		}
```

2024-10-12 23:04 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtClick.java
> +		})) { return false; }
actually you might want to declare the lambda as a predicate prior to the if statement, so the if statement doesn't get lost in the sauce.

2024-10-15 17:30 UTC, sovdeeth approved these changes

2024-10-31 18:11 UTC, merged