Add fishing
SkriptLang/Skript pull request #7137
Opened 2024-10-08 17:53 UTC by Efnilite

### Description

Continues #4284.

- Added fishing state
- Added fishing hook
- Added caught entity
- Added dropped XP of fishing event
- Added condition hook is in open water (seems to be bugged from spigot as it always return true even when in 1x1x1 water block or no water at all)
- Added pull hooked entity effect
- Added bucket entity event + expression
- Added fishing lure expr
- Added hooked entity expr
- Added hook waiting time

Thanks @AyhamAl-Ali!

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-10-08 17:58 UTC, erenkarakal commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +    	//HorseJumpEvent
indent another time >:(

2024-10-15 19:35 UTC, Efnilite commented
good luck :)

2024-10-15 19:59 UTC, sovdeeth reviewed
needs some tests for invalid things, like max wait time < min wait time, infinities, NaNs, etc.

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +				.user("fish(ing)? ?hooks")
```suggestion
				.user("fish(ing)? ?hooks?")
```

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
> +		Classes.registerClass(new ClassInfo<>(FishHook.class, "fishinghook")
Why is this a class? It's just an entity.

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondFishingInfluenced.java
> +	}
```suggestion
	}

```

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/conditions/CondIsInOpenWater.java
> +@Description("Checks whether the fish hook is in open water.")
what does open water actually mean

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffFishingLure.java
> +@Description("Returns whether the lure enchantment should be applied to reduce the wait time.")
doesn't return anything

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffFishingLure.java
> +			"remove [the] lure enchantment");
```suggestion
			"apply [the] lure enchantment bonus",
			"remove [the] lure enchantment bonus");
```
want to be clear we're not removing the enchantment itself.

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffFishingLure.java
> +	}
```suggestion
	}

```

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/events/EvtBucketEntity.java
> +	private List<EntityData<?>> entities = new ArrayList<>(0);
why a list and not just the array from getAll?

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprEntityBucket.java
> +public class ExprEntityBucket extends SimpleExpression<ItemStack> {
this is pretty awkward wording. Is `future event-item` not available?

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprFishingApproachAngle.java
> +	"Returns the angle at which the fish will approach the fishing hook, after the wait time.",
what is the angle relative to?

2024-10-15 19:59 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprFishingBiteTime.java
> +			case REMOVE -> hook.setTimeUntilBite(hook.getTimeUntilBite() - ticks);
needs bounds checking

2024-10-15 19:59 UTC, sovdeeth requested changes
forgot to click request

2024-11-12 10:57 UTC, Moderocky approved these changes

2024-11-15 23:16 UTC, sovdeeth requested changes

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprExperience.java
> +@Since("2.1, 2.5.3 (block break event), 2.7 (experience change event), INSERT VERSION (breeding event), INSERT VERSION (fishing)")
```suggestion
@Since("2.1, 2.5.3 (block break event), 2.7 (experience change event), INSERT VERSION (breeding, fishing)")
```

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/CondFishingLure.java
> +			return false;
should probably assert trap or exception but doesn't really matter

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/CondFishingLure.java
> +	}
```suggestion
	}

```

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EffPullHookedEntity.java
> +		Skript.registerEffect(EffPullHookedEntity.class, "(reel|pull) [in] hook[ed] entity");
i don't really like in being optional tbh, it feels a bit strange
i think either `pull in hooked entity` or `pull hooked entity in`

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprEntityBucket.java
> +			"[the] (future|resulting) [event][-| ]item [bucket]");
i don't think this should pretend to be an event-value
Can't you just register a future item event value for the bucket event?

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingApproachAngle.java
> +				}
are these safe without clamping?

2024-11-15 23:16 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingWaitTime.java
> +			}
same with clamp safety

2024-11-15 23:16 UTC, sovdeeth commented on src/test/skript/junit/EvtFish.sk
> +		parse:
```suggestion
	parse if method "org.bukkit.entity.FishHook#getTimeUntilBite" exists:
```

2024-11-15 23:16 UTC, sovdeeth commented on src/test/skript/junit/EvtFish.sk
> +		parse:
```suggestion
	parse if method "org.bukkit.entity.FishHook#getTimeUntilBite" exists:
```

2024-12-08 00:44 UTC, sovdeeth approved these changes

2024-12-08 00:44 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingBiteTime.java
> +	}
does this really need to exist

2024-12-08 00:44 UTC, sovdeeth commented on src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingWaitTime.java
> +	}
likewise

2024-12-18 11:46 UTC, merged