Fix leather horse armor being unequipable
SkriptLang/Skript pull request #7141
Opened 2024-10-09 17:54 UTC by Efnilite

### Description
Fixes #7140.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-10-09 20:33 UTC, cheeezburga commented
Leather horse armour was only added in 1.14, and I think the 1.20.6+ test is resolved by #6849?

2024-10-10 15:00 UTC, Efnilite commented
Tests failing due to a 1.20.6-only Paper bug (https://github.com/PaperMC/Paper/pull/11139).

2024-10-12 03:20 UTC, cheeezburga approved these changes

2024-10-12 04:18 UTC, sovdeeth requested changes

2024-10-12 04:18 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffEquip.java
> +		}
why isn't this a version check

2024-10-12 04:18 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffEquip.java
> +				"unequip %livingentities%'[s] (armor|equipment)");
```suggestion
				"unequip %livingentities%'[s] (armo[u]r|equipment)");
```
while we're here

2024-10-12 13:49 UTC, sovdeeth approved these changes

2024-10-12 13:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffEquip.java
> +				Material.DIAMOND_HORSE_ARMOR, Material.LEATHER_HORSE_ARMOR);
needs 2 tabs

2024-10-12 13:49 UTC, sovdeeth commented on src/main/java/ch/njol/skript/effects/EffEquip.java
> +				Material.DIAMOND_HORSE_ARMOR);
2 tabs

2024-10-26 14:32 UTC, Moderocky approved these changes

2024-10-31 18:09 UTC, merged