Add some test expressions
SkriptLang/Skript pull request #7142
Opened 2024-10-10 18:06 UTC by Efnilite

### Description
Adds some test expressions which I felt were missing.

- `test world` can now be used instead of `world "world"`
- `test location` can now be used instead of `spawn of world "world"`

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-10-10 18:07 UTC, Fusezion approved these changes

2024-10-11 04:29 UTC, NotSoDelayed commented
There’s `event-location` in tests
https://github.com/SkriptLang/Skript/blob/ba32d7ad48edb8e33d5f5d2e44d03bba94ffb2de/src/main/java/ch/njol/skript/test/runner/EvtTestCase.java#L45-L59

2024-10-11 15:19 UTC, Efnilite commented
> There’s `event-location` in tests
> 
> https://github.com/SkriptLang/Skript/blob/ba32d7ad48edb8e33d5f5d2e44d03bba94ffb2de/src/main/java/ch/njol/skript/test/runner/EvtTestCase.java#L45-L59

this is used in like 5 tests, also `test-location` looks nicer :)

2024-10-11 18:59 UTC, TheLimeGlass commented
I don't like the removal of the `event-%classinfo%` also could be used by external addons using the testing suite.

I don't mind having test-%classinfo% but I prefer event-%classinfo% more. I have no say, so I don't want to review this.

2024-10-12 02:46 UTC, NotSoDelayed commented
I agree, removing `event-*` without a grace period is a breaking change.

2024-10-12 03:28 UTC, cheeezburga approved these changes
Looks good!

2024-10-12 04:19 UTC, sovdeeth requested changes
seems good but no reason to remove the event values

2024-10-12 13:52 UTC, sovdeeth requested changes
just some formatting

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/EvtTestCase.java
> +				.since("2.5");
2 tabs

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestBlock.java
> +				"[the] test(-| )block");
2 tabs

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestBlock.java
> +	}
```suggestion
	}

```

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestLocation.java
> +				"[the] test(-| )location");
2t

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestLocation.java
> +	}
```suggestion
	}

```

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestWorld.java
> +				"[the] test(-| )world");
2t

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestWorld.java
> +	}
```suggestion
	}

```

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestWorld.java
> +
```suggestion
```

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestLocation.java
> +
```suggestion
```

2024-10-12 13:52 UTC, sovdeeth commented on src/main/java/ch/njol/skript/test/runner/ExprTestBlock.java
> +
```suggestion
```

2024-10-12 23:16 UTC, sovdeeth approved these changes

2024-10-17 18:03 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/test/runner/ExprTestBlock.java
> +		"\tassert last spawned zombie's world is test world with \"zombie did not spawn in test world\""
call me crazy, but "test block" is not used here at all?

2024-10-17 18:04 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/test/runner/ExprTestLocation.java
> +		"\tset test block to air"
Oh... here it is?!?! I think you swapped test block/location examples.

2024-10-26 14:33 UTC, Moderocky approved these changes

2024-10-26 19:26 UTC, merged