Make EntryValidator validation not case-sensitive
SkriptLang/Skript pull request #7143
Opened 2024-10-12 21:17 UTC by erenkarakal

### Description
This PR makes all entries in KeyValueEntryData's lowercase when comparing.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #7138

2024-10-12 21:25 UTC, Efnilite approved these changes

2024-10-12 21:26 UTC, sovdeeth approved these changes

2024-10-12 21:27 UTC, UnderscoreTud approved these changes

2024-10-12 21:27 UTC, UnderscoreTud commented on src/main/java/org/skriptlang/skript/lang/entry/KeyValueEntryData.java
>  		return key.startsWith(getKey() + getSeparator());
```suggestion
		return key.startsWith((getKey() + getSeparator()).toLowerCase(Locale.ENGLISH));
```

2024-10-13 04:19 UTC, APickledWalrus requested changes
This probably needs done for the other canCreateWith implementations

You might also prefer using https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#regionMatches(boolean,int,java.lang.String,int,int)

2024-10-29 13:50 UTC, erenkarakal commented
> This probably needs done for the other canCreateWith implementations

other implementations seem to be ignoring text cases already

2024-10-29 14:01 UTC, APickledWalrus approved these changes

2024-10-31 17:27 UTC, merged