Add experience point support to ExprTotalExperience
SkriptLang/Skript pull request #7144
Opened 2024-10-12 23:48 UTC by erenkarakal

### Description
This PR adds 'experience point' support to the total experience expression and some tests.
The reason I made this PR is for the "on level progress change:" event. It did not let you get how much experience was changed as a number.
```
on level progress change:
  set {_xp} to event-experience     <--- what can you even do with this besides giving it to a player
```

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-10-13 00:58 UTC, Efnilite requested changes
and test could include reset or delete

2024-10-13 00:58 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
> +	public Integer convert(Object object) {
```suggestion
	public @Nullable Integer convert(Object object) {
```

2024-10-13 00:58 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
>  	public Class<?>[] acceptChange(ChangeMode mode) {
```suggestion
	public @Nullable Class<?>[] acceptChange(ChangeMode mode) {
```

2024-10-13 00:58 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
> +			case ADD, REMOVE, SET, DELETE, RESET -> new Class[]{Number.class};
Can't this be Integer?

2024-10-13 01:02 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
>  	public Class<?>[] acceptChange(ChangeMode mode) {
wrong spot

2024-10-13 01:13 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
>  	public Class<?>[] acceptChange(ChangeMode mode) {
reviewing on mobile moment

2024-10-13 15:37 UTC, sovdeeth approved these changes

2024-10-13 15:37 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
> +		}
choose braces or no braces

2024-10-26 14:33 UTC, Moderocky approved these changes

2025-02-05 15:52 UTC, closed without merging