Fix expression conversion
SkriptLang/Skript pull request #7165
Opened 2024-10-27 15:42 UTC by UnderscoreTud

### Description
This PR fixes an issue where the parser wouldn't attempt to convert an expression if `Expression#canReturn(Class)` returns `true`. Causing issues when an expression *could* return a certain type but doesn't once evaluated. For instance, adding two unset variables, which can potentially return variety of types (such as a string), and using the expression in a pattern that expects strings (e.g., `formatted ({_foo} + {_bar})` would result in a [stack trace](https://pastebin.com/C9h1LrCh) being thrown because the array returned from the arithmetic expression wasn't converted to a string array.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7164

2024-10-27 15:50 UTC, sovdeeth approved these changes

2024-10-27 15:50 UTC, sovdeeth commented on src/main/java/ch/njol/skript/lang/SkriptParser.java
> +							return null;
do you think it's worth making a helper method since this is duplicated?

2024-10-27 18:04 UTC, Moderocky approved these changes

2024-11-01 17:07 UTC, APickledWalrus requested changes
Will review in depth soon. tud and I discussed some potential issues/edge cases that still need fixed

2024-12-30 00:08 UTC, sovdeeth commented on src/main/java/ch/njol/skript/lang/SkriptParser.java
> +						if (type.isAssignableFrom(parsedReturnType)) {
what's the logic for not using canReturn?

2024-12-30 00:08 UTC, sovdeeth commented on src/main/java/ch/njol/skript/lang/SkriptParser.java
> +						if (type.isAssignableFrom(parsedReturnType)) {
oh i think that was explained in the original pr

2024-12-30 00:14 UTC, sovdeeth approved these changes

2024-12-30 01:11 UTC, APickledWalrus commented
I've gone ahead and moved the logic out of SimpleExpression and into ConvertedExpression. This is to preserve the behavior of expressions overriding the method AND that the logic/handling for this is consistent across Skript. The `canReturn` logic has been moved out of SkriptParser, as its usage there is an incorrect assertion (an object that might be `Expression<A>` or `Expression<B>`  is NOT the same as `Expression<A>`, so we cannot return it as one). It has to be handled by ConvertedExpression so that we can ensure arrays are typed correctly (the root problem).

2024-12-30 06:23 UTC, Moderocky approved these changes

2024-12-30 06:24 UTC, merged