Item Skull Owner
SkriptLang/Skript pull request #7174
Opened 2024-11-01 06:08 UTC by TheAbsolutionism

### Description
This PR aims to allow items to be used in ExprSkullOwner

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7171

2024-11-01 07:36 UTC, NotSoDelayed commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +	"set skull owner of player's tool to \"Njol\" parsed as offlineplayer"
Suggestion for a different value such as `{_player}` since the one above already showcased one of the possibilities

2024-11-01 11:36 UTC, Efnilite requested changes
tests :pleading_face:

2024-11-01 11:36 UTC, Efnilite commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +@Since("2.9.0, INSERT VERSION (items)")
```suggestion
@Since("2.9.0, INSERT VERSION (of items)")
```

2024-11-01 21:28 UTC, Efnilite approved these changes

2024-11-01 21:28 UTC, Efnilite commented on src/test/skript/tests/syntaxes/expressions/ExprSkullOwner.sk
> +test "skull owner - block":
```suggestion
test "skull owner - block":
```

2024-11-01 21:28 UTC, Efnilite commented on src/test/skript/tests/syntaxes/expressions/ExprSkullOwner.sk
> +	set {_loc} to spawn of world "world" ~ vector(3,3,3)
```suggestion
	set {_loc} to test-location
```

2024-11-01 23:25 UTC, TheAbsolutionism commented on src/test/skript/tests/syntaxes/expressions/ExprSkullOwner.sk
> +	set {_loc} to spawn of world "world" ~ vector(3,3,3)
Is `test-location` something new?

2024-11-01 23:43 UTC, Efnilite commented on src/test/skript/tests/syntaxes/expressions/ExprSkullOwner.sk
> +	set {_loc} to spawn of world "world" ~ vector(3,3,3)
yea, #7142

2024-11-02 00:10 UTC, cheeezburga approved these changes
Looks good. Are the deprecated method calls able to be replaced with updated ones? I only had a quick glance at the api, but could stuff like `setOwner("")` be replaced with `setOwningPlayer(null)`, and stuff like that?

2024-11-02 01:49 UTC, NotSoDelayed approved these changes

2024-11-15 22:02 UTC, sovdeeth approved these changes

2024-11-15 22:02 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
> +				skullItem.setItemMeta(skullMeta);
this should be in the slot if statement

2024-11-30 14:31 UTC, Moderocky approved these changes

2024-12-15 01:21 UTC, merged