Fixed when using tab complet, if the target is a Linux softlink folde…
SkriptLang/Skript pull request #7186
Opened 2024-11-03 05:06 UTC by killertuling

…r, it will not be accessed

### Description
Fixed where tab complet would not scan for .sk files within symlinked directories under the scripts folder. 
This PR resolves the problem of not being able to scan these directories. 
I have tested it, and after the modification, symlinked directories can be accessed normally. 
The operating system I used is Ubuntu Server 24.04.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-11-03 05:10 UTC, Efnilite requested changes

2024-11-03 05:10 UTC, Efnilite commented on src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
> +			try (Stream<Path> files = Files.walk(scripts.toPath(), java.nio.file.FileVisitOption.FOLLOW_LINKS)) {
```suggestion
			try (Stream<Path> files = Files.walk(scripts.toPath(), FileVisitOption.FOLLOW_LINKS)) {
```

2024-11-03 14:19 UTC, Efnilite approved these changes

2024-11-05 22:02 UTC, sovdeeth approved these changes

2024-11-23 09:17 UTC, Efnilite commented
branch needs to be updated before this can be merged

2024-12-15 01:23 UTC, sovdeeth commented
This PR's source branch is contaminated. Please pull these changes into a separate branch (NOT master). You may have to make a new PR.

2024-12-15 18:10 UTC, closed without merging