Updates SyntaxStringBuilder to return itself
SkriptLang/Skript pull request #7244
Opened 2024-12-07 08:13 UTC by cheeezburga

### Description
Makes the SyntaxStringBuilder's append methods return itself

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

2024-12-07 08:50 UTC, Moderocky approved these changes

2024-12-07 09:01 UTC, Efnilite commented
You can already chain arguments like this
```java
builder.append(x, "and", y);
```
Which is more readable than chained append calls on a single line (`builder.append(x).append("and").append(y)`) and the example you provided. This is something me and sovde have already discussed :)

This also encourages ternaries inside the append methods, as this encourages putting everything into a single expression, instead of being spread out over multiple statements with explicit `if`s, the latter of which has better readability. Essentially, this would allow the SSB to be used in the same way as the massive string concatenations used currently, but without the `toString(event, debug)`.

This is against the point of the SSB, which makes the `toString` more readable by forcing you to be explicit, which does sacrifice brevity.

Because of the unexpected popularity of the SSB, we may want to consider adding support for easy one-liners to it, e.g.
```java
new SyntaxStringBuilder(event, debug).single(x, "and", y);
```
Or similar. Personally, I support this, but a better solution should probably be discussed.

2024-12-07 09:09 UTC, cheeezburga commented
> You can already chain arguments like this
> 
> ```java
> builder.append(x, "and", y);
> ```
> 
> Which is more readable than chained append calls on a single line (`builder.append(x).append("and").append(y)`) and the example you provided. This is something me and sovde have already discussed :)
I still think there's merit in having it return itself. The behaviour you describe is still there obviously, but I think this just adds an alternative which could be useful. If I'm alone in this line of thinking, then I can close it, but it seems like there's no downside to it.

2024-12-07 09:38 UTC, Fusezion commented
> I still think there's merit in having it return itself. The behaviour you describe is still there obviously, but I think this just adds an alternative which could be useful. If I'm alone in this line of thinking, then I can close it, but it seems like there's no downside to it.

I prefer having `.append()` return, imo it's nicer and easier to read at times than seeing an array of arguments

2024-12-08 05:54 UTC, sovdeeth approved these changes

2024-12-08 10:20 UTC, Efnilite requested changes

2024-12-08 10:20 UTC, Efnilite commented on src/main/java/ch/njol/skript/lang/SyntaxStringBuilder.java
>  	 */
```suggestion
	 * Spaces are automatically added between the provided objects.
	 *
	 * @param objects The objects to add.
	 * @returns The builder.
	 */
```

2024-12-08 10:20 UTC, Efnilite commented on src/main/java/ch/njol/skript/lang/SyntaxStringBuilder.java
>  	 */
```suggestion
	 * @param object The object to add.
	 * @returns The builder.
	 */
```

2024-12-09 13:53 UTC, Efnilite approved these changes

2024-12-15 03:54 UTC, merged