API for custom default values during parsing.
SkriptLang/Skript pull request #7256
Opened 2024-12-12 02:42 UTC by sovdeeth

### Description

Adds an api for declaring custom default values during parsing. Does not apply to runtime defaults like arithmetic.
The goal of this is to provide a slightly easier method for section to provide section-specific defaults without having to create an entire custom event and change the context.

I think this implementation might be a little rough and would welcome critiques.

Example:
```java
		// Add custom default value
		data.addDefaultValue(Number.class, new SimpleLiteral((Number) 7, true));

		// parse section with custom value
		loadCode(sectionNode);

		// remove custom value
		data.removeDefaultValue(Number.class);
```

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-12-12 02:43 UTC, sovdeeth commented
Just realized this needs to support multiple layers of default values. Will fix Friday.

2024-12-12 13:36 UTC, Moderocky approved these changes

2024-12-13 05:46 UTC, sovdeeth commented
I would like some thoughts on how/whether to handle cases where context completely changes.
Perhaps a clearDefaults() and restoreDefaults() method? Maybe defaults should be tied to event/a context generic?
not sure, would like suggestions

2025-01-18 20:40 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/SkriptParser.java
> +			expr = data.getDefaultValue(exprInfo.classes[0].getC());
```suggestion
		DefaultValueData data = getParser().getData(DefaultValueData.class);
		if (data != null)
			expr = data.getDefaultValue(exprInfo.classes[0].getC());
```
I don't believe `data` will ever be null. `getData()` is not null/will create a new instance if it does not exist

2025-06-05 16:16 UTC, APickledWalrus requested changes
This looks pretty good. Just have a few comments I'd like discussion on before merging

2025-06-05 16:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/test/runner/ExprDefaultNumberValue.java
> +public class ExprDefaultNumberValue extends SimpleExpression<Number> {
does it need annotated as NoDoc?

2025-06-05 16:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/parser/DefaultValueData.java
> +		Deque<DefaultExpression<?>> stack =  defaults.get(type);
```suggestion
		Deque<DefaultExpression<?>> stack = defaults.get(type);
```

2025-06-05 16:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/parser/DefaultValueData.java
> +		Deque<DefaultExpression<?>> stack =  defaults.get(type);
```suggestion
		Deque<DefaultExpression<?>> stack = defaults.get(type);
```

2025-06-05 16:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/parser/DefaultValueData.java
> +		if (stack != null && !stack.isEmpty())
I wonder if we should throw an exception here if the stack is null/empty? e.g. preventing unbalanced add/remove usage

2025-06-05 16:16 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/lang/parser/DefaultValueData.java
> +	public <T> @Nullable DefaultExpression<T> getDefaultValue(Class<T> type) {
Do you think we should attempt to check assignable types if a direct lookup doesn't work? E.g. if a `Number.class` default value exists and we request `Integer.class`

2025-06-29 23:12 UTC, sovdeeth commented on src/main/java/ch/njol/skript/lang/parser/DefaultValueData.java
> +	public <T> @Nullable DefaultExpression<T> getDefaultValue(Class<T> type) {
It didn't do that previously, so for now I think it should stick to simple behavior. I think we can explore this with a later pr.

2025-06-30 00:26 UTC, APickledWalrus approved these changes

2025-06-30 02:42 UTC, merged