Elytra Boost
SkriptLang/Skript pull request #7283
Opened 2024-12-19 18:54 UTC by TheAbsolutionism

### Description
This PR aims to add Paper's PlayerElytraBoostEvent

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5826

2024-12-19 18:59 UTC, APickledWalrus requested changes
Looks pretty good. I mainly have some formatting concerns.

2024-12-19 18:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffElytraBoostConsume.java
> +				"prevent [the] (boosting|used) firework from being consumed",
```suggestion
				"(prevent|disallow) [the] (boosting|used) firework from being consumed",
```
Just as another option

2024-12-19 18:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffElytraBoostConsume.java
> +	private static final boolean ELYTRA_BOOST_EXISTS = Skript.classExists("com.destroystokyo.paper.event.player.PlayerElytraBoostEvent");
Since this is only used in the static field, you can just check this condition there

2024-12-19 18:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondElytraBoostConsume.java
> +	private static final boolean ELYTRA_BOOST_EXISTS = Skript.classExists("com.destroystokyo.paper.event.player.PlayerElytraBoostEvent");
Since this is only used in the static field, you can just check this condition there

2024-12-19 18:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/conditions/CondElytraBoostConsume.java
> +			Skript.error("This can only be used in an 'elytra boost' event.");
```suggestion
			Skript.error("This condition can only be used in an 'elytra boost' event.");
```

2024-12-19 18:59 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffElytraBoostConsume.java
> +			Skript.error("This can only be used in an 'elytra boost' event.");
```suggestion
			Skript.error("This effect can only be used in an 'elytra boost' event.");
```

2024-12-19 20:10 UTC, Efnilite approved these changes

2024-12-19 20:10 UTC, Efnilite commented on src/main/java/ch/njol/skript/conditions/CondElytraBoostConsume.java
> +				"[the] (boosting|used) firework will not be consumed");
```suggestion
				"[the] (boosting|used) firework (will not|won't) be consumed");
```

2024-12-19 20:54 UTC, APickledWalrus requested changes
A few final touches. Re-request for approval 🙂

2024-12-19 20:54 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/effects/EffElytraBoostConsume.java
> +		return "prevent the boosting firework from being consume";
```suggestion
		return "prevent the boosting firework from being consumed";
```

2024-12-19 20:54 UTC, APickledWalrus commented on src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/PlayerElytraBoostEventTest.java
> +		}
```suggestion
		EntityType entityType = EntityType.valueOf("FIREWORK");
		if (entityType == null) {
			entityType = EntityType.valueOf("FIREWORK_ROCKET");
		}
```
To simplify a little

2024-12-19 20:54 UTC, APickledWalrus commented on src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/PlayerElytraBoostEventTest.java
> +				event = (Event) constructor.newInstance(player, new ItemStack(Material.FIREWORK_ROCKET), firework,  EquipmentSlot.HAND);
```suggestion
				event = (Event) constructor.newInstance(player, new ItemStack(Material.FIREWORK_ROCKET), firework, EquipmentSlot.HAND);
```

2024-12-20 14:46 UTC, APickledWalrus approved these changes
good stuff

2024-12-20 14:46 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/events/SimpleEvents.java
> +				.examples("on elytra boost:")
i'd include the condition/effect in this example

2024-12-24 10:55 UTC, Moderocky approved these changes
Looks good.

2024-12-24 10:59 UTC, merged