The End of the Getter era
SkriptLang/Skript pull request #7285
Opened 2024-12-19 20:37 UTC by Efnilite

### Description
Removes Getter from BukkitEventValues.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-12-19 23:35 UTC, sovdeeth requested changes
only looked at a few but it applies to everything

2024-12-19 23:35 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprFoodLevel.java
> +				return 0.5f * ((FoodLevelChangeEvent) e).getFoodLevel();
variable names

2024-12-19 23:35 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprTool.java
> +			public Slot convert(final LivingEntity ent) {
why not lambda

2024-12-19 23:35 UTC, sovdeeth commented on src/main/java/ch/njol/skript/expressions/ExprWeather.java
> +				return WeatherType.fromWorld(w);
variable names and pattern matching

2024-12-20 21:56 UTC, APickledWalrus requested changes
Looks pretty good. In BukkitEventValues, there are cases where pattern matching, and TIME constants can be used. I highlighted one of each I noticed.

2024-12-20 21:56 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +		EventValues.registerEventValue(EntityEvent.class, CommandSender.class, EntityEvent::getEntity, 0, "Use 'attacker' and/or 'victim' in damage/death events", EntityDamageEvent.class, EntityDeathEvent.
```suggestion
		EventValues.registerEventValue(EntityEvent.class, Entity.class, EntityEvent::getEntity, TIME_NOW, "Use 'attacker' and/or 'victim' in damage/death events", EntityDamageEvent.class, EntityDeathEvent.class);
		EventValues.registerEventValue(EntityEvent.class, CommandSender.class, EntityEvent::getEntity, TIME_NOW, "Use 'attacker' and/or 'victim' in damage/death events", EntityDamageEvent.class, EntityDeathEvent.class);
```

2024-12-20 21:56 UTC, APickledWalrus commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return (Projectile) e.getDamager();
```suggestion
			if (e.getDamager() instanceof Projectile projectile)
				return projectile;
```

2024-12-20 23:15 UTC, TheAbsolutionism requested changes
Would be cool if you updated these while you're at it

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return (Projectile) ((EntityDamageByEntityEvent) ldc).getDamager();
```suggestion
			if (ldc instanceof EntityDamageByEntityEvent damageEvent && damageEvent.getDamager() instanceof Projectile projectile)
				return (Projectile) projectile;
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return ((HangingBreakByEntityEvent) e).getRemover();
```suggestion
			if (e instanceof HangingBreakByEntityEvent hangingEvent)
				return hangingEvent.getRemover();
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +		EventValues.registerEventValue(CommandEvent.class, World.class, e -> e.getSender() instanceof Player ? ((Player) e.getSender()).getWorld() : null);
```suggestion
		EventValues.registerEventValue(CommandEvent.class, World.class, e -> e.getSender() instanceof Player player ? player.getWorld() : null);
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return ((CraftItemEvent) e).getRecipe().getResult();
```suggestion
			if (e instanceof CraftItemEvent craftEvent)
				return craftEvent.getRecipe().getResult();
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +		EventValues.registerEventValue(InventoryClickEvent.class, Player.class, e -> e.getWhoClicked() instanceof Player ? (Player) e.getWhoClicked() : null);
```suggestion
		EventValues.registerEventValue(InventoryClickEvent.class, Player.class, e -> e.getWhoClicked() instanceof Player player ? player : null);
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return new ch.njol.skript.util.slot.EquipmentSlot(((PlayerInventory) invi).getHolder(), slotIndex);
```suggestion
			if (invi instanceof PlayerInventory playerInv && slotIndex >= 36) {
				return new ch.njol.skript.util.slot.EquipmentSlot(playerInv.getHolder(), slotIndex);
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +		EventValues.registerEventValue(InventoryDragEvent.class, Player.class, event -> event.getWhoClicked() instanceof Player ? (Player) event.getWhoClicked() : null);
```suggestion
		EventValues.registerEventValue(InventoryDragEvent.class, Player.class, event -> event.getWhoClicked() instanceof Player player ? player : null);
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return (Player) first;
```suggestion
			if (first instanceof Player player) // Needs to be player... Usually it is
				return player;
```

2024-12-20 23:15 UTC, TheAbsolutionism commented on src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
> +				return ((Keyed) recipe).getKey().toString();
```suggestion
			if (recipe instanceof Keyed recipeKey)
				return recipeKey.getKey().toString();
```

2024-12-21 18:30 UTC, TheAbsolutionism approved these changes

2024-12-21 18:31 UTC, Burbulinis approved these changes
thank you for your service, getters!

2024-12-22 11:16 UTC, Moderocky approved these changes

2024-12-23 13:33 UTC, Moderocky approved these changes

2024-12-26 20:04 UTC, sovdeeth approved these changes

2024-12-31 05:14 UTC, APickledWalrus approved these changes

2024-12-31 12:46 UTC, Moderocky commented
You almost reintroduced the ignite block issue 😬

2024-12-31 13:15 UTC, merged