'sk test' command upgrades
SkriptLang/Skript pull request #7308
Opened 2024-12-23 21:54 UTC by ShaneBeee

### Description
This PR aims to enhance the `/sk test` command:
- Add test script names to tab complete (from the Test script directory)
- Allow using `/sk test all` to run all of your test scripts

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-12-24 18:10 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +						if (!fileName.endsWith(".sk") && !fileName.endsWith("/"))
At the point of this check, its just a file name, so I cant check if its a directory.

This is going off of what is provided from tab complete:
<img width="332" alt="Screenshot 2024-12-24 at 10 10 02 AM" src="https://github.com/user-attachments/assets/518d614e-3faf-487f-b588-8b32a031e2fa" />
At this point, scripts end with `.sk` whereas directories end with `/`

2024-12-26 21:43 UTC, sovdeeth requested changes

2024-12-26 21:43 UTC, sovdeeth commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +						if (!fileName.endsWith(".sk") && !fileName.endsWith("/"))
I don't think that'd match reload's behavior though. reload's smart enough to detect directories that don't end in /, so I think this command should too.

2024-12-26 21:46 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +						if (!fileName.endsWith(".sk") && !fileName.endsWith("/"))
I'll take a peak at the reload code later and see if I can replicate.

2024-12-26 22:09 UTC, ShaneBeee commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +						if (!fileName.endsWith(".sk") && !fileName.endsWith("/"))
Ok, I saw that "reload" uses some static methods.
I just had to refactor the methods (and add some overloads) to just grab the scripts from the test directory using those methods.
This all works splendidly now.

2024-12-26 22:46 UTC, sovdeeth approved these changes

2024-12-27 12:10 UTC, cheeezburga approved these changes

2024-12-27 23:22 UTC, Efnilite approved these changes

2024-12-27 23:22 UTC, Efnilite commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +	private static File getScriptFromArgs(CommandSender sender, String[] args, File directoryFile) {
```suggestion
	private static @Nullable File getScriptFromArgs(CommandSender sender, String[] args, File directoryFile) {
```

2024-12-27 23:22 UTC, Efnilite commented on src/main/java/ch/njol/skript/SkriptCommand.java
> +	public static File getScriptFromName(String script, File directoryFile) {
```suggestion
	public static @Nullable File getScriptFromName(String script, File directoryFile) {
```

2024-12-29 22:03 UTC, merged