Registration API Fixes/Enhancements
SkriptLang/Skript pull request #7333
Opened 2024-12-31 04:32 UTC by APickledWalrus

### Description
This PR aims to fix Registration API bugs, make enhancements as necessary, and significantly expand (create) test coverage.

As part of my changes, I have reworked JUnit Test Loading. Simply, files ending in `Test` are treated as test files. This enables us to place test classes at the same location as the classes they are testing. For example, a test for `org.skriptlang.skript.util.Priority` is placed at `org.skriptlang.skript.util.PriorityTest`. Some test-specific classes have been renamed to work with this change.

Bug Fixes:
- Fixed some fields mistakenly marked as static in `SkriptImpl` (caused issues when creating multiple SkriptImpl instances)

Enhancements:
- JUnit Test loading changes (described above)
- ClassLoader utility improvements
  - `basePackage` can now be empty, meaning the search begins at the root (all classes)
  - Added a `filter` predicate option, providing greater control over what classes are allowed to even load (based on FQN checking)
- Added tests for the following classes/interfaces: `Skript`, `ClassLoader`, `ClassUtils`, `Priority`

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

2024-12-31 04:36 UTC, sovdeeth approved these changes

2025-01-03 12:22 UTC, Efnilite commented on src/test/java/org/skriptlang/skript/util/PriorityTest.java
> +		Assert.assertTrue(base.before().isEmpty());
these could probably be static imports. same for the rest of the tests

2025-01-06 15:25 UTC, Efnilite approved these changes

2025-01-06 15:25 UTC, Efnilite commented on src/main/java/org/skriptlang/skript/util/Builder.java
> -		B builder();
what's the reason for this change

2025-01-06 15:31 UTC, APickledWalrus commented on src/main/java/org/skriptlang/skript/util/Builder.java
> -		B builder();
it's a bit too simplistic as a name (and some of these classes often have static methods like `builder`, e.g. `ClassLoader.builder()`). I think `toBuilder` reflects the method's purpose well (if not better)

2025-01-06 16:33 UTC, Moderocky requested changes
On balance, I think the `org.skriptlang.skript.util.Builder` class ought to be scrapped entirely before it goes into use.
It seems like overzealous abstraction, trying to solve a problem that doesn't exist.

The generic type parameters are also becoming a bit ridiculous.
The (2) utilities it provides are probably very specific and I'm not sure the abstraction has any real use, since you'd never really be treating an object as an abstract 'builder' (you couldn't really use any methods from it), but as the class it actually is.

The one place I could see you might use it is wanting to accept something like a `Builder<SyntaxElement>` or a `Builder<XYZ>` and then call its `build()` method, but realistically this is just functioning as a `Supplier<...>` and you could simply pass a method reference of anything's `build` method like this.

Fortunately, I don't think anything is using this yet, so it shouldn't be a problem to get rid of it.

2025-01-15 17:12 UTC, merged